#!/usr/bin/env node
// ============================================================
// Instructional-video resolver: for every exercise in the
// catalog without a hand-verified videoId, search YouTube for a
// short how-to and pick the best scoring result. Emits
// src/plan/videoMap.ts (exerciseId → videoId).
//
// Run:  node tools/resolveVideos.mjs
// Re-run whenever exercises are added. Hand-verified videoId
// fields on ExerciseDef always win over this map.
// ============================================================
import { readFileSync, writeFileSync } from 'node:fs'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'

// Node's fetch ignores HTTPS_PROXY; curl honors it (and the CA bundle),
// so all traffic goes through the environment's agent proxy.
const run = promisify(execFile)
async function fetchText(url) {
  const { stdout } = await run('curl', ['-s', '--max-time', '20', '-H', 'accept-language: en-US,en', url], {
    maxBuffer: 32 * 1024 * 1024,
  })
  return stdout
}

const FILES = ['src/plan/exercises.ts', 'src/plan/athleticExercises.ts']

// Pull id / name / videoId with a tolerant scan (data files are regular)
function extractDefs(src) {
  const defs = []
  const re = /id: '([^']+)',\s*\n\s*name: '([^']+)',/g
  let m
  while ((m = re.exec(src))) {
    const tail = src.slice(m.index, m.index + 600)
    const vid = tail.match(/videoId: '([^']+)'/)
    defs.push({ id: m[1], name: m[2], videoId: vid?.[1] })
  }
  return defs
}

const expand = (name) =>
  name
    .replace(/\bDB\b/g, 'dumbbell')
    .replace(/\bOHP\b/g, 'overhead press')
    .replace(/\bRDL\b/g, 'Romanian deadlift')
    .replace(/\(.*?\)/g, '')
    .trim()

function parseDuration(t) {
  if (!t) return null
  const parts = t.split(':').map(Number)
  if (parts.some(Number.isNaN)) return null
  return parts.reduce((s, p) => s * 60 + p, 0)
}

function score(video, tokens) {
  const title = video.title.toLowerCase()
  let s = 0
  const hits = tokens.filter((t) => title.includes(t)).length
  if (hits === 0) return -1 // must mention the movement at all
  s += hits * 3
  if (/how to|form|technique|tutorial|guide|properly/.test(title)) s += 3
  if (video.sec !== null) {
    if (video.sec >= 40 && video.sec <= 300) s += 4 // short instructional sweet spot
    else if (video.sec <= 600) s += 1
    else s -= 3 // no 20-minute podcasts
  }
  if (/\bshorts?\b/.test(title)) s += 1
  return s
}

async function searchYouTube(query) {
  const url = `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`
  const html = await fetchText(url)
  if (!html) return []
  const m = html.match(/var ytInitialData = (\{.+?\});<\/script>/s)
  if (!m) return []
  let data
  try {
    data = JSON.parse(m[1])
  } catch {
    return []
  }
  const out = []
  const walk = (node) => {
    if (!node || typeof node !== 'object' || out.length > 30) return
    if (node.videoRenderer?.videoId) {
      const v = node.videoRenderer
      out.push({
        id: v.videoId,
        title: v.title?.runs?.[0]?.text ?? '',
        sec: parseDuration(v.lengthText?.simpleText),
      })
      return
    }
    for (const k of Object.keys(node)) walk(node[k])
  }
  walk(data)
  return out
}

const defs = FILES.flatMap((f) => extractDefs(readFileSync(f, 'utf8')))
console.log(`catalog: ${defs.length} exercises, ${defs.filter((d) => d.videoId).length} hand-verified`)

const map = {}
let miss = 0
for (const def of defs) {
  if (def.videoId) continue
  const clean = expand(def.name)
  const tokens = clean.toLowerCase().split(/[^a-z]+/).filter((t) => t.length > 2)
  try {
    const vids = await searchYouTube(`${clean} exercise how to proper form`)
    const best = vids
      .map((v) => ({ ...v, s: score(v, tokens) }))
      .filter((v) => v.s >= 6)
      .sort((a, b) => b.s - a.s)[0]
    if (best) {
      map[def.id] = best.id
      console.log(`✓ ${def.id} → ${best.id}  (${best.sec ?? '?'}s) ${best.title.slice(0, 60)}`)
    } else {
      miss++
      console.log(`· ${def.id}: no confident match, leaving without video`)
    }
  } catch (e) {
    miss++
    console.log(`! ${def.id}: ${e.message}`)
  }
  await new Promise((r) => setTimeout(r, 350))
}

const body = Object.entries(map)
  .map(([k, v]) => `  '${k}': '${v}',`)
  .join('\n')
writeFileSync(
  'src/plan/videoMap.ts',
  `// ============================================================
// GENERATED by tools/resolveVideos.mjs. Do not hand-edit.
// Short instructional videos resolved per exercise; a def's own
// hand-verified videoId always wins over this map.
// ============================================================

export const VIDEO_MAP: Record<string, string> = {
${body}
}
`,
)
console.log(`\nwrote src/plan/videoMap.ts: ${Object.keys(map).length} resolved, ${miss} without`)
