import type { ExerciseDef } from '../types'

// ============================================================
// Athletic Performance Library, exercises organized by the
// quality they train (acceleration, max velocity, jumping,
// elasticity, absorption, lateral power, COD, agility, balance,
// ballistic strength). Same guide format as the base catalog:
// steps you can follow mid-session, one main cue, honest
// mistakes. Structured metadata (level, direction, programming
// defaults, progression chains) lives in plan/athletic.ts.
// ============================================================

const E = (def: ExerciseDef) => def

export const ATHLETIC_EXERCISES: ExerciseDef[] = [
  // ================= ACCELERATION =================
  E({
    id: 'two-point-start',
    name: '2-Point Start (10 yd)',
    kind: 'sprint',
    equipment: 'Field / court',
    steps: [
      'Stagger stance, front foot loaded, hips down like a sprinter about to steal a base.',
      'Snap the back arm through and drive OUT at 45°, staying low and pushing the ground behind you for 10 hard yards, then coast tall.',
      'Project out, not up, standing straight up on step one kills the rep. Walk back and fully reset between reps.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Calves'], qualities: ['Acceleration', 'First step'] },
    why: 'The staggered start is the game position, every drive to the rim and every defensive burst starts from it. It adds intent and direction control on top of the falling start.',
    mistakes: ['Standing straight up on step one.', 'Short choppy arm action, the arms set the leg rhythm.'],
    cue: 'Project OUT at 45°, push the ground away behind you.',
    videoQuery: 'two point sprint start acceleration technique',
    restSec: 180,
  }),
  E({
    id: 'three-point-start',
    name: '3-Point Start (10 yd)',
    kind: 'sprint',
    equipment: 'Field / court',
    steps: [
      'Crouch with one hand down under your shoulder, hips higher than shoulders, strong front leg loaded. Breathe.',
      'Explode the down-hand arm back as you drive out, first three steps LOW, pistoning the ground back and rising gradually.',
      'Keep the eyes down early to stay projected forward. Full walk-back recovery, quality only.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Hamstrings'], qualities: ['Acceleration', 'Horizontal power'] },
    why: 'The lowest start position forces the most horizontal projection, it is the purest strength-to-speed expression of acceleration and exposes any weak first step immediately.',
    mistakes: ['Hips too low (jamming the first step).', 'Looking up early, eyes down keeps you projected forward.'],
    cue: 'Explode out of the crouch, low, low, then rise.',
    videoQuery: '3 point sprint start drill',
    restSec: 180,
  }),
  E({
    id: 'push-up-start',
    name: 'Push-Up Start (10 yd)',
    kind: 'sprint',
    equipment: 'Field / court',
    steps: [
      'Lie chest-down like the bottom of a push-up, hands under shoulders.',
      'On your own “go”, push up and get your feet under you in ONE fast scramble, then drive out low for 10 yards the instant they land.',
      'Scramble INTO the sprint, never up into a stand first. Walk back, shake out, reset fully.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Chest'], qualities: ['Acceleration', 'Reaction'] },
    why: 'Starting from the ground removes all pre-tension, so your body has to organize and produce force from zero, a raw, honest acceleration stimulus that also mimics scramble situations.',
    mistakes: ['Standing tall before sprinting, scramble INTO the sprint, not into a stand.'],
    cue: 'Ground to full sprint in one motion, no pause at the top.',
    videoQuery: 'push up sprint start drill',
    restSec: 180,
  }),
  E({
    id: 'wall-drive',
    name: 'Wall Drive (acceleration posture)',
    kind: 'sprint',
    equipment: 'Wall',
    steps: [
      'Hands on a wall, body in one straight 45° line from head to heel.',
      'Drive one knee up hard, foot cocked under the hip, hold a beat, then exchange legs with a sharp punch into the ground.',
      'The 45° line never sags and the foot strikes under the hip, not out front. Singles first, then 3-count exchanges, crisp beats sloppy.',
    ],
    targets: { muscles: ['Hip flexors', 'Glutes', 'Calves'], qualities: ['Acceleration mechanics', 'Posture'] },
    why: 'The wall lets you groove perfect acceleration shapes, stiff body line, knee punch, ground push, without any speed cost. It is where the first-step position gets learned and rehearsed.',
    mistakes: ['Hips sagging out of the straight line.', 'Casting the foot out in front instead of striking under the hip.'],
    cue: 'One straight line, punch the knee, strike under the hip.',
    videoQuery: 'wall drill acceleration march technique',
    restSec: 60,
  }),
  E({
    id: 'a-march',
    name: 'A-March',
    kind: 'sprint',
    equipment: 'Anywhere flat',
    steps: [
      'Walk tall with posture stacked: ribs down, eyes ahead.',
      'Drive one knee to hip height with the toe pulled up, opposite arm punching, then step DOWN, striking the ground under your hips.',
      'Never land out in front or let the ankle go floppy. March 15–20 yards per rep.',
    ],
    targets: { muscles: ['Hip flexors', 'Calves', 'Glutes'], qualities: ['Sprint mechanics', 'Coordination'] },
    why: 'The A-march is sprinting slowed to walking speed, knee punch, dorsiflexed foot, strike under the hips. Groove it here and the shapes show up at full speed for free.',
    mistakes: ['Leaning back as the knee rises.', 'Letting the ankle go floppy, keep the toe pulled up.'],
    cue: 'Knee up, toe up, step down under you.',
    videoQuery: 'a march sprint drill technique',
    restSec: 45,
  }),
  E({
    id: 'a-skip',
    name: 'A-Skip',
    kind: 'sprint',
    equipment: 'Anywhere flat',
    steps: [
      'Stand tall, ready to skip: knee punch, toe pulled up, arms driving, the same shapes as the A-march.',
      'Hop low on one foot as you punch the other knee up, then strike that foot straight down under your hips. 15–20 yards per rep.',
      'Quick, quiet, springy contacts with arms setting the rhythm. Skip for rhythm, never for height.',
    ],
    targets: { muscles: ['Hip flexors', 'Calves', 'Hamstrings'], qualities: ['Sprint mechanics', 'Rhythm', 'Ankle stiffness'] },
    why: 'The A-skip adds rhythm and elastic ground contact to the sprint shapes, it is the standard bridge between marching mechanics and actual sprinting, and a perfect warm-up primer.',
    mistakes: ['Skipping high instead of quick, height is not the goal, rhythm is.', 'Arms going side-to-side.'],
    cue: 'Quick off the ground, punch, strike, repeat.',
    videoQuery: 'a skip sprint drill technique',
    restSec: 45,
  }),
  E({
    id: 'resisted-start',
    name: 'Band-Resisted Start',
    kind: 'sprint',
    equipment: 'Band + partner (or hill)',
    steps: [
      'Band around your waist with a partner holding tension behind you (or use a steep hill).',
      'Drive out low against the resistance for 5–10 yards, big pushes, full steps, driving the ground BACK.',
      'The band should let you move at 80–90% of free speed, more drag turns it into a march. Full recovery every rep.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Acceleration', 'Horizontal force'] },
    why: 'Light resistance exaggerates the lean and forces longer, harder ground pushes, more horizontal force per step. That is the exact engine of a faster first step.',
    mistakes: ['Too much resistance, if the shape breaks, the drill is lost.', 'Popping upright against the band.'],
    cue: 'Big pushes, drive the ground BACK, stay in your lean.',
    videoQuery: 'band resisted sprint start acceleration',
    restSec: 180,
  }),
  E({
    id: 'sled-sprint',
    name: 'Sled Sprint (light)',
    kind: 'sprint',
    equipment: 'Sled + harness',
    steps: [
      'Load the sled light, you should lose no more than 10–20% of your free sprint speed.',
      'Drive out low, punching the ground back in full strides for 10–15 yards, then walk the sled back as your recovery.',
      'Every rep at full intent and the sprint shape never changes. Heavy grinding trains pushing, not sprinting.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Acceleration', 'Horizontal force'] },
    why: 'The gold-standard resisted acceleration tool: measurable, repeatable horizontal overload without changing your sprint shape, if the load stays honest.',
    mistakes: ['Loading heavy and grinding, that trains pushing, not sprinting.'],
    cue: 'Same sprint, more push, do not let the shape change.',
    videoQuery: 'light sled sprint acceleration training',
    restSec: 180,
  }),
  E({
    id: 'accel-20',
    name: 'Acceleration 10–20 yd',
    kind: 'sprint',
    equipment: 'Field / court',
    steps: [
      'Set up in your favorite start: falling, 2-point, or 3-point.',
      'Accelerate hard through 20 yards, rising gradually so you’re near full speed and tall by 15–20, then coast down easy.',
      'No popping up early, keep pushing and earn the tall posture. Walk back and fully recover between reps.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Quads'], qualities: ['Acceleration', 'Speed build-up'] },
    why: 'The 10–20 yard zone is where acceleration becomes real speed. Extending the drive phase teaches you to keep pushing instead of standing up at step three like most athletes do.',
    mistakes: ['Reaching top speed at 10 yards because you stood up early.'],
    cue: 'Keep pushing, earn your tall posture, don’t jump to it.',
    videoQuery: '20 yard acceleration sprint technique',
    restSec: 210,
  }),

  // ================= MAX VELOCITY =================
  E({
    id: 'flying-20',
    name: 'Flying 20',
    kind: 'sprint',
    equipment: 'Field / track',
    steps: [
      'Give yourself 20–30 yards of build-up runway before the start line.',
      'Hit the line at speed and hold TRUE max velocity for 20 yards, tall, relaxed, bouncing, then coast down over plenty of runway.',
      'Max velocity is relaxed violence, never strain or grit. Rest 2–4 minutes between reps, this is expensive work.',
    ],
    targets: { muscles: ['Hamstrings', 'Glutes', 'Calves'], qualities: ['Max velocity', 'Elastic stride'] },
    why: 'A longer fly zone than the flying 10, more time at absolute top speed, which is the single most potent (and most fragile) stimulus in sprinting. Tiny dose, huge signal.',
    mistakes: ['Straining and gritting at top speed, max velocity is RELAXED violence.', 'Too little build-up runway.'],
    cue: 'Tall, relaxed, bouncing, let the speed happen.',
    videoQuery: 'flying 20 sprint max velocity training',
    restSec: 240,
  }),
  E({
    id: 'build-up-sprint',
    name: 'Build-Up Sprint (60–80%→95%)',
    kind: 'sprint',
    equipment: 'Field / track',
    steps: [
      'Mark out 40–60 yards of smooth running room.',
      'Accelerate through gears, 60% then 80% then 95%, hold the top gear a few strides, then coast down long.',
      'Each gear should feel like adding bounce, not strain. Never skip gears and redline at 30 yards.',
    ],
    targets: { muscles: ['Hamstrings', 'Glutes', 'Calves'], qualities: ['Max velocity', 'Sprint rhythm'] },
    why: 'Gear changes teach relaxed speed, the skill of going faster by staying loose. Also the safest way to touch high velocities early in a session or a return week.',
    mistakes: ['Skipping gears and redlining at 30 yards.'],
    cue: 'Shift gears with bounce, not strain.',
    videoQuery: 'build up sprint drill technique',
    restSec: 180,
  }),
  E({
    id: 'wicket-run',
    name: 'Wicket Run (mini-hurdle rhythm)',
    kind: 'sprint',
    equipment: 'Low hurdles / cones',
    steps: [
      'Set 8–12 low wickets (mini hurdles) about 5.5–6.5 ft apart, spaced so you can run tall through them.',
      'Build in, then run OVER the wickets with quick, quiet contacts under your hips, knees riding high in front.',
      'Let the spacing do the coaching. If you’re reaching for wickets, shorten the gap, reaching is the exact fault this drill kills.',
    ],
    targets: { muscles: ['Hip flexors', 'Hamstrings', 'Calves'], qualities: ['Sprint mechanics', 'Max velocity', 'Rhythm'] },
    why: 'Wickets are the closest thing to a cheat code for upright sprint mechanics, the spacing physically prevents overstriding and backside mechanics without a single verbal cue.',
    mistakes: ['Spacing too long, reaching for wickets recreates the exact fault the drill kills.'],
    cue: 'Run tall OVER them, knees up, strike under you.',
    videoQuery: 'wicket runs sprint mechanics drill',
    restSec: 180,
  }),
  E({
    id: 'dribble-run',
    name: 'Ankle Dribble Run',
    kind: 'sprint',
    equipment: 'Anywhere flat',
    steps: [
      'Start an easy jog, feet cocked up, ready for tiny fast steps.',
      '“Dribble” your feet just past your ankles, each step striking down under your hips with a stiff ankle. 15–20 yards per pass.',
      'Progress ankle-height to calf-height to knee-height, and never let the heel flick back behind you.',
    ],
    targets: { muscles: ['Calves', 'Hip flexors'], qualities: ['Sprint rhythm', 'Ankle stiffness'] },
    why: 'Dribbles rehearse the down-and-under strike pattern at rising amplitudes, the standard rhythm bridge from drills into real max-velocity running.',
    mistakes: ['Letting the heel flick back behind you, keep the cycle in front.'],
    cue: 'Fast little strikes, down and under, stiff ankle.',
    videoQuery: 'ankle dribble sprint drill',
    restSec: 60,
  }),

  // ================= VERTICAL JUMPING =================
  E({
    id: 'standing-vertical-jump',
    name: 'Standing Vertical Jump',
    kind: 'jump',
    equipment: 'Anywhere (target helps)',
    steps: [
      'Stand tall under your target, feet hip-width.',
      'Dip fast, arms ripping down and back, then explode straight up in one line and reach at the top. Land soft, knees over toes.',
      'The dip is a snap, not a slow squat. Full reset between jumps, every one a max effort.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Two-foot vertical', 'Concentric power'] },
    why: 'The purest test and builder of dead-start leg power, no run-up to hide behind. Your standing spring is the floor your approach jump is built on.',
    mistakes: ['Slow lazy dip, the dip is a snap, not a squat.', 'Reaching with both hands and killing the reach height.'],
    cue: 'Rip the arms down, then throw everything up at once.',
    videoQuery: 'standing vertical jump technique',
    restSec: 90,
  }),
  E({
    id: 'countermovement-jump',
    name: 'Countermovement Jump (max)',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Stand tall, feet about hip-width, arms ready to swing.',
      'Dip FAST to your natural depth, arms swinging back, reverse instantly with no pause, and fly. Land soft in an athletic stance.',
      'The bounce IS the exercise, never pause in the hole. Walk a circle between reps and stop when height drops.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Two-foot vertical', 'Explosive power', 'Rate of force'] },
    why: 'The countermovement jump is the standard of two-foot power, the fast dip stores elastic energy and the instant reversal teaches your body to use it. This is the jump that carries over to the game.',
    mistakes: ['Pausing at the bottom of the dip, the bounce IS the exercise.', 'Chasing reps when height drops. Height gone = done.'],
    cue: 'Dip fast, reverse faster, no pause in the hole.',
    videoQuery: 'countermovement jump technique max height',
    restSec: 120,
  }),
  E({
    id: 'squat-jump',
    name: 'Squat Jump (paused)',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Sit into a half squat and PAUSE two full seconds, killing all bounce.',
      'From the dead stop, explode straight up as hard as possible, then land soft and walk it off.',
      'No sneaky dip before takeoff, that turns it back into a countermovement jump. Reset the pause every rep.',
    ],
    targets: { muscles: ['Glutes', 'Quads'], qualities: ['Concentric power', 'Starting strength'] },
    why: 'Pausing deletes the stretch reflex, forcing pure concentric force from a dead stop, the quality that decides who gets off the floor first when there is no run-up and no rhythm.',
    mistakes: ['Sneaking a small dip before takeoff, that turns it back into a countermovement jump.'],
    cue: 'Dead stop… then explode. No sneaky dip.',
    videoQuery: 'paused squat jump exercise',
    restSec: 120,
  }),
  E({
    id: 'one-foot-jump',
    name: 'One-Foot Max Jump (short approach)',
    kind: 'jump',
    equipment: 'Court / open space',
    steps: [
      'Take two or three quick approach steps toward your jump spot.',
      'Plant one foot and jump at full intent, opposite knee and hand driving up hard. Land soft on two feet.',
      'Speed INTO the plant is the jump, never slow down into it. No caving plant knee, alternate takeoff legs across sets.',
    ],
    targets: { muscles: ['Glutes', 'Calves', 'Hip flexors'], qualities: ['One-foot vertical', 'Elastic takeoff'] },
    why: 'One-foot jumping is a spring skill, stiffness and speed matter more than raw squat strength. It needs its own practice; two-foot power does not automatically transfer.',
    mistakes: ['Slowing down into the plant, speed INTO the plant is the jump.', 'Letting the plant knee cave.'],
    cue: 'Fast into the plant, knee punches the sky.',
    videoQuery: 'single leg jump technique basketball',
    restSec: 120,
  }),
  E({
    id: 'penultimate-drill',
    name: 'Penultimate Step Drill (walk-in)',
    kind: 'jump',
    equipment: 'Court / open space',
    steps: [
      'Walk in slow, rehearsing the last two steps of a jump approach.',
      'Long, LOW second-to-last step to drop the hips, short quick last step, plant heel-to-toe, then jump up out of it, arms sweeping.',
      'The hips lower BEFORE the plant, never by bending the knee at it. Groove it slow before you ever try it fast.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Approach mechanics', 'Penultimate step'] },
    why: 'The penultimate step is where great jumpers create height, the long low step lowers the hips WITHOUT bending the takeoff knee, so the last step converts speed into lift instead of absorbing it.',
    mistakes: ['Chopping the second-to-last step short.', 'Sinking into a deep knee bend at the plant, the lowering happens BEFORE the plant.'],
    cue: 'Long-low… short-quick, hips down early, then UP.',
    videoQuery: 'penultimate step jump technique',
    restSec: 90,
  }),
  E({
    id: 'penultimate-approach-jump',
    name: 'Penultimate Approach Jump (full speed)',
    kind: 'jump',
    equipment: 'Court / open space',
    steps: [
      'Take a full 4–6 step approach at real speed.',
      'Second-to-last step LONG and LOW while still moving fast, then a short quick last step, plant, and explode up at full intent.',
      'Only approach as fast as you can convert, wasted speed is wasted height. Full recovery, stop when height visibly drops.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Approach jump', 'Penultimate step', 'Two-foot vertical'] },
    why: 'This is the money jump, the drilled penultimate mechanics at game speed. It converts your sprint into vertical better than any amount of extra squatting once the pattern is clean.',
    mistakes: ['Approach too fast for your plant strength, speed you cannot convert is wasted.', 'Eyes down at the plant.'],
    cue: 'Long-low, short-quick, THROW it all up.',
    videoQuery: 'approach jump penultimate step full speed',
    restSec: 150,
  }),
  E({
    id: 'low-box-approach-jump',
    name: 'Low-Box Approach Jump',
    kind: 'jump',
    equipment: 'Low box (12–18")',
    steps: [
      'Set a low box (12–18") and take a short 3–4 step approach.',
      'Use your penultimate rhythm (long-low, then short-quick), jump as high as the approach allows, and land ON the box softly.',
      'The box only shortens the landing, never jump “to” it or tuck your knees to fake height. Step down and fully reset.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Approach jump', 'Low-cost landing'] },
    why: 'Approach jumping with most of the landing cost removed, more quality max-intent takeoffs per week without beating up your knees and ankles. A volume-friendly way to rehearse the approach.',
    mistakes: ['Tucking knees to “make” a tall box, keep the box low and the jump honest.'],
    cue: 'Max jump, easy landing, the box just catches you.',
    videoQuery: 'box approach jump drill',
    restSec: 120,
  }),

  // ================= HORIZONTAL POWER =================
  E({
    id: 'broad-jump',
    name: 'Standing Broad Jump',
    kind: 'jump',
    equipment: 'Open floor / turf',
    steps: [
      'Feet hip-width behind a line, arms ready.',
      'Rip the arms back as the hips dip, then explode OUT at roughly 45°, hips fully extending, and land in an athletic stance.',
      'Jump OUT, not up, and absorb the landing into your hips, never stiff-legged. Walk back and reset completely.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Quads'], qualities: ['Horizontal power', 'Hip extension'] },
    why: 'The broad jump is horizontal force in one number, the same hip-extension violence that drives your first step, in a package you can measure and progress week to week.',
    mistakes: ['Jumping UP instead of OUT.', 'Landing stiff-legged, absorb into the hips.'],
    cue: 'Throw yourself OUT at 45°, hips through.',
    videoQuery: 'standing broad jump technique',
    restSec: 120,
  }),
  E({
    id: 'broad-jump-stick',
    name: 'Broad Jump to Stick',
    kind: 'jump',
    equipment: 'Open floor / turf',
    steps: [
      'Feet hip-width behind a line, arms ready for a full rip.',
      'Max broad jump out at 45°, then land and FREEZE: athletic stance, chest up, knees over toes, dead quiet feet.',
      'Hold the stick two full seconds, a stumble means the rep didn’t count. Never let the knees cave on the catch.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Hamstrings'], qualities: ['Horizontal power', 'Force absorption'] },
    why: 'Producing force means nothing if you cannot catch it. Sticking a max broad jump trains the brakes and the engine in one rep, the foundation for cutting, landing, and jumping again.',
    mistakes: ['Letting the knees cave on the catch.', 'A “stick” that dribbles into three little steps.'],
    cue: 'Explode out, land frozen. Two-second statue.',
    videoQuery: 'broad jump stick landing drill',
    restSec: 120,
  }),
  E({
    id: 'repeated-broad-jump',
    name: 'Repeated Broad Jumps (x3)',
    kind: 'jump',
    equipment: 'Open floor / turf',
    steps: [
      'Set up for a broad jump with room for three in a row.',
      'Jump out, land, and immediately reload into the next, three connected jumps with minimal ground time. Stick the final landing.',
      'Quick ground contact never beats a caved knee or a dead landing, keep every jump honest. Walk back, full reset.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Calves'], qualities: ['Horizontal power', 'Elastic reload'] },
    why: 'Linking jumps teaches the reload, catching force and firing it straight back out, which is how horizontal power actually shows up in a game: never one perfect rep from a standstill.',
    mistakes: ['Pausing between jumps (that is three singles, not one triple).', 'Each jump shrinking, keep them honest.'],
    cue: 'Land loaded, the landing IS the next takeoff.',
    videoQuery: 'triple broad jump drill',
    restSec: 150,
  }),
  E({
    id: 'single-leg-broad-jump',
    name: 'Single-Leg Broad Jump',
    kind: 'jump',
    equipment: 'Open floor / turf',
    steps: [
      'Stand on one leg behind a line, arms ready.',
      'Dip, rip the arms back, and jump OUT off the single leg, landing on BOTH feet with a stick.',
      'A clean stick matters more than distance, and the plant knee never dives inward. Alternate legs each rep.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Calves'], qualities: ['Unilateral power', 'Horizontal power'] },
    why: 'Every real push-off in sport is one leg. The single-leg broad jump finds and fixes the strength gap between your legs before it becomes a speed leak or an injury.',
    mistakes: ['Letting the plant knee dive inward on takeoff.', 'Landing on one leg before you have earned it, two-foot landings first.'],
    cue: 'One-leg drive, two-foot stick.',
    videoQuery: 'single leg broad jump drill',
    restSec: 120,
  }),
  E({
    id: 'power-bound',
    name: 'Alternate Bounds',
    kind: 'jump',
    equipment: 'Turf / track',
    steps: [
      'Jog in a few easy steps to get moving.',
      'Leap off one leg, drive the other knee up-and-out, fly, land on the other leg and keep going. 4–8 contacts over 15–25 yards.',
      'Jump OFF the ground, don’t reach for it with the foot out front. Big air, proud chest, walk back fully between reps.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Calves'], qualities: ['Horizontal power', 'Unilateral elasticity', 'Bounding'] },
    why: 'Bounding is single-leg power at running speed, the bridge between the weight room and sprinting. Nothing else loads the hips and hamstrings so specifically for stride power.',
    mistakes: ['Reaching for distance with the foot out front, jump OFF the ground, don’t reach for it.', 'Doing them tired and flat.'],
    cue: 'Explode off, fly, drive the knee THROUGH.',
    videoQuery: 'alternate leg bounding drill',
    restSec: 180,
  }),
  E({
    id: 'single-leg-bound',
    name: 'Single-Leg Bounds (RR/LL)',
    kind: 'jump',
    equipment: 'Turf / track',
    steps: [
      'Jog in easy, then set up to bound on the SAME leg 3–4 times in a row.',
      'Cycle the leg fast, strike under you, and ride the spring forward. Switch legs each rep.',
      'These are advanced, earn them with months of pogos and alternate bounds first. Grass or turf, no grinding long contacts.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Calves'], qualities: ['Unilateral elasticity', 'Reactive strength'] },
    why: 'Same-leg bounds are one of the highest-value (and highest-demand) elastic drills in existence, a direct line to one-foot jumping and top-speed stiffness. Earn them with alternate bounds first.',
    mistakes: ['Attempting these without months of pogo/bound base, they are advanced.', 'Grinding long contacts.'],
    cue: 'Spring, same leg, quick off the ground.',
    videoQuery: 'single leg bound plyometric',
    restSec: 180,
  }),

  // ================= ELASTIC / REACTIVE =================
  E({
    id: 'ankle-hop',
    name: 'Ankle Hops (in place)',
    kind: 'jump',
    equipment: 'Firm floor',
    steps: [
      'Feet together, knees nearly straight, hands relaxed.',
      'Hop in place off the ankles only, small, quick, and quiet, like the floor is hot.',
      'Knees stay quiet, bending them turns it into mini squats. Sets of 10–20 seconds, perfectly rhythmic.',
    ],
    targets: { muscles: ['Calves'], qualities: ['Ankle stiffness', 'Elastic base'] },
    why: 'The gentlest doorway into elastic training, pure ankle spring with tiny impact. The rhythm and stiffness you build here is what every bigger bounce is made of.',
    mistakes: ['Bending the knees and turning it into mini squats.'],
    cue: 'Knees quiet, bounce off the ankles.',
    videoQuery: 'ankle hops pogo drill',
    restSec: 60,
  }),
  E({
    id: 'alternating-pogo',
    name: 'Alternating Pogos',
    kind: 'jump',
    equipment: 'Firm floor',
    steps: [
      'Stand tall as if about to sprint on the spot, ankles stiff.',
      'Pogo in place, exchanging feet each contact, quick and quiet, striking under your hips. 10–20 contacts per set.',
      'Hips stay level and the ankles do the work, never let the contacts drift out in front of you.',
    ],
    targets: { muscles: ['Calves', 'Hip flexors'], qualities: ['Ankle stiffness', 'Sprint-specific elasticity'] },
    why: 'Splitting the pogo one foot at a time moves ankle spring toward sprinting, alternating stiff contacts under the hips is literally the bottom half of max-velocity running.',
    mistakes: ['Contacts drifting out in front of you.'],
    cue: 'Sprint on the spot, stiff, quick, under you.',
    videoQuery: 'alternating pogo hops drill',
    restSec: 60,
  }),
  E({
    id: 'single-leg-pogo',
    name: 'Single-Leg Pogos',
    kind: 'jump',
    equipment: 'Firm floor',
    steps: [
      'Stand on one leg, knee nearly straight, a wall nearby for balance at first.',
      'Pogo small, stiff, rhythmic hops off that ankle, 8–15 contacts, then switch legs.',
      'Stop the set the moment the rhythm breaks or the contacts get loud, mushy ankles teach nothing.',
    ],
    targets: { muscles: ['Calves'], qualities: ['Unilateral ankle stiffness', 'Single-leg elasticity'] },
    why: 'One-leg spring is where games are played, cutting, single-leg takeoffs, top-speed strides. This tiny drill is the safest possible dose of that quality.',
    mistakes: ['Collapsing at the ankle and getting long, mushy contacts.'],
    cue: 'Stiff ankle, bounce, don’t sink.',
    videoQuery: 'single leg pogo hops',
    restSec: 90,
  }),
  E({
    id: 'line-hop',
    name: 'Line Hops (front-back / side-side)',
    kind: 'jump',
    equipment: 'Any line on the floor',
    steps: [
      'Stand with feet together over any line on the floor, on the balls of your feet.',
      'Hop front-back over the line as fast as possible for 5–10 seconds, then side-side on the next set.',
      'Stay LOW and fast, height murders frequency. Count contacts if you want a score to beat.',
    ],
    targets: { muscles: ['Calves'], qualities: ['Foot quickness', 'Ankle stiffness', 'Coordination'] },
    why: 'Fast feet are trained, not born. Line hops build contact speed and precise foot placement with almost zero cost, a perfect primer before speed or agility work.',
    mistakes: ['Hopping high, height murders frequency.'],
    cue: 'Low and FAST, tap-tap-tap over the line.',
    videoQuery: 'line hops quick feet drill',
    restSec: 45,
  }),
  E({
    id: 'rudiment-hop',
    name: 'Rudiment Hops (skip variations)',
    kind: 'jump',
    equipment: 'Open floor',
    steps: [
      'Pick a 10–20 yard lane of open floor and stand tall.',
      'Travel forward with low, stiff-ankle hop patterns: double-foot hops, hop-hop-stick, lateral zig-zags.',
      'Each contact quick and quiet with tall posture. These are rhythm work, never max jumps.',
    ],
    targets: { muscles: ['Calves', 'Glutes'], qualities: ['Elastic coordination', 'Ankle stiffness', 'Rhythm'] },
    why: 'Rudiments are the alphabet of bouncing, low-amplitude patterns that teach your feet and brain dozens of ways to store and return energy before you ever attempt big plyometrics.',
    mistakes: ['Turning them into max jumps, these are rhythm, not height.'],
    cue: 'Quiet springs, rhythm first, height never.',
    videoQuery: 'rudiment hops plyometric prep',
    restSec: 60,
  }),
  E({
    id: 'snap-down-rebound',
    name: 'Snap-Down to Rebound Jump',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Stand tall, arms up, ready to snap down.',
      'Snap down fast into an athletic stance and, the INSTANT you catch it, rebound straight up into a max jump. Land soft.',
      'The switch must be immediate, a slow sink between catch and jump kills the drill. Reset fully between reps.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Reactive strength', 'Fast switching'] },
    why: 'This teaches the switch, catching downward force and reversing it instantly. It is the countermovement jump with the reversal demand turned up, and a stepping stone toward depth jumps.',
    mistakes: ['A slow sink between the catch and the jump, the switch must be immediate.'],
    cue: 'Catch… FIRE. No pause between down and up.',
    videoQuery: 'snap down to vertical jump drill',
    restSec: 120,
  }),
  E({
    id: 'low-hurdle-hop',
    name: 'Low Hurdle Hops',
    kind: 'jump',
    equipment: 'Low hurdles (6–12")',
    steps: [
      'Set 4–6 low hurdles (6–12") about a stride apart.',
      'Two-foot hop over each with quick ground contact between, arms setting the rhythm, and stick the last one.',
      'Quiet landings, tall posture. If the hurdles force a knee tuck, they’re too tall and the springiness is gone.',
    ],
    targets: { muscles: ['Calves', 'Quads', 'Glutes'], qualities: ['Bilateral elasticity', 'Repeated jumps'] },
    why: 'Hurdle spacing forces honest, repeated elastic jumps with a rhythm you cannot fake, the classic bridge from pogos toward true reactive jumping.',
    mistakes: ['Hurdles too tall too soon, knees tuck and the elasticity disappears.', 'Long smushy ground contacts.'],
    cue: 'Touch and go, the ground is a trampoline.',
    videoQuery: 'low hurdle hops plyometric drill',
    restSec: 120,
  }),
  E({
    id: 'depth-drop',
    name: 'Depth Drop (step-off landing)',
    kind: 'jump',
    equipment: 'Box (12–24")',
    steps: [
      'Stand on a 12–24" box, ready to step OFF, never jump off.',
      'Step off with one foot leading and land on both feet in a perfect athletic stance, quiet, knees over toes, chest up.',
      'Hold the landing two seconds. Raise the box only when landings stay silent, noise is wasted force.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Calves'], qualities: ['Force absorption', 'Landing mechanics'] },
    why: 'A controlled dose of falling teaches your legs and nervous system to absorb real impact, the prerequisite skill before any true depth jumping, and the best insurance for your knees.',
    mistakes: ['Jumping up-and-off the box, adding height you did not order.', 'Loud landings, noise is wasted force.'],
    cue: 'Step off, land like a ninja, frozen and silent.',
    videoQuery: 'depth drop landing technique box',
    restSec: 90,
  }),
  E({
    id: 'depth-jump',
    name: 'Depth Jump',
    kind: 'jump',
    equipment: 'Box (12–24")',
    steps: [
      'Stand on a modest box, ready to step off, not jump off.',
      'Step off, and the INSTANT you touch down, explode straight up into a max jump.',
      'Ground time short without shrinking the jump. Tiny volumes, full resets, and earn these with months of landing work first.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Reactive strength', 'Shock method'] },
    why: 'The classic shock-method drill: overload the stretch reflex with a drop, then demand an instant max reversal. Brutally effective and brutally expensive, an advanced tool for athletes with a landing base.',
    mistakes: ['Box too tall (long ground time = the stimulus is gone).', 'Doing these without months of drops, snap-downs, and hurdle hops first.'],
    cue: 'Touch the ground like it’s hot, down becomes UP.',
    videoQuery: 'depth jump plyometric technique',
    restSec: 180,
  }),
  E({
    id: 'repeated-cmj',
    name: 'Repeated Jumps (CMJ x4-6)',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Stand tall with room to jump straight up.',
      'Countermovement jump (fast dip, no pause), then on landing reload immediately into the next. 4–6 jumps per set.',
      'Every rep a real effort, quick between. Stop the set the moment height visibly drops, hops don’t count.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Repeated jump power', 'Elastic endurance'] },
    why: 'Games rarely give you one jump from rest, they demand the second and third jump fast. Linked jumps train the reload while heights stay honest and countable.',
    mistakes: ['Letting jumps 4–6 turn into hops. Every rep must be a jump you would sign.'],
    cue: 'Land loaded, go again, every one a real jump.',
    videoQuery: 'repeated countermovement jumps drill',
    restSec: 150,
  }),

  // ================= FORCE ABSORPTION / LANDING =================
  E({
    id: 'snap-down',
    name: 'Snap-Down',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Stand tall on your toes, arms overhead.',
      'SNAP down into an athletic quarter-squat, arms ripping down and back, hips dropping, feet slapping flat. Freeze the catch.',
      'Speed of the drop is the point. Catch with chest up and knees over toes, never inside your big toes.',
    ],
    targets: { muscles: ['Quads', 'Glutes'], qualities: ['Force absorption', 'Landing position'] },
    why: 'The snap-down teaches the athletic catch position at zero cost, how to get stiff and stacked FAST. It is the first rung of every landing and reactive progression in this library.',
    mistakes: ['A slow, casual sink instead of a violent snap.', 'Catching with knees inside your big toes.'],
    cue: 'Rip down FAST, freeze like a statue.',
    videoQuery: 'snap down drill landing mechanics',
    restSec: 60,
  }),
  E({
    id: 'snap-down-stick',
    name: 'Snap-Down to Stick',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Stand tall with arms ready, this one starts with a small hop.',
      'Hop up, snap down into the landing, arms ripping back and hips dropping, then stick the catch dead-still for two seconds.',
      'Quiet feet, stacked knees, proud chest. If the landing talks (noise, wobble, extra steps), the rep failed.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Calves'], qualities: ['Force absorption', 'Landing mechanics'] },
    why: 'Adding a small flight phase makes the catch real, actual falling force, still tiny cost. Own this before boxes, bounds, and depth work; it is the landing pattern every later drill reuses.',
    mistakes: ['Stiff-legged catches that jar the knees.', 'Rushing the freeze.'],
    cue: 'Hop, snap, STICK, two seconds of silence.',
    videoQuery: 'snap down to stick landing drill',
    restSec: 75,
  }),
  E({
    id: 'drop-landing',
    name: 'Box Drop to Stick',
    kind: 'jump',
    equipment: 'Box (12–20")',
    steps: [
      'Stand on a 12–20" box, ready to step off.',
      'Step off and stick a two-foot landing in your snap-down shape, absorbing through hips and ankles.',
      'Nearly silent, held two seconds. Raise the height only while the silence holds, a loud landing means not yet.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Calves'], qualities: ['Force absorption', 'Deceleration strength'] },
    why: 'Graduated falling. Each silent landing at a new height is your body literally learning to brake harder, protection and performance in the same rep.',
    mistakes: ['Height ego. A loud landing at 24" is worth less than a silent one at 12".'],
    cue: 'Land in your snap-down, silent, stacked, still.',
    videoQuery: 'box drop landing stick drill',
    restSec: 90,
  }),
  E({
    id: 'single-leg-landing',
    name: 'Single-Leg Landing (hop to stick)',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Stand ready for a small two-foot hop forward.',
      'Hop, land on ONE leg and stick it, knee over the middle toes, hips back, arms out for balance. Hold two seconds.',
      'Never let the knee dive inward, that is the one unbreakable rule. Alternate legs, then progress to lateral and rotational hops.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Unilateral absorption', 'Knee control', 'Balance'] },
    why: 'Almost every non-contact knee injury is a failed single-leg landing. Training the catch on one leg builds the stability that lets you cut, bound, and land off one foot without fear.',
    mistakes: ['Knee diving inward, the single most important thing to never allow.', 'Balancing with a toe-touch from the free leg.'],
    cue: 'One-leg statue, knee over toes, dead still.',
    videoQuery: 'single leg landing stick drill',
    restSec: 75,
  }),
  E({
    id: 'decel-stick',
    name: 'Sprint to Stick (deceleration)',
    kind: 'sprint',
    equipment: 'Field / court',
    steps: [
      'Mark a 10–15 yard runway on field or court.',
      'Accelerate hard, then brake in 3–4 choppy steps, hips DOWN and BACK, feet drumming, and finish frozen in an athletic stance.',
      'Many small braking steps, never two giant ones, that is how knees get hurt. Shorten the stopping distance as you improve.',
    ],
    targets: { muscles: ['Quads', 'Glutes'], qualities: ['Deceleration', 'Braking', 'Eccentric strength'] },
    why: 'Stopping is a skill, and the fastest players are the best stoppers, every cut is a brake before it is a burst. This drill builds the eccentric brakes at sprint speed with a measurable finish.',
    mistakes: ['Two giant braking steps instead of several small ones, that is how knees get hurt.', 'Standing tall while braking.'],
    cue: 'Chop the brakes, hips down, land frozen.',
    videoQuery: 'sprint deceleration stick drill',
    restSec: 150,
  }),

  // ================= LATERAL POWER =================
  E({
    id: 'lateral-bound',
    name: 'Lateral Bound',
    kind: 'jump',
    equipment: 'Open floor / turf',
    steps: [
      'Stand on one leg with clear space to each side.',
      'Dip and drive OUT sideways off that leg, fly, and land on the opposite leg, riding the landing softly. Rebound back or reset.',
      'Commit to real distance and never land on a straight stiff leg, ride into the hip.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Calves'], qualities: ['Lateral power', 'Unilateral elasticity'] },
    why: 'Sideways is a separate skill. Lateral bounds build the hip abductor/adductor power that creates separation on a cut, the quality vertical training never touches.',
    mistakes: ['Landing on a straight stiff leg.', 'Tiny cautious hops, commit to real distance.'],
    cue: 'Push the ground AWAY sideways, fly, then ride the landing.',
    videoQuery: 'lateral bound plyometric technique',
    restSec: 120,
  }),
  E({
    id: 'lateral-bound-stick',
    name: 'Lateral Bound to Stick',
    kind: 'jump',
    equipment: 'Open floor / turf',
    steps: [
      'Stand on one leg, ready to bound sideways.',
      'Max lateral bound, land on the opposite leg and STICK it: two-second freeze, knee over toes, hips back, torso quiet.',
      'A stumble or caving knee is a failed rep, shorten the bound until it’s clean. Alternate directions.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Quads'], qualities: ['Lateral power', 'Unilateral absorption', 'Cut foundation'] },
    why: 'This IS the cut, slowed down: produce sideways force, then catch it on one leg. Own the stick and every change of direction gets faster and safer at once.',
    mistakes: ['Letting the landing knee collapse inward.', 'Rushing out of the stick.'],
    cue: 'Bound, one-leg statue. Own the landing.',
    videoQuery: 'lateral bound stick landing drill',
    restSec: 120,
  }),
  E({
    id: 'skater-bound',
    name: 'Continuous Skater Bounds',
    kind: 'jump',
    equipment: 'Open floor',
    steps: [
      'Athletic stance, ready to bound side to side like a speed skater.',
      'Bound laterally, landing on the outside leg and springing straight back the other way, arms swinging across the body.',
      'Quick springy exchanges: land, load, gone, no sinking into deep slow landings. 6–12 contacts, rhythm over max distance.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Calves'], qualities: ['Lateral elasticity', 'Repeated lateral power'] },
    why: 'Linked lateral bounds train the elastic exchange, catching one direction and instantly firing the other, exactly what shuffling defenders and cutting attackers do all game.',
    mistakes: ['Sinking into deep slow landings between bounds.'],
    cue: 'Skate, spring off each catch, no sinking.',
    videoQuery: 'skater bounds lateral plyometric',
    restSec: 120,
  }),
  E({
    id: 'lateral-line-hop',
    name: 'Lateral Line Hops (single-leg)',
    kind: 'jump',
    equipment: 'Any line on the floor',
    steps: [
      'Stand on one leg beside any line on the floor.',
      'Hop side-to-side over the line as fast as possible, 5–10 seconds of tiny stiff contacts, then switch legs.',
      'Quiet, quick, controlled, the ankle does the work. Keep the hops small, never high.',
    ],
    targets: { muscles: ['Calves', 'Glutes'], qualities: ['Lateral ankle stiffness', 'Foot quickness'] },
    why: 'Single-leg lateral spring at the ankle protects and powers every cut. This is the smallest, safest dose of sideways elasticity you can buy.',
    mistakes: ['Big high hops, keep it small and fast.'],
    cue: 'Tick-tock over the line, stiff and small.',
    videoQuery: 'single leg lateral line hops',
    restSec: 60,
  }),
  E({
    id: 'crossover-bound',
    name: 'Crossover Bound',
    kind: 'jump',
    equipment: 'Open floor / turf',
    steps: [
      'Start in a side-on lateral stance with room to travel.',
      'Cross the trail leg OVER and bound that way, landing on the outside leg and riding into the next crossover. 4–6 contacts each way.',
      'The hips lead and stay square-ish while the shoulders stay calm, don’t spin the whole body.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Hip flexors'], qualities: ['Lateral power', 'Hip crossover mechanics'] },
    why: 'The crossover step is how athletes actually re-accelerate sideways, hips rotating over a planted leg. Bounding it builds the specific hip action defenders and base-stealers live on.',
    mistakes: ['Turning the whole body instead of letting the hips cross over.'],
    cue: 'Cross and GO, hips lead, shoulders stay calm.',
    videoQuery: 'crossover bound lateral drill',
    restSec: 120,
  }),
  E({
    id: 'lateral-shuffle',
    name: 'Lateral Shuffle (low + fast)',
    kind: 'sprint',
    equipment: 'Court / cones',
    steps: [
      'Athletic stance, hips low, over a 5–10 yard lane.',
      'Shuffle across pushing off the trail leg, touch the line or cone, and shuffle back. Fast feet, proud chest, eyes up.',
      'Stay LOW and level the whole time, no bobbing, and never cross the feet or click the heels together.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Quads'], qualities: ['Lateral quickness', 'Defensive movement'] },
    why: 'The base position of defense. Fast, level shuffling with a real push off the trail leg is a trainable skill that shows up in every closeout and every mirror situation.',
    mistakes: ['Standing up as you tire.', 'Feet clicking together, you can’t push from a closed base.'],
    cue: 'Stay LOW, push the ground away, never cross, never click.',
    videoQuery: 'defensive lateral shuffle drill',
    restSec: 90,
  }),

  // ================= CHANGE OF DIRECTION =================
  E({
    id: 'shuttle-5-10-5',
    name: '5-10-5 Pro Agility Shuttle',
    kind: 'sprint',
    equipment: '3 cones / lines',
    steps: [
      'Straddle the middle of three lines or cones set 5 yards apart.',
      'Sprint 5 yards right and touch the line, sprint 10 left and touch, then sprint back 5 through the middle.',
      'Brake with choppy steps and low hips at each line, exploding out of every plant. Full recovery, this is speed work, not conditioning.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Adductors'], qualities: ['Change of direction', 'Braking', 'Re-acceleration'] },
    why: 'The classic COD test packs a brake, a plant, and a re-launch into every 5 yards, a scoreboard for your ability to stop and go that transfers straight to game movement.',
    mistakes: ['Rounding the turns instead of planting hard.', 'Running it gassed, quality dies and so does the point.'],
    cue: 'Chop, plant LOW, explode out the other side.',
    videoQuery: '5-10-5 pro agility shuttle technique',
    restSec: 180,
  }),
  E({
    id: 'l-drill',
    name: 'L-Drill (3-cone)',
    kind: 'sprint',
    equipment: '3 cones',
    steps: [
      'Set three cones in an L shape, 5 yards apart.',
      'Sprint to cone 2 and back, then around 2, weave around 3, and return, braking low into every turn and accelerating out.',
      'Lean into the arcs instead of standing tall and drifting wide. Alternate starting sides.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Calves'], qualities: ['Change of direction', 'Curved acceleration', 'Body control'] },
    why: 'The L-drill mixes sharp 180s with tight arcs, braking, bending, and re-accelerating in one continuous pattern. It exposes stiffness that straight-line drills never find.',
    mistakes: ['Standing tall through the arcs and drifting wide.'],
    cue: 'Low into every turn, bend the run, don’t break it.',
    videoQuery: 'L drill 3 cone technique',
    restSec: 180,
  }),
  E({
    id: 'shuffle-to-sprint',
    name: 'Lateral Shuffle to Sprint',
    kind: 'sprint',
    equipment: 'Court / cones',
    steps: [
      'Athletic stance at one end of a 5-yard lane, low and ready.',
      'Shuffle laterally 5 yards, plant the outside foot on the last one, snap the hips around, and sprint 10 yards.',
      'The turn is one violent hip flip, no stutter steps between shuffle and sprint. Plant, flip, GONE.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Quads'], qualities: ['Transition speed', 'Hip turn', 'COD'] },
    why: 'Defense to offense in one rep: the shuffle-to-sprint transition trains the hip flip that separates players who react from players who arrive.',
    mistakes: ['Little stutter steps between the shuffle and the sprint, plant, flip, GO.'],
    cue: 'Plant the outside foot, flip the hips. GONE.',
    videoQuery: 'shuffle to sprint transition drill',
    restSec: 150,
  }),
  E({
    id: 'crossover-run',
    name: 'Crossover Run',
    kind: 'sprint',
    equipment: 'Field / court',
    steps: [
      'Turn side-on so your hips face sideways while your shoulders stay square downfield.',
      'Run laterally with the legs crossing over, driving the crossing knee across and through. 10–15 yards each direction.',
      'Smooth and rhythmic, and the shoulders never rotate with the hips.',
    ],
    targets: { muscles: ['Hip flexors', 'Adductors', 'Glutes'], qualities: ['Multidirectional mobility', 'Hip dissociation'] },
    why: 'Separating hips from shoulders while moving is elite body control, the crossover run drills it at low cost and opens up the tight hips that cap lateral quickness.',
    mistakes: ['Letting the shoulders rotate with the hips.'],
    cue: 'Hips run sideways, chest stays forward.',
    videoQuery: 'carioca crossover run drill',
    restSec: 60,
  }),
  E({
    id: 'plant-and-go',
    name: 'Plant-and-Go',
    kind: 'sprint',
    equipment: 'Cone / line',
    steps: [
      'Set a cone or line 5–10 yards away.',
      'Sprint to it, brake in 2–3 chops, plant the OUTSIDE foot beyond your center, drop the hips, and explode back the way you came.',
      'The plant foot lands outside your body so you can push off it, and you stay low through the plant. Alternate plant legs.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Adductors'], qualities: ['Cutting', '180° COD', 'Plant leg strength'] },
    why: 'The single rep of changing direction, isolated: brake, plant wide, go. Every cut in every sport is some version of this rep, so it gets trained on purpose, fresh, both legs.',
    mistakes: ['Planting under your body, you need the foot OUTSIDE to push back from.', 'Standing tall in the plant.'],
    cue: 'Plant WIDE and low, push the floor the other way.',
    videoQuery: 'plant and cut change of direction drill',
    restSec: 150,
  }),
  E({
    id: 'cut-45',
    name: '45° Cut',
    kind: 'sprint',
    equipment: 'Cone / line',
    steps: [
      'Set a cone ahead of you as the cut point.',
      'Sprint at it and make one sharp outside-foot plant that sends you 45° off your line, then accelerate 5 yards out of the cut.',
      'Angle, not stop: minimal braking so you keep most of your speed. Train both directions.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Calves'], qualities: ['Cutting', 'Speed retention', 'COD'] },
    why: 'The 45 is the game’s most common cut, a swerve at speed. Training it teaches you to redirect without giving away the acceleration you already paid for.',
    mistakes: ['Chopping down to a near-stop for a shallow cut, save the brakes for sharper angles.'],
    cue: 'One hard plant, bend the run, keep the speed.',
    videoQuery: '45 degree speed cut drill',
    restSec: 120,
  }),
  E({
    id: 'cut-90',
    name: '90° Cut',
    kind: 'sprint',
    equipment: 'Cone / line',
    steps: [
      'Set a cone as the corner of your cut.',
      'Sprint at it, brake in 2–3 chops, plant the outside foot hard, drop the hips, and explode out perpendicular to your approach.',
      'Cut a sharp corner, not a rounded arc, and spread the braking across the chops, not all on the last step. Both directions, fresh.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Adductors'], qualities: ['Cutting', 'Braking', 'COD'] },
    why: 'The 90 demands real braking AND real re-acceleration, the full deceleration-to-power chain in one rep. It is the sharpest cut most game situations ever ask for.',
    mistakes: ['Rounding the corner (that is a curve, not a cut).', 'All the braking on the final step.'],
    cue: 'Brake early, corner SHARP, first step violent.',
    videoQuery: '90 degree cut change of direction',
    restSec: 150,
  }),
  E({
    id: 'turn-180',
    name: '180° Turn',
    kind: 'sprint',
    equipment: 'Cone / line',
    steps: [
      'Mark a line or cone 5–10 yards out.',
      'Sprint to it, chop the brakes, plant low, snap a full 180° turn, and sprint back. The first step out is the rep, make it vicious.',
      'Stay LOW through the reversal, turning tall is the killer. Alternate turning over each shoulder.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Calves'], qualities: ['180° COD', 'Braking', 'Re-acceleration'] },
    why: 'Full reversals are the hardest brake in sport, everything stops, then everything restarts. Sprinter out, defender back: this is that moment, rehearsed.',
    mistakes: ['Turning tall, you must be LOW through the reversal.'],
    cue: 'Sit into the turn, snap around, first step wins.',
    videoQuery: '180 degree turn sprint drill',
    restSec: 150,
  }),
  E({
    id: 'curved-sprint',
    name: 'Curved Sprint',
    kind: 'sprint',
    equipment: 'Court / arc of cones',
    steps: [
      'Use the three-point line or a wide arc of cones.',
      'Sprint the arc at 90%+ effort, leaning INTO the curve from the ankles, inside arm tighter, outside arm bigger.',
      'Trust the lean, fighting it drifts you wide off the arc. Feel the inside leg push, and run both directions.',
    ],
    targets: { muscles: ['Glutes', 'Adductors', 'Calves'], qualities: ['Curved speed', 'Lean mechanics'] },
    why: 'Game speed is rarely straight. Curved sprinting loads the legs asymmetrically and teaches the lean that lets you carry speed around defenders, bases, and corners.',
    mistakes: ['Fighting the lean and drifting wide off the arc.'],
    cue: 'Lean in from the ankles, hug the arc at speed.',
    videoQuery: 'curved sprint technique training',
    restSec: 180,
  }),

  // ================= REACTIVE AGILITY =================
  E({
    id: 'mirror-drill',
    name: 'Mirror Drill (partner reactive)',
    kind: 'sprint',
    equipment: 'Partner + 5-yard lane',
    steps: [
      'Face a partner across a line in a low athletic stance.',
      'They shuffle, cut, and dart side to side for 5–8 seconds and you mirror every move. Swap leader each rep.',
      'Eyes on their hips and react with your feet, never guess early and lunge. Stay low the whole burst.',
    ],
    targets: { muscles: ['Adductors', 'Glutes', 'Calves'], qualities: ['Reactive agility', 'Read-and-react'] },
    why: 'Cones never juke you. Reacting to a human converts your trained COD into game agility, perception and movement wired together, which is the quality that actually defends people.',
    mistakes: ['Guessing early and lunging.', 'Standing tall between reactions.'],
    cue: 'Eyes on their hips, react, don’t guess.',
    videoQuery: 'mirror drill reactive agility partner',
    restSec: 90,
  }),
  E({
    id: 'reactive-shuttle',
    name: 'Reactive Shuttle (cue-called)',
    kind: 'sprint',
    equipment: 'Cones + a caller (or app cue)',
    steps: [
      'Stand centered between cones with a caller (voice, point, or app cue).',
      'On each cue, sprint or shuffle to the called side, touch, and recover to center for the next call. 4–6 reactions per set.',
      'Stay truly still until the call, creeping toward a guessed side defeats the drill. Full quality every reaction.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Adductors'], qualities: ['Reactive agility', 'First-step reaction'] },
    why: 'Adding an unplanned cue to a shuttle trains the reaction step, the tenth of a second between stimulus and first movement where most game speed is actually won or lost.',
    mistakes: ['Creeping toward a guessed side before the call.'],
    cue: 'Still… then GONE the instant you hear it.',
    videoQuery: 'reactive cone shuttle cue drill',
    restSec: 120,
  }),

  // ================= SINGLE-LEG STABILITY / CONTROL =================
  E({
    id: 'step-down',
    name: 'Step-Down (slow eccentric)',
    kind: 'lift',
    equipment: 'Low box / stair',
    steps: [
      'Stand tall on a low box on one leg, the other foot hovering off the front.',
      'Lower in 3 slow seconds until the free heel kisses the floor with no weight on it, then press back up through the standing leg.',
      'Knee tracks over the middle toes and hips stay level, never drop fast through the bottom half.',
    ],
    targets: { muscles: ['Quads', 'Glutes'], qualities: ['Single-leg control', 'Knee stability'] },
    why: 'The step-down is single-leg knee control in slow motion, it finds the wobble a jump hides and strengthens exactly the range where landings and cuts go wrong.',
    mistakes: ['Dropping fast through the bottom half.', 'Hips hiking sideways instead of staying level.'],
    cue: '3 seconds down, knee over toes, hips level.',
    videoQuery: 'single leg step down exercise',
    restSec: 90,
  }),
  E({
    id: 'lateral-lunge',
    name: 'Lateral Lunge',
    kind: 'lift',
    equipment: 'Bodyweight or dumbbell',
    steps: [
      'Stand tall with room to step sideways, bodyweight or a dumbbell held at your chest.',
      'Take a big step sideways and sit your hips back and down over that leg, other leg straight, then push the floor away to return.',
      'Chest proud and heel glued down, sit INTO the side hip. All reps one side then switch, or alternate.',
    ],
    targets: { muscles: ['Adductors', 'Glutes', 'Quads'], qualities: ['Lateral strength', 'Frontal-plane range'] },
    why: 'Strength in the side-to-side plane is the raw material of cutting, the lateral lunge loads the adductors and glutes through the exact range your plant leg passes through in a hard cut.',
    mistakes: ['Knee drifting past sideways over the toes with the heel lifting.', 'Torso folding flat.'],
    cue: 'Sit INTO the side hip, heel glued down.',
    videoQuery: 'lateral lunge technique',
    restSec: 90,
  }),
  E({
    id: 'single-leg-squat-box',
    name: 'Single-Leg Squat to Box',
    kind: 'lift',
    equipment: 'Bench / box',
    steps: [
      'Stand on one leg in front of a bench or box, arms out front as a counterweight.',
      'Sit back and down under control until you lightly touch the box, then drive back up through the whole foot.',
      'Touch like the box is glass, never plop, and don’t let the knee cave as you stand. Lower the box over time.',
    ],
    targets: { muscles: ['Quads', 'Glutes'], qualities: ['Unilateral strength', 'Pistol progression'] },
    why: 'The box turns the single-leg squat from a party trick into a progressive exercise, measurable depth, honest control, and a direct path to true single-leg strength.',
    mistakes: ['Crashing onto the box.', 'Knee caving as you stand.'],
    cue: 'Touch the box like it’s glass, then stand through the floor.',
    videoQuery: 'single leg box squat progression',
    restSec: 120,
  }),
  E({
    id: 'balance-to-jump',
    name: 'Balance to Jump',
    kind: 'jump',
    equipment: 'Anywhere',
    steps: [
      'Balance on one leg, eyes forward, dead still for 3 full seconds.',
      'From stillness, explode into a max vertical jump off that leg (or both, your level), then stick the landing back under control.',
      'Earn real stillness before you jump, a wobbly balance phase defeats the drill. Stillness, violence, stillness.',
    ],
    targets: { muscles: ['Glutes', 'Calves', 'Quads'], qualities: ['Balance', 'Stability-to-power transfer'] },
    why: 'Producing max force FROM stability is the game skill, nobody hands you a perfect stance. This drill wires the switch from quiet control to full explosion and back.',
    mistakes: ['A wobbling “balance” phase, earn stillness before you jump.'],
    cue: 'Statue… detonate… statue.',
    videoQuery: 'balance to jump single leg drill',
    restSec: 90,
  }),

  // ================= BALLISTIC STRENGTH / EQUIPMENT POWER =================
  E({
    id: 'trap-bar-jump',
    name: 'Trap-Bar Jump',
    kind: 'jump',
    equipment: 'Trap bar (light load)',
    steps: [
      'Load the trap bar light, 15–30% of your deadlift. Grip, brace, flat back.',
      'Dip and JUMP with hips, knees, and ankles all extending fully, bar held tight, a small real flight, then land soft.',
      'Light and fast beats heavy and slow every time here. Reset the stance completely every rep, no casual landings.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Traps'], qualities: ['Loaded power', 'Explosive strength'] },
    why: 'The friendliest loaded jump in the gym, power output rivaling Olympic lifts without the technique tax. Light and fast beats heavy and slow every time here.',
    mistakes: ['Loading heavy until the “jump” barely leaves the floor.', 'Casual landings.'],
    cue: 'Light bar, VIOLENT jump, land like it matters.',
    videoQuery: 'trap bar jump power exercise',
    restSec: 150,
  }),
  E({
    id: 'jump-squat',
    name: 'Jump Squat (light DB)',
    kind: 'jump',
    equipment: 'Light dumbbells or bodyweight',
    steps: [
      'Hold light dumbbells at your sides, or use nothing.',
      'Quarter-squat dip, then jump for real height with full extension and a controlled soft landing.',
      'The load must never visibly slow you down, if it does, go lighter. Reset between every rep, speed stays king.',
    ],
    targets: { muscles: ['Glutes', 'Quads', 'Calves'], qualities: ['Loaded power', 'Rate of force'] },
    why: 'A small load on a real jump raises force output while keeping movement speed honest, the classic bridge between the squat rack and the vertical you actually use.',
    mistakes: ['Going heavy and grinding slow half-jumps.'],
    cue: 'Same jump, tiny load, speed stays king.',
    videoQuery: 'dumbbell jump squat exercise',
    restSec: 120,
  }),
  E({
    id: 'kb-swing',
    name: 'Kettlebell Swing',
    kind: 'lift',
    equipment: 'Kettlebell',
    steps: [
      'Hinge over the bell with a flat back and grip it with both hands.',
      'Hike it back high between your legs, then SNAP the hips forward so the bell floats to chest height, and let it swing into the next hinge.',
      'The arms are just ropes, the hips do all the lifting. Hinge, never squat, crisp reps with no mush.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings'], qualities: ['Hip power', 'Ballistic hinge'] },
    why: 'The swing is repeat-effort hip snap, the same violent extension as a jump, trained by the dozen. It builds the posterior-chain power your sprints and jumps cash out.',
    mistakes: ['Squatting the swing instead of hinging it.', 'Lifting the bell with the arms.'],
    cue: 'Hike it, then SNAP the hips, arms are just ropes.',
    videoQuery: 'kettlebell swing hip hinge technique',
    restSec: 90,
  }),
  E({
    id: 'mb-scoop-toss',
    name: 'Med-Ball Scoop Toss',
    kind: 'jump',
    equipment: 'Medicine ball (6–12 lb)',
    steps: [
      'Hold the med ball low with both hands and hinge back like a swing.',
      'Explode up and slightly back, launching the ball high, then let it fly and land, never catch a max throw.',
      'The hips launch it, the arms just hand it to the sky, no arm-lifting. Reset fully each rep.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Traps'], qualities: ['Total-body power', 'Hip extension'] },
    why: 'Throws let you accelerate through the ENTIRE movement with zero landing cost, a pure expression of hip power that even beginners can go 100% on safely.',
    mistakes: ['Arm-lifting the ball instead of riding the hip snap.'],
    cue: 'Hips launch it, the arms just hand it to the sky.',
    videoQuery: 'medicine ball scoop toss power',
    restSec: 120,
  }),
  E({
    id: 'mb-rotational-throw',
    name: 'Med-Ball Rotational Throw',
    kind: 'jump',
    equipment: 'Medicine ball + wall',
    steps: [
      'Stand side-on to a wall with the ball at your back hip.',
      'Load the back hip, then drive it THROUGH, hips leading, torso following, so the ball rockets into the wall. Collect and reset.',
      'Hips first, arms last, never spin the shoulders ahead of the hips. Work both sides.',
    ],
    targets: { muscles: ['Obliques', 'Glutes', 'Adductors'], qualities: ['Rotational power', 'Hip-to-torso transfer'] },
    why: 'Rotation is the forgotten athletic plane, swinging, throwing, striking, and even sharp cuts all run on hip-led rotational power. The med-ball throw trains it at full intent.',
    mistakes: ['Arm-throwing with lazy hips.', 'Spinning the shoulders first.'],
    cue: 'Back hip drives THROUGH the ball, arms last.',
    videoQuery: 'rotational medicine ball throw technique',
    restSec: 90,
  }),
  E({
    id: 'mb-overhead-throw',
    name: 'Med-Ball Overhead Throw (backward)',
    kind: 'jump',
    equipment: 'Medicine ball + open space',
    steps: [
      'Hold the ball low in a quarter squat, arms long, open space behind you.',
      'Extend EVERYTHING, hips, back, then arms, launching the ball up and over your head behind you. Turn, collect, walk back.',
      'The legs are the engine, jump it off the ground rather than arm-throwing it. Every throw at max intent.',
    ],
    targets: { muscles: ['Glutes', 'Hamstrings', 'Delts'], qualities: ['Total-body power', 'Triple extension'] },
    why: 'The overhead backward throw is the biggest full-body power expression outside a weight room, a jump that ends in a throw. Great testing tool: distance is your power score.',
    mistakes: ['Throwing with arms and back only, the legs are the engine.'],
    cue: 'Jump it off the ground, the ball just keeps going.',
    videoQuery: 'overhead backward medicine ball throw',
    restSec: 120,
  }),
  E({
    id: 'sled-push',
    name: 'Sled Push',
    kind: 'lift',
    equipment: 'Sled',
    steps: [
      'Grip the poles with arms locked long or bent low, body in one straight 45° line.',
      'Drive the sled 10–20 yards with full steps, each one a piston punched into the ground.',
      'Stay in your lean, hips never pop up into a stand. Moderate loads move crisp, heavy loads move strong, both have a place.',
    ],
    targets: { muscles: ['Quads', 'Glutes', 'Calves'], qualities: ['Horizontal strength', 'Acceleration strength'] },
    why: 'Pure horizontal drive with zero eccentric cost, leg strength in the exact posture of acceleration, trainable hard without wrecking tomorrow.',
    mistakes: ['Hips popping up into a stand as you push.', 'Choppy half-steps.'],
    cue: 'Stay in your lean, full steps, piston the ground.',
    videoQuery: 'sled push technique acceleration',
    restSec: 120,
  }),

  // ================= SPRINT HAMSTRING + LOWER LEG =================
  E({
    id: 'nordic-curl',
    name: 'Nordic Curl (eccentric)',
    kind: 'lift',
    equipment: 'Anchored ankles (partner / bench)',
    steps: [
      'Kneel tall with your ankles anchored, glutes squeezed, body one line from knees to head.',
      'Lower forward as SLOWLY as the hamstrings allow, fighting every degree, then catch with your hands and push back up lightly.',
      'Never break at the hips to make it easier. A few slow quality reps beat many sloppy ones.',
    ],
    targets: { muscles: ['Hamstrings'], qualities: ['Eccentric hamstring strength', 'Sprint durability'] },
    why: 'The most protective hamstring exercise ever studied, long-length eccentric strength is exactly what sprinting demands at top speed, and exactly what tears when it is missing.',
    mistakes: ['Breaking at the hips to make it easier.', 'Dropping fast past the sticking point.'],
    cue: 'One straight line, lose the fall as SLOWLY as possible.',
    videoQuery: 'nordic hamstring curl eccentric',
    restSec: 120,
  }),
  E({
    id: 'tibialis-raise',
    name: 'Tibialis Raise',
    kind: 'lift',
    equipment: 'Wall (or plate on toes)',
    steps: [
      'Lean back against a wall, feet a foot-length out, legs straight.',
      'Pull both feet UP toward your shins as high as possible, then lower slow. Full range every rep.',
      'Knees stay straight, no cheating the range. High reps, the burn down the front of the shin is it working.',
    ],
    targets: { muscles: ['Calves'], qualities: ['Lower-leg balance', 'Shin resilience'] },
    why: 'The tibialis is the brake pad of the lower leg, it absorbs every heel strike and landing. Strengthening it bulletproofs shins and ankles for all the bouncing this library asks of them.',
    mistakes: ['Bending the knees and cheating the range.'],
    cue: 'Toes to shins, slow down, full range.',
    videoQuery: 'tibialis raise wall exercise',
    restSec: 60,
  }),
]
