import type { ExerciseDef } from '../types'

// ============================================================
// Full exercise guides. `cue` lines and several `why`/`mistakes`
// entries come straight from the NAOD V3 PDF notes; steps are
// authored to be followable by feel, mid-session, on a phone.
// ============================================================

const E = (def: ExerciseDef) => def

export const EXERCISES: Record<string, ExerciseDef> = Object.fromEntries(
  [
    // ================= MONDAY — TWO-FOOT POWER + FIRST STEP =================
    E({
      id: 'falling-start-sprint',
      name: 'Falling Start Sprint (5–10 yd)',
      kind: 'sprint',
      equipment: 'Field / court',
      steps: [
        'Stand tall, feet together, arms relaxed.',
        'Lean forward from the ankles — keep your body in one straight line — until you literally have to catch yourself.',
        'The instant you tip past the point of no return, fire the catching leg into the ground and GO.',
        'Stay LOW for the first 5 yards: chest over knees, driving the ground backward behind you with each step.',
        'Punch your arms hard — they set the rhythm for your legs.',
        'Walk all the way back and reset completely before the next rep. Full recovery, every rep.',
      ],
      targets: {
        muscles: ['Glutes', 'Hamstrings', 'Calves', 'Hip flexors'],
        qualities: ['First step', 'Acceleration', 'Horizontal power'],
      },
      why: 'This IS your first step. Falling starts teach your body to fire fast and low from stillness — the exact skill of blowing by someone from a dead stop. Your plan puts it first on Monday, on fresh legs, because speed practiced tired is speed practiced wrong.',
      mistakes: [
        'Popping straight up on the first step instead of projecting forward low and hard.',
        'Leaning from the waist instead of the ankles — bend at the hips and you lose the line of force.',
        'Cutting the rest short. This is nervous-system work, not conditioning.',
      ],
      cue: 'Lean till you HAVE to catch yourself. Fire fast and low. Drive the ground back — don’t pop up.',
      videoQuery: 'falling start sprint acceleration drill technique',
      restSec: 180,
    }),
    E({
      id: 'box-jump',
      name: 'Box Jump (two-foot, max height)',
      kind: 'jump',
      equipment: 'Box or bench',
      steps: [
        'Stand a short step back from the box, feet hip-width.',
        'Swing your arms back as you dip your hips fast — a quick, shallow quarter squat.',
        'Explode UP: throw your arms, extend hips, knees, and ankles all at once.',
        'Pull your knees up and land soft on the middle of the box, both feet flat.',
        'Stand fully tall on top. STEP down — never jump down.',
        'Reset your stance and your breath before every jump. Each rep is a max effort.',
      ],
      targets: {
        muscles: ['Glutes', 'Quads', 'Calves'],
        qualities: ['Two-foot vertical', 'Explosive power', 'Rate of force'],
      },
      why: 'Two-foot jumping is max force from a dead stop — your natural strength. Box jumps let you train max-intent takeoffs with almost no landing cost, so your legs stay fresh enough to do it twice a week all year. This feeds your standing dunk power directly.',
      mistakes: [
        'Chasing a high box with a deep knee tuck instead of actually jumping higher. Box height is not jump height.',
        'Jumping DOWN off the box — that is where people get hurt for zero benefit.',
        'Rushing reps while tired. Stop the set the moment your height drops.',
      ],
      cue: 'Max intent every rep. Step down. Stop when height drops.',
      videoQuery: 'box jump proper technique max height',
      restSec: 180,
    }),
    E({
      id: 'goblet-squat',
      name: 'Goblet Squat',
      kind: 'lift',
      equipment: 'Dumbbell',
      steps: [
        'Hold one dumbbell vertically against your chest, elbows tucked under it.',
        'Feet shoulder-width, toes slightly out. Brace your abs like someone is about to poke you.',
        'Sit straight down between your knees — chest proud, elbows tracking inside your knees.',
        'Hit just below parallel (or as deep as you can keep your heels down and back flat).',
        'Drive the floor away FAST — the lowering is controlled, the standing is explosive.',
        'Exhale hard through the sticking point. Re-brace before the next rep.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Core'],
        qualities: ['Leg strength', 'Jump force base', 'Squat pattern'],
      },
      why: 'The squat pattern is a core mover in your plan — it never rotates out, you just keep adding load. On Monday it is deliberately moderate and FAST: it backs up the sprint and jump work without frying your legs before Wednesday’s heavy day.',
      mistakes: [
        'Grinding heavy slow reps on Monday. That is Wednesday’s job — Monday you leave 2–3 in the tank and move the weight with speed.',
        'Heels lifting — elevate them slightly or work ankle mobility (Thursday exists for this).',
        'Letting the chest collapse forward into a good-morning.',
      ],
      cue: 'Moderate and explosive, NOT a grind. Leave 2–3 reps in the tank.',
      videoQuery: 'goblet squat proper form',
      restSec: 150,
    }),
    E({
      id: 'db-front-squat',
      name: 'DB Front Squat',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Clean two dumbbells to your shoulders, one end resting on each shoulder, elbows high.',
        'Feet shoulder-width, toes slightly out. Big breath into your belly, brace.',
        'Squat straight down, staying as upright as the front-loaded weight forces you to be.',
        'Just below parallel, then drive up hard through mid-foot.',
        'Keep elbows up the whole rep — if they drop, the weight pulls you forward.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Upper back', 'Core'],
        qualities: ['Leg strength', 'Upright squat pattern', 'Jump force base'],
      },
      why: 'Front-loading forces the upright torso that carries over to jumping and sprinting posture. Same core-mover squat pattern, new angle for the block — variety for the joints, same engine.',
      mistakes: [
        'Elbows dropping → torso folds → lower back takes over.',
        'Shallow reps as weight goes up. Depth first, load second.',
        'Holding your breath through multiple reps — re-breathe and re-brace each rep.',
      ],
      videoQuery: 'dumbbell front squat form',
      restSec: 150,
    }),
    E({
      id: 'heels-elevated-goblet',
      name: 'Heels-Elevated Goblet Squat',
      kind: 'lift',
      equipment: 'Dumbbell + plates under heels',
      steps: [
        'Set your heels on a plate or low board (1–2 inches), forefoot on the floor.',
        'Hold the dumbbell at your chest like a normal goblet squat.',
        'Squat DEEP — the heel lift lets your knees travel forward, so ride them forward on purpose.',
        'Stay upright, sink to full depth, and feel the quads load hard at the bottom.',
        'Stand explosively. Control down, fast up.',
      ],
      targets: {
        muscles: ['Quads (emphasized)', 'Glutes', 'Core'],
        qualities: ['Knee-dominant strength', 'Deep-range leg drive'],
      },
      why: 'Elevating the heels biases the quads and the deep knee bend — the exact range your legs pass through loading a two-foot jump. Block 3’s angle change keeps the squat pattern progressing without grinding the same groove.',
      mistakes: [
        'Using the heel lift to hide ankle stiffness but still cutting depth — go DEEPER, that is the point.',
        'Knees caving inward at the bottom.',
        'Bouncing out of the bottom instead of staying tight.',
      ],
      videoQuery: 'heels elevated goblet squat benefits form',
      restSec: 150,
    }),
    E({
      id: 'romanian-deadlift',
      name: 'Romanian Deadlift',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Stand tall holding the bar at your hips, hands just outside your thighs.',
        'Soft knees — set them slightly bent and keep that angle the whole rep.',
        'Push your HIPS straight back and let the bar slide down your thighs, back flat, lats tight.',
        'Go until your hamstrings pull hard (usually just below the knees) — not until the bar hits the floor.',
        'Drive your hips forward to stand, squeezing your glutes at the top. Don’t lean back.',
        'Keep the bar glued to your legs the entire time.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Lower back', 'Grip'],
        qualities: ['Hip hinge power', 'Sprint speed', 'Posterior chain'],
      },
      why: 'Your sprint speed and jump both run on the posterior chain, and the RDL is its core builder — a never-rotate lift in your plan. Strong hamstrings are also the insurance policy against the sprint-day hamstring tear.',
      mistakes: [
        'Bending the knees more as you lower — that turns it into a squat and unloads the hamstrings.',
        'Rounding the lower back to chase depth. Depth is wherever YOUR hamstrings end.',
        'Bar drifting away from the legs — it multiplies stress on your spine.',
      ],
      cue: 'Hips back, bar on the legs, hamstrings loaded like bowstrings.',
      videoId: 'uhghy9pFIPY',
      videoQuery: 'romanian deadlift form barbell',
      restSec: 150,
    }),
    E({
      id: 'bulgarian-split-squat',
      name: 'Bulgarian Split Squat',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      perSide: true,
      steps: [
        'Stand a big step in front of the bench, rear foot laces-down on it.',
        'Hold a dumbbell in each hand. Most of your weight lives on the FRONT leg.',
        'Drop your back knee straight down toward the floor, front shin fairly vertical.',
        'Light touch at the bottom, then drive up through the front heel.',
        'Finish all reps on one leg, then switch. Front leg does the work — the back leg is a kickstand.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Adductors'],
        qualities: ['Single-leg strength', 'One-foot jump base', 'Knee stability'],
      },
      why: 'You sprint and jump off one leg at a time. Single-leg strength is what turns your two-foot power into a one-foot takeoff — and it irons out left-right gaps before they become injuries.',
      mistakes: [
        'Standing too close to the bench — cramps the front knee and tips you forward.',
        'Pushing through the back foot. It holds balance, nothing more.',
        'Wobbling side to side — slow down, own the balance; it is half the exercise.',
      ],
      videoId: '2C-uNgKwPLE',
      videoQuery: 'bulgarian split squat proper form dumbbells',
      restSec: 120,
    }),
    E({
      id: 'walking-lunge',
      name: 'Walking Lunge',
      kind: 'lift',
      equipment: 'Dumbbells',
      perSide: true,
      steps: [
        'Stand tall with a dumbbell in each hand at your sides.',
        'Take a long step forward and drop your back knee toward the floor.',
        'Front knee tracks over the toes; torso stays tall with a slight forward lean.',
        'Push HARD off the front heel and step straight through into the next lunge.',
        'Keep moving — smooth, controlled, no pause between steps.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        qualities: ['Single-leg strength', 'Stride power', 'Balance under fatigue'],
      },
      why: 'Lunges load the exact split-stance shape of sprinting. Every stride you run is a single-leg push — this is that push with weight in your hands, building the thick legs your plan calls for.',
      mistakes: [
        'Short choppy steps that keep everything on the quads and stress the knee.',
        'Slamming the back knee into the ground.',
        'Folding at the waist as fatigue builds.',
      ],
      videoQuery: 'walking lunge dumbbell form',
      restSec: 120,
    }),
    E({
      id: 'step-up',
      name: 'Step-Up',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      perSide: true,
      steps: [
        'Stand facing the bench with a dumbbell in each hand.',
        'Put one whole foot on the bench — heel included.',
        'Drive through THAT heel to lift your body up. Don’t bounce off the floor leg.',
        'Stand fully tall on top, then lower yourself down slowly on the same leg.',
        'Finish the set on one side, then switch.',
      ],
      targets: {
        muscles: ['Glutes', 'Quads'],
        qualities: ['Single-leg drive', 'First-step power', 'Hip extension'],
      },
      why: 'A step-up is a first step with load — one leg driving your whole bodyweight up and forward. Block 3 rotates it in to hit the same single-leg quality from a fresh angle.',
      mistakes: [
        'Kicking off the bottom leg — steal from the floor and the top leg learns nothing.',
        'Only half the foot on the bench.',
        'Dropping down with gravity instead of lowering under control.',
      ],
      videoQuery: 'dumbbell step up glute form',
      restSec: 120,
    }),
    E({
      id: 'single-leg-calf-raise',
      name: 'Single-Leg Calf Raise',
      kind: 'lift',
      equipment: '1 dumbbell',
      perSide: true,
      steps: [
        'Stand on one foot on a step or plate, ball of the foot on the edge, heel hanging off.',
        'Hold a dumbbell on the working side; fingertips of the other hand on a wall for balance.',
        'Lower your heel slowly below the step until you feel a deep calf stretch.',
        'Pause one second at the bottom — no bouncing.',
        'Drive up as HIGH as you can onto your big toe. Squeeze hard at the top.',
      ],
      targets: {
        muscles: ['Calves (gastroc + soleus)', 'Foot/ankle stabilizers'],
        qualities: ['Ankle stiffness', 'Jump takeoff', 'Sprint ground contact'],
      },
      why: 'Every jump and every sprint stride ends with the calf and ankle snapping force into the floor. Stiff, strong calves return energy instantly — that is inches on your vertical hiding in an accessory most people skip.',
      mistakes: [
        'Bouncing out of the stretch instead of pausing.',
        'Half reps — no deep stretch, no full rise.',
        'Bending the knee to cheat the weight up.',
      ],
      videoQuery: 'single leg calf raise full range',
      restSec: 90,
    }),
    E({
      id: 'hanging-leg-raise',
      name: 'Hanging Leg Raise',
      kind: 'core',
      equipment: 'Pull-up bar',
      steps: [
        'Hang from the bar, hands shoulder-width, body still.',
        'Tilt your pelvis under first — think “tuck your tailbone”.',
        'Raise your legs (bent knees to start, straight as you get stronger) to hip height or above.',
        'Lower SLOWLY — 2–3 seconds down, without swinging.',
        'Kill all momentum between reps. If you swing, the abs stop working.',
      ],
      targets: {
        muscles: ['Lower abs', 'Hip flexors', 'Grip'],
        qualities: ['Visible abs', 'Core control', 'Knee drive'],
      },
      why: 'Visible abs are a stated goal, and the lower abs are built by raising the legs against gravity — not by crunches. Bonus: hip flexor strength drives the knee punch in your sprint and jump.',
      mistakes: [
        'Swinging into momentum reps.',
        'Lifting with the legs only — the pelvis must curl, or the abs never fire.',
        'Cutting the lowering phase short: that half is where the muscle is made.',
      ],
      videoQuery: 'hanging leg raise strict form',
      restSec: 90,
    }),

    // ================= TUESDAY — PUSH + SHOULDER HEALTH =================
    E({
      id: 'incline-db-press',
      name: 'Incline DB Press',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      steps: [
        'Set the bench to a 30–45° incline. Sit with the dumbbells on your thighs.',
        'Kick them up one at a time as you lie back; start pressed over your upper chest.',
        'Pull your shoulder blades back and down into the bench — they stay pinned all set.',
        'Lower with CONTROL to the outer chest, elbows about 45° from your body.',
        'Press up and slightly in, exhaling hard. Touch the dumbbells gently at the top — no clank.',
      ],
      targets: {
        muscles: ['Upper chest', 'Front delts', 'Triceps'],
        qualities: ['Upper-chest size', 'Pressing strength'],
      },
      why: 'Upper chest is a stated goal of your plan, and it grows from incline volume — which is exactly why this is FIRST every Tuesday, when you are strongest. This is also a core mover: progress it every block.',
      mistakes: [
        'Flattening the incline benefit by flaring elbows straight out.',
        'Bouncing out of the bottom instead of controlling the lowering.',
        'Losing shoulder-blade position — shoulders rolling forward is how pressing starts to hurt.',
      ],
      cue: 'Incline first every week. Control the lowering, press hard.',
      videoId: '8iPEnn-ltC8',
      videoQuery: 'incline dumbbell press upper chest form',
      restSec: 150,
    }),
    E({
      id: 'flat-db-press',
      name: 'Flat DB Press',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      steps: [
        'Lie flat, feet planted on the floor, slight arch, shoulder blades pinned back and down.',
        'Start with dumbbells over your chest, palms forward or slightly turned in.',
        'Lower under control until you feel a full chest stretch, elbows ~45° from your sides.',
        'Press up and slightly together, squeezing the chest at lockout.',
        'Keep your wrists stacked straight over your elbows the whole rep.',
      ],
      targets: {
        muscles: ['Chest', 'Front delts', 'Triceps'],
        qualities: ['Pressing strength', 'Chest mass'],
      },
      why: 'The flat press builds the overall chest mass under your incline work. Dumbbells over a bar means each side works alone and your shoulders move freely — more muscle, less joint stress, perfect for a home gym.',
      mistakes: [
        'Elbows flared to 90° — max shoulder stress for no extra chest.',
        'Half-rep lockouts with no top squeeze.',
        'Feet dancing around — plant them and push the floor away.',
      ],
      videoQuery: 'flat dumbbell bench press form',
      restSec: 150,
    }),
    E({
      id: 'floor-press',
      name: 'Close-Grip Floor Press',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Lie on the floor under the bar (or roll it over you), knees bent, feet flat.',
        'Grip just inside shoulder-width. Elbows tucked close to your sides.',
        'Lower under control until your upper arms rest gently on the floor — pause a beat.',
        'Press hard from the dead stop, exhaling through the press.',
        'Lock out with triceps, keeping wrists straight over elbows.',
      ],
      targets: {
        muscles: ['Triceps', 'Chest', 'Front delts'],
        qualities: ['Lockout strength', 'Pressing power from a dead stop'],
      },
      why: 'The floor shortens the range and forces a dead-stop press — pure triceps and pure starting strength, with the shoulders protected. Block 3 rotates it in so your press keeps climbing without beating up the same angle all year.',
      mistakes: [
        'Bouncing the arms off the floor instead of pausing.',
        'Flaring elbows — keep them tucked, this is a triceps lift.',
        'Bridging your hips off the floor.',
      ],
      videoQuery: 'barbell floor press technique',
      restSec: 150,
    }),
    E({
      id: 'standing-ohp',
      name: 'Standing Barbell OHP',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Bar at your collarbones, hands just outside shoulders, elbows slightly in front of the bar.',
        'Squeeze your glutes and brace your abs HARD — your torso is the platform.',
        'Press the bar in a straight line, pulling your chin back to let it pass your face.',
        'As the bar clears your head, push your head “through the window” so the bar stacks over your spine.',
        'Lock out with biceps by your ears. Lower under control back to the collarbones.',
      ],
      targets: {
        muscles: ['Shoulders', 'Triceps', 'Upper chest', 'Core'],
        qualities: ['Overhead strength', 'Wide-shoulder mass', 'Total-body stiffness'],
      },
      why: 'Wide, capped shoulders are on your goal list, and the standing press is their heaviest builder — plus it is a core mover you progress all year. Standing (not seated) makes your trunk transfer force, the same job it does in a jump.',
      mistakes: [
        'Leaning way back and turning it into an incline press — squeeze the glutes to stop this.',
        'Pressing around your face in a curve instead of moving your head.',
        'No leg drive allowed — if you need to dip and push, the weight is too heavy.',
      ],
      videoId: 'GlyABLsPk-Q',
      videoQuery: 'standing barbell overhead press form',
      restSec: 150,
    }),
    E({
      id: 'lateral-raise',
      name: 'Lateral Raise',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Stand tall, dumbbells at your sides, slight bend in the elbows.',
        'Lean forward a hair and raise the weights out to your sides — leading with your ELBOWS.',
        'Stop at shoulder height, pinkies slightly higher than thumbs, like pouring water.',
        'Lower slowly — 2–3 seconds down. The lowering is half the set.',
        'Stay strict. If you have to swing, the weight is too heavy.',
      ],
      targets: {
        muscles: ['Side delts'],
        qualities: ['Shoulder width', 'The V-taper look'],
      },
      why: 'Shoulder WIDTH is mostly the side delt, and the side delt only really grows from raises — pressing barely touches it. High reps, light weight, twice a week: this is what makes shoulders read wide from across the court.',
      mistakes: [
        'Swinging heavy dumbbells with the traps doing everything.',
        'Raising with straight vertical arms — soft elbows, lead with them.',
        'Dropping the weights on the way down.',
      ],
      videoQuery: 'lateral raise proper form side delts',
      restSec: 90,
    }),
    E({
      id: 'close-grip-press',
      name: 'Close-Grip Bench / Floor Press',
      kind: 'lift',
      equipment: 'Barbell + bench',
      steps: [
        'Grip the bar just inside shoulder-width — NOT hands-touching narrow.',
        'Unrack with wrists stacked straight; elbows stay tucked near your sides.',
        'Lower to your lower chest under control, forearms staying vertical.',
        'Press up, finishing the last third with a hard triceps lockout.',
        'Exhale through the press; re-set your brace between reps.',
      ],
      targets: {
        muscles: ['Triceps', 'Chest', 'Front delts'],
        qualities: ['Arm size (the 16″ goal)', 'Pressing lockout'],
      },
      why: 'Two-thirds of arm size is triceps. The close grip lets you overload them with real weight instead of only isolation moves — feeding the 16-inch arm target while backing up every press you do.',
      mistakes: [
        'Grip so narrow the wrists hurt — inside shoulder-width is close enough.',
        'Elbows flaring, which turns it back into a chest press.',
        'Bouncing off the chest.',
      ],
      videoQuery: 'close grip bench press triceps form',
      restSec: 120,
    }),
    E({
      id: 'overhead-tricep-extension',
      name: 'Overhead Tricep Extension',
      kind: 'lift',
      equipment: '1 dumbbell or EZ bar',
      steps: [
        'Stand or sit tall. Hold one dumbbell with both hands cupped under the top plate, overhead.',
        'Elbows point forward, close to your head — lock them in place.',
        'Lower the weight slowly behind your head until you feel a deep triceps stretch.',
        'Extend back to straight arms without moving the upper arms.',
        'Keep ribs down and abs on so your lower back doesn’t arch.',
      ],
      targets: {
        muscles: ['Triceps (long head)'],
        qualities: ['Arm size', 'Elbow health under load'],
      },
      why: 'The long head of the triceps — the big one that makes arms look thick from the side — only gets fully stretched overhead. This is the isolation piece the close-grip pressing doesn’t cover.',
      mistakes: [
        'Elbows drifting out wide as you fatigue.',
        'Short pump reps in the top half — the stretch at the bottom is the growth.',
        'Arching the lower back to fake range.',
      ],
      videoQuery: 'overhead dumbbell tricep extension form',
      restSec: 90,
    }),
    E({
      id: 'prone-y-raise',
      name: 'Prone Y Raise',
      kind: 'lift',
      equipment: 'Light dumbbells + incline bench',
      steps: [
        'Lie face down on an incline bench, arms hanging straight down, light dumbbells in hand.',
        'Turn your thumbs UP toward the ceiling.',
        'Raise both arms up-and-out into a Y shape, squeezing the lower traps between your shoulder blades.',
        'Pause at the top for a second.',
        'Lower slow and controlled. These stay LIGHT — 5s and 10s do the job.',
      ],
      targets: {
        muscles: ['Lower traps', 'Rear delts', 'Rotator cuff'],
        qualities: ['Shoulder health', 'Overhead stability'],
      },
      why: 'You press hard twice a week and throw dunks on Saturday — this is the insurance. Strong lower traps keep the shoulder blade rotating properly overhead, which is what keeps pressing pain-free all year.',
      mistakes: [
        'Going heavy and shrugging with the upper traps.',
        'Thumbs down — that position pinches the shoulder.',
        'Rushing. Slow and controlled is the entire point.',
      ],
      cue: 'Slow and controlled — feel the rear delts and lower traps.',
      videoQuery: 'prone Y raise incline bench lower trap',
      restSec: 60,
    }),

    // ================= WEDNESDAY — LOWER STRENGTH + HYPERTROPHY =================
    E({
      id: 'front-squat',
      name: 'DB / Barbell Front Squat',
      kind: 'lift',
      equipment: 'Dumbbells or barbell',
      steps: [
        'Barbell: bar on front delts, fingertips under it, elbows driven HIGH. DBs: one on each shoulder.',
        'Feet shoulder-width, toes slightly out. Big belly breath, brace hard.',
        'Squat down keeping your torso as vertical as possible — the front load demands it.',
        'Below parallel if your heels stay down; drive up through mid-foot.',
        'Elbows stay high the entire rep. Exhale over the top, re-brace, go again.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Upper back', 'Core'],
        qualities: ['Heavy leg strength', 'Vertical force', 'Thick legs'],
      },
      why: 'Wednesday is the heavy version of the squat pattern — slower and heavier than Monday, building the thick legs and raw force your jumps convert into height. Placed two days before Saturday so your legs arrive fresh for sprints.',
      mistakes: [
        'Elbows dropping and the bar rolling forward.',
        'Cutting depth as the load climbs.',
        'Grinding to failure — heavy, not reckless; a rep or two always left in the tank.',
      ],
      videoId: '0ect9ETE6t0',
      videoQuery: 'front squat technique barbell dumbbell',
      restSec: 180,
    }),
    E({
      id: 'hip-thrust',
      name: 'Barbell Hip Thrust',
      kind: 'lift',
      equipment: 'Barbell + bench',
      steps: [
        'Sit on the floor, upper back against the bench edge (bottom of the shoulder blades).',
        'Roll the bar over your hips onto a pad or folded towel.',
        'Feet flat, hip-width, positioned so your shins are VERTICAL at the top.',
        'Drive through your heels and squeeze your glutes to lift the bar until your body is a flat table.',
        'Chin tucked, ribs down — do NOT arch the lower back to finish.',
        'Hold the top squeeze for a full second, lower under control, repeat.',
      ],
      targets: {
        muscles: ['Glutes', 'Hamstrings'],
        qualities: ['Hip extension power', 'Vertical jump', 'Sprint drive'],
      },
      why: 'Huge for vertical and glute size — the PDF says it straight. Jumping and sprinting are violent hip extension, and nothing loads hip extension like a heavy thrust. This is a core mover: keep adding plates all year.',
      mistakes: [
        'Overarching the back at the top instead of squeezing the glutes flat.',
        'Feet too far out (hamstring cramp) or too close (all quads).',
        'Bouncing fast half reps — own the one-second squeeze at the top.',
      ],
      cue: 'Shoulders on the bench, bar padded across the hips. Squeeze, don’t arch.',
      videoId: 'LM8XHLYJoYs',
      videoQuery: 'barbell hip thrust setup form bench',
      restSec: 150,
    }),
    E({
      id: 'single-leg-rdl',
      name: 'Single-Leg RDL',
      kind: 'lift',
      equipment: 'Dumbbell',
      perSide: true,
      steps: [
        'Hold a dumbbell in the hand OPPOSITE the standing leg.',
        'Soft knee on the standing leg. Hinge at the hip, letting the free leg drift straight back.',
        'Keep hips SQUARE to the floor — imagine headlights on your hip bones pointing down.',
        'Lower until the hamstring pulls hard (dumbbell near mid-shin), back flat.',
        'Drive the hips forward to stand, squeezing the glute. All reps one side, then switch.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Ankle/hip stabilizers'],
        qualities: ['Single-leg hinge', 'Plant-leg strength', 'Balance'],
      },
      why: 'Your one-foot jump plants on a single loaded hamstring — this is that moment, slowed down and strengthened. It also bulletproofs the hamstring for max-velocity sprint day.',
      mistakes: [
        'Hips rotating open toward the free leg.',
        'Rounding the back to touch the floor — range ends where the hamstring ends.',
        'Rushing the balance. Slow is strong here.',
      ],
      videoId: 'gz9l8UA_KXs',
      videoQuery: 'single leg romanian deadlift dumbbell form',
      restSec: 120,
    }),
    E({
      id: 'good-morning',
      name: 'Good Morning',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Bar on your upper back like a squat, hands squeezing it tight, lats on.',
        'Feet hip-width, soft knees fixed in place.',
        'Push your hips straight BACK, folding at the hip until your torso nears 45° (or hamstrings stop you).',
        'Keep the back table-flat and the bar path over mid-foot.',
        'Drive hips forward to stand tall. Start LIGHT — this rewards patience.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Spinal erectors'],
        qualities: ['Hip hinge strength', 'Posterior chain armor'],
      },
      why: 'Block 2’s hamstring rotation. Same hinge engine as the RDL but loaded on your back, which makes the erectors work overtime — carryover to every sprint, jump, and pickup-game rebound landing.',
      mistakes: [
        'Bending the knees into a squat as it gets heavy.',
        'Any rounding of the lower back — this lift punishes ego, keep it light and perfect.',
        'Going too deep; stop where the hamstrings stop you.',
      ],
      videoQuery: 'barbell good morning exercise form',
      restSec: 150,
    }),
    E({
      id: 'slider-leg-curl',
      name: 'Slider Leg Curl',
      kind: 'lift',
      equipment: 'Floor + towel/sliders',
      steps: [
        'Lie on your back, heels on towels (hard floor) or sliders, knees bent, hips bridged UP.',
        'From the bridge, slide your heels away until your legs are nearly straight — hips stay up.',
        'Drag your heels back toward you with your hamstrings, keeping the bridge tall.',
        'That drag-back is the rep. Slow out, strong in.',
        'If it’s too hard, slide out only as far as you can control. Too easy: pause 2s extended.',
      ],
      targets: {
        muscles: ['Hamstrings (knee-flexion role)', 'Glutes'],
        qualities: ['Hamstring resilience', 'Sprint-speed protection'],
      },
      why: 'Hamstrings do two jobs — hip hinge and knee flexion — and sprint injuries live in the second one. Block 3 adds this to cover the job your RDLs don’t, right when your sprint speeds are at their highest of the year.',
      mistakes: [
        'Hips sagging to the floor mid-rep — the bridge is non-negotiable.',
        'Letting the slide out just drop instead of resisting it.',
        'Yanking with the lower back.',
      ],
      videoQuery: 'sliding leg curl towel hamstring exercise',
      restSec: 120,
    }),
    E({
      id: 'seated-calf-raise',
      name: 'Seated / Bent-Knee Calf Raise',
      kind: 'lift',
      equipment: 'Dumbbell + bench',
      perSide: true,
      steps: [
        'Sit on the bench, ball of one foot on a plate or step, dumbbell standing on that knee.',
        'Let the heel sink to a deep stretch — pause one second.',
        'Press up onto the ball of the foot as high as it goes, squeezing the calf.',
        'Slow down, pause, drive up. No bouncing at any point.',
        'Finish the side, then switch.',
      ],
      targets: {
        muscles: ['Soleus (deep calf)'],
        qualities: ['Ankle stiffness', 'Ground-contact snap'],
      },
      why: 'With the knee bent, the deep soleus does the work — the muscle firing during the bent-knee moments of sprinting and jump loading. Block 2 rotates it in so both calf muscles get their turn.',
      mistakes: [
        'Bouncing reps off the stretch reflex.',
        'Too little weight to matter — the soleus is dense and strong; load it.',
        'Partial range at the top.',
      ],
      videoQuery: 'seated calf raise dumbbell soleus',
      restSec: 90,
    }),
    E({
      id: 'double-leg-calf-raise',
      name: 'Double-Leg Heavy Calf Raise',
      kind: 'lift',
      equipment: 'Dumbbells + step',
      steps: [
        'Stand with both forefeet on a step or plate, heels hanging, a heavy dumbbell in each hand.',
        'Sink both heels to a deep stretch. One-second pause.',
        'Drive up as tall as possible onto the big toes — think “jump without leaving the ground”.',
        'Squeeze the top hard, lower over 2–3 seconds.',
        'Both legs means more total load — go heavier than the single-leg weeks.',
      ],
      targets: {
        muscles: ['Calves (gastroc emphasis)'],
        qualities: ['Heavy ankle strength', 'Takeoff stiffness'],
      },
      why: 'Block 3 trades single-leg reps for pure LOAD. Heavier calves = a stiffer ankle at takeoff — the last link that turns leg force into rim height instead of mushy ground contact.',
      mistakes: [
        'Loading so heavy the range shrinks to a pulse.',
        'Skipping the bottom pause.',
        'Rolling to the outside edge of the foot — finish over the big toe.',
      ],
      videoQuery: 'heavy standing calf raise dumbbells form',
      restSec: 90,
    }),
    E({
      id: 'weighted-situp',
      name: 'Weighted Sit-Up',
      kind: 'core',
      equipment: '1 plate or dumbbell',
      steps: [
        'Lie on your back, knees bent, feet anchored or flat. Hug a plate to your chest.',
        'Exhale and curl UP one vertebra at a time — chin soft, no neck yanking.',
        'Come to a tall sit, plate still tight to your chest.',
        'Lower back down SLOWLY, resisting the whole way — 2–3 seconds.',
        'Add weight over the weeks like any lift. Abs grow with load, like everything else.',
      ],
      targets: {
        muscles: ['Rectus abdominis (the six-pack)', 'Hip flexors'],
        qualities: ['Visible abs', 'Trunk flexion strength'],
      },
      why: 'Visible abs need two things: a leaner waist (nutrition’s job) and thicker ab muscle (this). Progressive load is what makes abs pop through — treat it like a lift, not a burnout.',
      mistakes: [
        'Pulling on your neck.',
        'Dropping down fast and losing the eccentric half.',
        'Reps so fast the hip flexors take everything.',
      ],
      videoQuery: 'weighted sit up plate form',
      restSec: 90,
    }),
    E({
      id: 'plank-side-plank',
      name: 'Plank + Side Plank',
      kind: 'core',
      equipment: 'Floor',
      steps: [
        'Front plank: forearms down, body one straight line, glutes and abs squeezed HARD.',
        'Push the floor away so your upper back is full, not sagging between the shoulders.',
        'Hold with intent — a hard 30 seconds beats a saggy 90.',
        'Side plank: elbow under shoulder, feet stacked, hips lifted tall; top arm up or on hip.',
        'Do front + each side. That trio is one set.',
      ],
      targets: {
        muscles: ['Deep core', 'Obliques', 'Shoulder stabilizers'],
        qualities: ['Anti-rotation', 'Trunk stiffness for sprints', 'Waist control'],
      },
      why: 'Sprinting and jumping leak power through a soft trunk. Planks teach the core to lock the ribcage to the pelvis so every pound of leg force arrives at the floor — and the obliques frame a tighter waist.',
      mistakes: [
        'Hips sagging or hiking — one straight line, filmed or mirrored if unsure.',
        'Holding your breath; breathe shallow and steady behind the brace.',
        'Zoning out. Squeeze harder, hold shorter.',
      ],
      videoQuery: 'plank side plank proper form',
      restSec: 60,
    }),

    // ================= THURSDAY — MOBILITY + ACTIVE RECOVERY =================
    E({
      id: 'hip-9090-switch',
      name: '90/90 Hip Switch',
      kind: 'mobility',
      equipment: 'Floor',
      perSide: true,
      steps: [
        'Sit with your front leg bent 90° in front of you and back leg bent 90° behind you.',
        'Sit tall — chest proud, both sit bones trying to stay down.',
        'Rotate both knees together to the other side, switching front/back legs.',
        'Pause in each position; lean your chest over the front shin for extra hip stretch.',
        'Slow, breathing switches. No forcing.',
      ],
      targets: {
        muscles: ['Hip rotators', 'Glutes', 'Hip capsule'],
        qualities: ['Hip range for jumps', 'Change-of-direction health'],
      },
      why: 'Your hips take every plant, cut, and landing. Rotational hip range is what lets you load a jump deep and land absorbing force with muscle instead of joint — this keeps that range from shrinking under all the lifting.',
      mistakes: [
        'Slouching through the switches.',
        'Using hands to lift through every rep instead of the hips doing the work.',
        'Bouncing at end range.',
      ],
      videoQuery: '90 90 hip switch mobility drill',
      restSec: 30,
    }),
    E({
      id: 'deep-squat-hold',
      name: 'Deep Squat Hold + Pry',
      kind: 'mobility',
      equipment: 'Bodyweight',
      steps: [
        'Sink into the deepest squat you can, heels down, feet a bit wider than usual.',
        'Elbows inside the knees, palms together — gently pry the knees outward.',
        'Sit tall in the hole; breathe slow and let your hips sink deeper with each exhale.',
        'Shift weight side to side to open each ankle and hip.',
        'Hold the prescribed time. Hold onto something in front if balance fights you.',
      ],
      targets: {
        muscles: ['Hips', 'Ankles', 'Adductors', 'Lower back (decompression)'],
        qualities: ['Squat depth', 'Jump-loading range'],
      },
      why: 'The deep squat is the human resting position your lifting depends on. Owning it keeps Wednesday’s heavy squats deep and safe — and ankle-and-hip range directly raises your jump, per your own plan.',
      mistakes: [
        'Heels floating — elevate them slightly rather than tipping forward.',
        'Rounding into a slump instead of sitting tall in the hole.',
        'Holding your breath; the exhale is what unlocks depth.',
      ],
      videoQuery: 'deep squat hold pry mobility',
      restSec: 30,
    }),
    E({
      id: 'ankle-wall-mobilization',
      name: 'Ankle Wall Mobilization',
      kind: 'mobility',
      equipment: 'Wall',
      perSide: true,
      steps: [
        'Face a wall, toes about a hand-width away from it.',
        'Keeping the heel GLUED down, drive your knee straight over your toes toward the wall.',
        'Touch the wall (or get as close as the ankle allows), pause, return.',
        'Too easy? Slide the foot back an inch. The heel staying down is the only rule.',
        'Smooth reps, both sides.',
      ],
      targets: {
        muscles: ['Ankle joint', 'Calves', 'Achilles'],
        qualities: ['Dorsiflexion', 'Deeper jump load', 'Plant-leg safety'],
      },
      why: 'Ankle range is hidden vertical. A stiff ankle cuts your jump load short and dumps stress into the knee on every plant — your plan calls this out directly: ankle and hip range raise the jump and protect the plant leg.',
      mistakes: [
        'Heel peeling up — that rep counted for nothing.',
        'Knee diving inward; track it over the second toe.',
        'Rushing through without the pause at end range.',
      ],
      videoQuery: 'ankle dorsiflexion wall mobilization knee to wall',
      restSec: 30,
    }),
    E({
      id: 'couch-stretch',
      name: 'Couch Stretch',
      kind: 'mobility',
      equipment: 'Wall / couch',
      perSide: true,
      steps: [
        'Kneel with your back foot up against a wall or couch, back knee tucked into the corner.',
        'Front foot flat in front, lunge position.',
        'Squeeze the back-leg glute and tuck your pelvis — feel the stretch move to the front of the hip.',
        'Only then raise your torso taller to deepen it. Breathe.',
        'Long, calm holds. It should feel intense, never sharp.',
      ],
      targets: {
        muscles: ['Hip flexors', 'Quads'],
        qualities: ['Hip extension range', 'Stride length', 'Sprint mechanics'],
      },
      why: 'Sitting and lifting shorten the hip flexors, and short hip flexors cap your sprint stride and steal hip extension from every jump. This opens the front of the hip so your glutes can finish what they start.',
      mistakes: [
        'Arching the lower back instead of tucking the pelvis — the stretch must live in the hip, not the spine.',
        'Skipping the glute squeeze that makes it work.',
        'Forcing depth on day one.',
      ],
      videoQuery: 'couch stretch hip flexor correct form',
      restSec: 30,
    }),
    E({
      id: 't-spine-opener',
      name: 'T-Spine Opener',
      kind: 'mobility',
      equipment: 'Floor',
      perSide: true,
      steps: [
        'Lie on your side, knees pulled up to hip height, arms stacked straight in front of you.',
        'Keeping the knees glued together on the floor, sweep your top arm up and over to the other side.',
        'Follow your hand with your eyes; let the chest open toward the ceiling.',
        'Pause and breathe into the twist, then return.',
        'Smooth reps per side.',
      ],
      targets: {
        muscles: ['Thoracic spine', 'Chest', 'Shoulders'],
        qualities: ['Overhead range', 'Pressing posture', 'Rotation'],
      },
      why: 'Overhead pressing and heavy rows need a mid-back that extends and rotates. A stiff t-spine makes the shoulder and lower back pay the difference — this keeps Tuesday’s OHP clean and pain-free.',
      mistakes: [
        'Top knee lifting off — that turns spine rotation into hip rotation.',
        'Whipping the arm over with momentum.',
        'Shallow breathing; the exhale opens the twist.',
      ],
      videoQuery: 'open book t-spine rotation stretch',
      restSec: 30,
    }),
    E({
      id: 'dead-hang',
      name: 'Dead Hang',
      kind: 'mobility',
      equipment: 'Pull-up bar',
      steps: [
        'Grip the bar overhand, shoulder-width, and hang with straight arms.',
        'Let your shoulders shrug up by your ears — relax and let the spine lengthen.',
        'Breathe slow; feel the lats, chest, and spine decompress.',
        'Keep body quiet — no swinging.',
        'Build toward the full prescribed hold. Grip is being trained for free.',
      ],
      targets: {
        muscles: ['Lats', 'Grip', 'Shoulders', 'Spine (decompression)'],
        qualities: ['Overhead range', 'Grip endurance', 'Spinal recovery'],
      },
      why: 'Your plan says it plainly: the dead hang decompresses your spine after a week of loading, and it quietly builds the grip that pull-ups, carries, and rim-hangs all draw on.',
      mistakes: [
        'Actively pulling the shoulders down the whole time — let them lengthen for the decompression benefit.',
        'Death-gripping so hard you cut the hold short; relax into it.',
        'Swinging.',
      ],
      videoQuery: 'dead hang benefits proper technique',
      restSec: 45,
    }),
    E({
      id: 'easy-walk',
      name: 'Easy Walk',
      kind: 'cardio',
      equipment: 'Outside',
      steps: [
        'Head out the door. Conversational pace — you could talk the whole way.',
        'Arms relaxed, breathe through your nose if you can.',
        '20–30 minutes. Sunlight is a bonus for sleep tonight.',
        'This is recovery, not training. Do not turn it into a workout.',
      ],
      targets: {
        muscles: ['Whole body (low intensity)'],
        qualities: ['Recovery', 'Blood flow', 'Daily steps'],
      },
      why: 'Easy movement clears the sludge from Wednesday’s heavy legs without adding any fatigue — so Friday and Saturday get your best. Steps are the cheapest recovery tool you own.',
      mistakes: [
        'Speed-walking it into cardio. Keep it genuinely easy.',
        'Skipping it because it feels too small to matter. It matters.',
      ],
      videoQuery: 'zone 1 recovery walk benefits',
      restSec: 0,
    }),

    // ================= FRIDAY — PULL + GRIP + SHOULDER HEALTH =================
    E({
      id: 'pull-up',
      name: 'Pull-Ups (wide grip)',
      kind: 'lift',
      equipment: 'Pull-up bar',
      steps: [
        'Grip the bar wider than shoulders, palms away. Hang with straight arms.',
        'Set your shoulders first: pull the blades down and back before the arms bend.',
        'Drive your ELBOWS down toward your hips — think of pulling the bar to you.',
        'Chin over the bar (chest toward it if you can), squeeze the lats.',
        'Lower ALL the way to straight arms — every rep starts from a dead hang.',
        'Max reps means max honest reps: stop when form breaks, log the number.',
      ],
      targets: {
        muscles: ['Lats', 'Upper back', 'Biceps', 'Grip'],
        qualities: ['Lat WIDTH', 'The V-taper', 'Pulling strength'],
      },
      why: 'Wide lats are a stated goal and this is where lat width gets built — the PDF’s words. It is a core mover: same exercise all year, and the climbing rep number becomes one of your clearest progress charts.',
      mistakes: [
        'Half reps that skip the dead-hang bottom — those build ego, not lats.',
        'Kipping/swinging through reps.',
        'Leading with a chin-poke instead of driving the elbows down.',
      ],
      videoId: 'rmdn5X_KLkY',
      videoQuery: 'wide grip pull up form lats',
      restSec: 150,
    }),
    E({
      id: 'barbell-row',
      name: 'Barbell Row',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Hinge to about 45° (or lower), bar hanging at arm’s length, back flat, knees soft.',
        'Brace, then pull the bar to your lower ribs / upper stomach.',
        'Drive the elbows back, squeezing the shoulder blades together at the top.',
        'Lower under control to full stretch without dropping the chest.',
        'Torso stays still — if you heave upright to move it, strip weight.',
      ],
      targets: {
        muscles: ['Lats', 'Mid-back', 'Rear delts', 'Biceps', 'Lower back (isometric)'],
        qualities: ['Back thickness', 'Pulling strength'],
      },
      why: 'Pull-ups build width; rows build the thickness behind it. A big flat pull also balances all your pressing so the shoulders stay healthy and the frame reads powerful from the side.',
      mistakes: [
        'Standing up 30° every rep to cheat the weight up.',
        'Pulling to the chest with flared elbows — target the lower ribs.',
        'Rounding the lower back as fatigue sets in.',
      ],
      videoId: 'FWJR5Ve8bnQ',
      videoQuery: 'barbell bent over row proper form',
      restSec: 150,
    }),
    E({
      id: 'db-pullover',
      name: 'DB Pullover',
      kind: 'lift',
      equipment: 'Dumbbell + bench',
      steps: [
        'Lie across or along the bench, feet planted. Hold one dumbbell with both hands over your chest.',
        'Slight fixed bend in the elbows — lock that angle for the whole set.',
        'Lower the weight in an arc back over your head until you feel a deep lat + chest stretch.',
        'Pull it back over your chest in the same arc, ribs staying DOWN.',
        'Slow arc back, strong arc up. The stretch is the growth signal.',
      ],
      targets: {
        muscles: ['Lats (long stretch)', 'Chest', 'Serratus', 'Triceps (long head)'],
        qualities: ['Lat width', 'Ribcage expansion look', 'Overhead range'],
      },
      why: 'The pullover loads the lats at their longest — the stretch position that pull-ups and rows never reach. Week A’s tool for wider lats and a fuller upper body, straight off your goal list.',
      mistakes: [
        'Bending and extending the elbows — that turns it into a triceps extension.',
        'Flaring the ribs and arching the back to fake range.',
        'Going so heavy the stretch gets cut short.',
      ],
      videoQuery: 'dumbbell pullover lats form bench',
      restSec: 120,
    }),
    E({
      id: 'one-arm-db-row',
      name: 'One-Arm DB Row',
      kind: 'lift',
      equipment: 'Dumbbell + bench',
      perSide: true,
      steps: [
        'Left knee and left hand on the bench, right foot planted wide, back flat like a table.',
        'Dumbbell hanging in the right hand, shoulder relaxed toward the floor.',
        'Pull the elbow up and BACK toward your hip — not straight up to the ceiling.',
        'Touch the dumbbell to your side at the top, squeeze the lat.',
        'Lower to a full stretch, letting the shoulder blade slide forward at the bottom. Switch sides.',
      ],
      targets: {
        muscles: ['Lats', 'Mid-back', 'Biceps', 'Grip'],
        qualities: ['Unilateral pull strength', 'Lat width + thickness'],
      },
      why: 'One side at a time means full focus, a longer range than the barbell allows, and no lower-back limit — so the lats get direct heavy work. Week B’s rotation partner to the pullover.',
      mistakes: [
        'Yanking with rotation — the torso stays square to the floor.',
        'Pulling the elbow out wide, turning it into a rear-delt row.',
        'Short top-half pumps with no bottom stretch.',
      ],
      videoQuery: 'one arm dumbbell row form',
      restSec: 120,
    }),
    E({
      id: 'chest-supported-row',
      name: 'Chest-Supported Row',
      kind: 'lift',
      equipment: 'Dumbbells + incline bench',
      steps: [
        'Set the bench to ~30–45° and lie chest-down on it, dumbbells hanging below.',
        'Let the shoulder blades spread at the bottom — full stretch.',
        'Row both elbows back toward your hips, squeezing the blades together.',
        'Pause a beat at the top; the bench stops all cheating.',
        'Lower slow to the full hang. What moves is exactly what your back can row.',
      ],
      targets: {
        muscles: ['Mid-back', 'Lats', 'Rear delts', 'Biceps'],
        qualities: ['Strict pulling volume', 'Back detail', 'Spine-friendly rowing'],
      },
      why: 'Block 3’s row: the bench deletes momentum and spares the lower back late in the training year, so the upper back gets every rep. Strictness is the progression here, not just load.',
      mistakes: [
        'Lifting the chest off the pad to heave.',
        'Range shrinking as the set gets hard.',
        'Shrugging into the neck instead of pulling to the hips.',
      ],
      videoQuery: 'chest supported dumbbell row incline bench',
      restSec: 120,
    }),
    E({
      id: 'rear-delt-raise',
      name: 'Rear Delt Raise (slow tempo)',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Hinge to near-flat torso, light dumbbells hanging, soft elbows.',
        'Raise the weights out to your sides, leading with the elbows, thumbs slightly down.',
        'Stop at shoulder line — feel the back of the shoulder do it, not the traps.',
        'Lower on a strict 3-SECOND count. The slow lowering is the exercise.',
        'Stay light. This is precision work.',
      ],
      targets: {
        muscles: ['Rear delts', 'Mid traps'],
        qualities: ['3-D shoulder look', 'Shoulder health', 'Posture'],
      },
      why: 'The 3-second lowering doubles as your shoulder-health work — the PDF builds it in on purpose. Rear delts balance all your pressing, finish the wide-shoulder look from behind, and keep the joint centered.',
      mistakes: [
        'Going heavy and swinging — the rear delt is small; let it work alone.',
        'Rushing the 3-second eccentric. That IS the set.',
        'Standing too upright, which turns it into a lateral raise.',
      ],
      cue: '3-second lowering, every rep. Doubles as shoulder health.',
      videoQuery: 'bent over rear delt raise slow eccentric',
      restSec: 90,
    }),
    E({
      id: 'ez-bar-curl',
      name: 'EZ Bar Curl',
      kind: 'lift',
      equipment: 'EZ bar',
      steps: [
        'Grip the EZ bar on the angled grips, arms hanging, elbows pinned to your sides.',
        'Curl the bar up in an arc without the elbows drifting forward or up.',
        'Squeeze the biceps hard at the top for a beat.',
        'Lower on a controlled 2–3 count to FULL straight arms.',
        'No hip bump, no lean-back. Strip weight before you strip form.',
      ],
      targets: {
        muscles: ['Biceps', 'Forearms'],
        qualities: ['Arm size (16″ goal)', 'Elbow-friendly curling'],
      },
      why: 'The EZ bar’s angle spares your wrists while letting you load the biceps heaviest — the base builder for the 16-inch arm target. Curls also show up Saturday because arms recover fast and twice-a-week arms grow.',
      mistakes: [
        'Elbows drifting forward, turning it into a front raise.',
        'Half-rep bottom — full extension is where the growth range lives.',
        'Swinging with the hips on the last reps.',
      ],
      videoQuery: 'ez bar curl proper form biceps',
      restSec: 90,
    }),
    E({
      id: 'incline-db-curl',
      name: 'Incline DB Curl',
      kind: 'lift',
      equipment: 'Dumbbells + incline bench',
      steps: [
        'Set the bench to ~45–60° and lie back, arms hanging straight DOWN behind your body line.',
        'Palms forward. Curl both dumbbells up without the elbows creeping forward.',
        'Squeeze at the top, then lower slowly to that deep hanging stretch.',
        'The stretch at the bottom is the point — don’t shorten it.',
        'Lighter than your EZ curl weight. That’s correct, not weak.',
      ],
      targets: {
        muscles: ['Biceps (long head, stretched)'],
        qualities: ['Arm size', 'Peak development'],
      },
      why: 'The incline puts the biceps under load at full stretch — the position research keeps showing grows muscle fastest. Block 2 swaps it in so the arms get a new stimulus without new equipment.',
      mistakes: [
        'Shoulders rolling forward off the bench to shorten the stretch.',
        'Turning it into a hammer curl when it burns — keep palms up.',
        'Bouncing out of the bottom.',
      ],
      videoQuery: 'incline dumbbell curl stretch form',
      restSec: 90,
    }),
    E({
      id: 'hammer-curl',
      name: 'Hammer Curl',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Stand tall, dumbbells at your sides, palms facing each other — keep that neutral grip.',
        'Curl up with elbows pinned, like swinging a hammer.',
        'Squeeze at the top, lower under control to straight arms.',
        'Both arms together or alternating — just no swinging.',
        'This grip is your strongest curl; load it accordingly.',
      ],
      targets: {
        muscles: ['Brachialis', 'Biceps', 'Forearms (brachioradialis)'],
        qualities: ['Arm THICKNESS', 'Grip strength'],
      },
      why: 'The brachialis sits under the biceps — grow it and the whole arm gets wider from every angle. The neutral grip also builds the forearms that your pull-ups, carries, and rim grabs run on.',
      mistakes: [
        'Rocking the torso to swing the weight up.',
        'Elbows flaring away from the body.',
        'Racing through the lowering.',
      ],
      videoQuery: 'hammer curl proper form',
      restSec: 90,
    }),
    E({
      id: 'farmer-carry',
      name: 'Farmer Carry',
      kind: 'carry',
      equipment: 'Loadable dumbbells',
      steps: [
        'Deadlift a heavy dumbbell up in each hand — flat back, legs doing the lift.',
        'Stand TALL: ribs down, shoulders back, crush grip on the handles.',
        'Walk with short, quick, controlled steps for the prescribed time.',
        'No leaning, no shuffling collapse — posture is the exercise.',
        'Set the weights down with a flat back, rest, repeat.',
      ],
      targets: {
        muscles: ['Grip/forearms', 'Traps', 'Core', 'Whole body'],
        qualities: ['Grip strength for dunking', 'Trunk stability', 'Work capacity'],
      },
      why: 'Straight from the PDF: carries build the grip strength for dunking and general athleticism. Hanging on the rim, ripping rebounds, heavy RDLs — all grip-limited. Carries fix that while hammering the core.',
      mistakes: [
        'Weights too light to threaten your grip — it should be a fight by the end.',
        'Leaning back or shrugging up into the ears.',
        'Long lazy strides that swing the bells.',
      ],
      videoQuery: 'farmer carry walk proper form',
      restSec: 120,
    }),
    E({
      id: 'towel-hang',
      name: 'Towel Hang',
      kind: 'carry',
      equipment: 'Towel + pull-up bar',
      steps: [
        'Drape a towel over the pull-up bar and grab a handful with each hand.',
        'Hang with straight arms, feet off the floor, body quiet.',
        'CRUSH the towel — the thick, soft grip makes your hands and forearms scream.',
        'Hang for max honest time; log the seconds.',
        'One towel per hand for even more grip if it gets easy.',
      ],
      targets: {
        muscles: ['Grip (crush + support)', 'Forearms', 'Lats'],
        qualities: ['Rim-hang grip', 'Forearm size', 'Ball security'],
      },
      why: 'The towel’s thickness turns a hang into a max-grip event — the closest thing in your gym to hanging on a rim. Grip strength is the unglamorous piece of dunking your plan refuses to skip.',
      mistakes: [
        'Regripping constantly instead of fighting for the hold.',
        'Swinging to pass the time — quiet body, working hands.',
        'Quitting at discomfort rather than actual failure. Log real maxes.',
      ],
      videoQuery: 'towel hang grip training',
      restSec: 120,
    }),

    // ================= SATURDAY — MAX SPEED + ONE-FOOT REACTIVE =================
    E({
      id: 'dynamic-warmup',
      name: 'Dynamic Warm-Up',
      kind: 'warmup',
      equipment: 'Bodyweight',
      steps: [
        '2–3 min easy jog or skipping to raise your temperature.',
        'Leg swings front/back and side/side — 10 each leg.',
        'Walking lunges with a twist, high knees, butt kicks — ~20 yards each.',
        'A-skips, then 2–3 build-up runs at 60% → 80% → 90% effort.',
        'By the end you should feel FAST, loose, and slightly buzzed — not tired.',
      ],
      targets: {
        muscles: ['Whole body'],
        qualities: ['Sprint readiness', 'Injury prevention'],
      },
      why: 'Max-velocity sprinting on cold hamstrings is how pulls happen. Eight minutes here is the price of admission for the fastest running of your week — never skip it, never rush it.',
      mistakes: [
        'Static stretching instead of moving — save long holds for after.',
        'Turning the warm-up into a workout.',
        'Skipping the build-up runs and going 0-to-max on rep one.',
      ],
      videoQuery: 'dynamic warm up sprinting routine',
      restSec: 0,
    }),
    E({
      id: 'max-velocity-sprint',
      name: 'Max-Velocity Sprint (30–40 yd)',
      kind: 'sprint',
      equipment: 'Field / street',
      steps: [
        'Build up over the first 10–15 yards — smooth acceleration, rising posture.',
        'Hit TOP SPEED through the middle: tall posture, high knees, loose face and hands.',
        'Strike the ground under your hips, big backside arm swing, cheeks bouncing loose.',
        'Ease off gradually at the end — never slam the brakes.',
        'Walk back fully + extra rest. Every rep at true 100%. Tired sprinting is cancelled sprinting.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Hip flexors', 'Calves'],
        qualities: ['Top-end speed', 'Elastic power', 'The back half of your sprint'],
      },
      why: 'Top speed lives here — your plan’s words. Max-velocity work builds the part of your sprint AFTER you’re moving, and it’s the single most potent stimulus in athletics. It must be done fresh, which is exactly why it leads Saturday.',
      mistakes: [
        'Straining and gritting — speed comes from relaxation at max effort.',
        'Short rest turning speed work into conditioning.',
        'Sprinting through fatigue: stop the moment you feel slower.',
      ],
      cue: 'TRUE max effort. Full recovery. Never tired. Stop when speed drops.',
      videoQuery: 'max velocity sprint mechanics top speed',
      restSec: 240,
    }),
    E({
      id: 'flying-sprint',
      name: 'Flying Sprint (10 yd run-in, 20 yd max)',
      kind: 'sprint',
      equipment: 'Field / street',
      steps: [
        'Mark a 10-yard build-in zone and a 20-yard fly zone.',
        'Accelerate GRADUALLY through the build-in — about 80% by the line.',
        'The instant you cross into the fly zone: EXPLODE to your absolute fastest running.',
        'Stay tall and relaxed — jaw loose, hands loose, knees punching.',
        'Coast down long. Walk back + full rest. These are your fastest strides of the week.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Calves'],
        qualities: ['Absolute top speed', 'Stride frequency', 'Elastic return'],
      },
      why: 'The run-in removes the slow start so every fly yard happens at max velocity — more top-speed exposure per rep than any other drill. This is where your fastest running gets faster.',
      mistakes: [
        'Sprinting the build-in and arriving at the fly zone already fading.',
        'Pressing/forcing in the fly — think “fast and loose”, not “hard”.',
        'Doing extra reps while slowing. Three great flys beat six mediocre ones.',
      ],
      cue: 'Gradual run-in, then explode — your fastest running.',
      videoQuery: 'flying sprints top speed drill',
      restSec: 240,
    }),
    E({
      id: 'pogo-hop',
      name: 'Pogo Hops (stiff ankle)',
      kind: 'jump',
      equipment: 'Floor',
      steps: [
        'Stand tall, hands relaxed. Legs nearly straight — knees soft but NOT bending for power.',
        'Bounce off the balls of your feet like a pogo stick — ankles do everything.',
        'Ground contact as SHORT as possible: think “hot floor”.',
        'Get height from ankle snap and stiffness, not from squatting.',
        'Crisp rhythmic reps. If your heels start slapping down, rest.',
      ],
      targets: {
        muscles: ['Calves', 'Achilles tendon', 'Feet'],
        qualities: ['Tendon stiffness', 'Elastic return', 'One-foot jump spring'],
      },
      why: 'Your one-foot jump runs on the same elastic spring as sprinting, and pogos build exactly that: tendon stiffness. The PDF names them the tool for it. Stiffer tendons = the ground gives your jump back for free.',
      mistakes: [
        'Bending the knees into little squat jumps — that’s a different exercise.',
        'Long mushy ground contacts. Short and springy or stop.',
        'Landing on flat feet / heels.',
      ],
      videoQuery: 'pogo hops plyometric ankle stiffness',
      restSec: 120,
    }),
    E({
      id: 'approach-jump',
      name: 'Penultimate-Step Approach Jump',
      kind: 'jump',
      equipment: 'Court / hoop',
      steps: [
        'Take a 3–5 step build-up approach at about 70–80% speed.',
        'PENULTIMATE step (second-to-last): step LONG and LOW — this drops your hips and loads the plant leg.',
        'Plant fast: short last step, foot slightly ahead, leg stiff like a pole vault pole.',
        'Drive the opposite knee and both arms UP violently as you fire off the plant leg.',
        'Land soft on two feet. Walk back, full reset, practice the rhythm every single time.',
      ],
      targets: {
        muscles: ['Plant-leg hamstrings/glutes', 'Calves', 'Hip flexors'],
        qualities: ['One-foot vertical', 'Speed-to-height conversion', 'Approach rhythm'],
      },
      why: 'Your plan calls the penultimate step THE single most important piece of the one-foot jump. Most converting jumpers stay too upright and lose all their height — the long-low second-to-last step is the fix, and it needs reps as much as strength.',
      mistakes: [
        'Staying upright through the plant — no hip drop, no height. The #1 error.',
        'Slowing down into the jump instead of converting speed through it.',
        'A long, slow last step that kills the spring. Penultimate long, last step SHORT.',
      ],
      cue: 'Lower the hips on the second-to-last step. Fire off one foot, knee UP.',
      videoId: 'cvhNlIEZvS4',
      videoQuery: 'penultimate step single leg jump technique',
      restSec: 180,
    }),
    E({
      id: 'dunk-attempt',
      name: 'One-Foot Max Vert / Dunk Attempts',
      kind: 'jump',
      equipment: 'Hoop',
      steps: [
        'Full approach, full intent — this is game-speed jumping.',
        'Same rhythm you drilled: penultimate long and low, plant fast, knee up hard.',
        'Reach for your target: rim grab, ball dunk, or backboard high-point.',
        'Land soft on two feet, absorbing through the hips.',
        'Track your best touch height — it’s one of your weekly progress numbers.',
      ],
      targets: {
        muscles: ['Full lower body', 'Core'],
        qualities: ['One-foot max vertical', 'Dunk conversion', 'Confidence'],
      },
      why: 'The goal IS consistent dunks — so the plan has you attempt them, fresh, every week. Expect the one-foot jump to feel weaker than two-foot at first: normal, temporary, and for many converted jumpers it eventually wins because you keep all your run-up speed.',
      mistakes: [
        'Grinding attempts while tired — stop the drill the moment height drops.',
        'Changing your approach every rep. Same rhythm, better execution.',
        'Judging the one-foot jump in month one. The elasticity takes weeks — don’t quit early.',
      ],
      cue: 'Stop the moment height drops. Fresh jumps only.',
      videoId: 'SMhtEjgNzMI',
      videoQuery: 'one foot dunk approach training',
      restSec: 180,
    }),

    // ================= CARDIO BACKUP OPTIONS =================
    E({
      id: 'easy-jog',
      name: 'Easy Jog',
      kind: 'cardio',
      equipment: 'Outside',
      steps: [
        'Jog at a conversational pace — you can talk the whole time. That’s the test.',
        'Land softly, quick light steps.',
        '25–30 minutes. Nose-breathing pace is about right.',
        'If your legs are trashed from training, walk instead. Zone 2 is a tool, not a test.',
      ],
      targets: {
        muscles: ['Heart', 'Legs (low load)'],
        qualities: ['Aerobic base', 'Recovery between hard days', 'Conditioning floor'],
      },
      why: 'Zone-2 work builds the engine that lets you play full games without fading — without interfering with lifting or jumping. Your no-ball-week replacement when energy is just okay.',
      mistakes: [
        'Creeping into a medium-hard run that adds fatigue but builds nothing specific.',
        'Stacking it on top of a full ball week. It replaces ball, not adds.',
      ],
      videoQuery: 'zone 2 running benefits pace',
      restSec: 0,
    }),
    E({
      id: 'brisk-walk',
      name: 'Brisk Walk (outdoor)',
      kind: 'cardio',
      equipment: 'Outside',
      steps: [
        'Walk with purpose — noticeably faster than a stroll, arms swinging.',
        '30–45 minutes outside. Clear your head while you’re at it.',
        'Breathing elevated but easy conversation still possible.',
      ],
      targets: {
        muscles: ['Legs', 'Heart (light)'],
        qualities: ['Recovery-friendly conditioning', 'Daily steps'],
      },
      why: 'The most recovery-friendly option on tired weeks — real conditioning volume with zero interference to your lifting or jumps. Get outside, bank the steps.',
      mistakes: ['Counting a phone-scrolling amble as brisk. Move with intent.'],
      videoQuery: 'brisk walking workout benefits',
      restSec: 0,
    }),
    E({
      id: 'incline-walk',
      name: 'Incline Walk',
      kind: 'cardio',
      equipment: 'Treadmill (if gym access)',
      steps: [
        'Treadmill at 10–15% incline, 3.0–3.5 mph.',
        'NO holding the rails — that deletes the work. Pump your arms.',
        '25–30 min steady. Heart rate up, joints happy.',
      ],
      targets: {
        muscles: ['Glutes', 'Calves', 'Heart'],
        qualities: ['Zone-2 conditioning', 'Posterior chain endurance'],
      },
      why: 'All the heart-rate benefit of jogging with none of the impact — glutes and calves get quiet extra volume that feeds your jump. Best zone-2 pick when the weather or your joints say no to running.',
      mistakes: ['Holding the rails.', 'Cranking speed instead of incline.'],
      videoQuery: 'incline treadmill walk benefits',
      restSec: 0,
    }),
    E({
      id: 'hill-sprint',
      name: 'Hill Sprints',
      kind: 'cardio',
      equipment: 'Steep hill (30–40 yd)',
      steps: [
        'Find a steep hill, 30–40 yards of runnable slope.',
        'Sprint UP all-out: big knee drive, big arms, forward lean into the slope.',
        'Walk down slowly — that’s your full rest.',
        '6–10 sprints. Stop when your speed visibly drops.',
      ],
      targets: {
        muscles: ['Glutes', 'Hamstrings', 'Calves', 'Heart'],
        qualities: ['Conditioning + power', 'Acceleration strength', 'Fat burn'],
      },
      why: 'The hill forces perfect acceleration mechanics (you literally cannot overstride uphill) while being easier on the hamstrings than flat sprints. Conditioning that also feeds your first step — the highest-value hard-cardio option you have.',
      mistakes: [
        'Jogging the downhill instead of walking — recovery is part of the protocol.',
        'Doing these the day before Monday or Saturday and pre-fatiguing your speed work.',
      ],
      videoQuery: 'hill sprints workout benefits',
      restSec: 0,
    }),
    E({
      id: 'parking-lot-sprint',
      name: 'Parking Lot Sprints',
      kind: 'cardio',
      equipment: 'Any open space',
      steps: [
        '10–15 seconds ALL OUT — true max effort.',
        'Rest 45–60 seconds (walk it).',
        'Repeat 6–10 rounds.',
        'Effort is the variable that matters: if it stops being max, you’re done.',
      ],
      targets: {
        muscles: ['Full lower body', 'Heart'],
        qualities: ['Repeat-sprint conditioning', 'Game-shape'],
      },
      why: 'Basketball is repeated short max efforts with incomplete rest — this is that, distilled. When you can’t play ball, this keeps the exact energy system that games run on.',
      mistakes: [
        'Pacing yourself into 80% “sprints”. Shorter and truly max beats longer and fake.',
        'Skipping the walk-rest and turning it into a jog.',
      ],
      videoQuery: 'sprint interval training 10 seconds',
      restSec: 0,
    }),
    E({
      id: 'stair-run',
      name: 'Stair Runs',
      kind: 'cardio',
      equipment: 'Stadium or building stairs',
      steps: [
        'Run up hard — every step or every other step, arms driving.',
        'Walk down. That’s the rest.',
        '8–12 rounds, stopping while quality is still high.',
        'Stay on the balls of your feet; the calves are supposed to feel it.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Calves', 'Heart'],
        qualities: ['Leg-drive conditioning', 'Knee-punch mechanics'],
      },
      why: 'Stairs force the high-knee, ball-of-foot drive of good acceleration and light up the calves that pogo work also targets. A hard-cardio option that quietly rehearses sprint mechanics.',
      mistakes: ['Flat-footed stomping.', 'Racing the descent — walk it, it’s your rest.'],
      videoQuery: 'stair sprints workout',
      restSec: 0,
    }),
    E({
      id: 'circuit-a',
      name: 'Home Circuit A',
      kind: 'cardio',
      equipment: 'None, indoor',
      steps: [
        '10 burpees — chest to floor, jump at the top.',
        '20 jumping jacks — brisk rhythm.',
        '10 squat jumps — land soft, sink, explode.',
        'Rest 1 minute. Repeat 4–5 rounds.',
        'Full-body, high output — push the pace inside each round.',
      ],
      targets: {
        muscles: ['Full body'],
        qualities: ['Conditioning', 'High output indoors'],
      },
      why: 'Bad weather, no space to run, still need to sweat — this is the plan’s indoor answer. High-output full-body rounds that keep your engine from idling on a no-ball week.',
      mistakes: [
        'Sloppy burpees with saggy hips — quality first, pace second.',
        'Landing squat jumps stiff-legged.',
      ],
      videoQuery: 'burpee squat jump circuit workout',
      restSec: 60,
    }),
    E({
      id: 'circuit-b',
      name: 'Home Circuit B',
      kind: 'cardio',
      equipment: 'None, indoor',
      steps: [
        '30 seconds mountain climbers — steady, hips low.',
        '30 seconds high knees — quick feet, tall chest.',
        '30 seconds rest.',
        'Repeat 8–10 rounds at a steady, repeatable pace.',
      ],
      targets: {
        muscles: ['Core', 'Hip flexors', 'Legs', 'Heart'],
        qualities: ['Endurance', 'Steady conditioning'],
      },
      why: 'The steadier indoor option — builds endurance without the pounding, and the high-knee pattern doubles as sprint-posture practice. Pick this over Circuit A when you want work, not war.',
      mistakes: [
        'Hips piking up on mountain climbers.',
        'Sprinting rounds 1–2 and dying by round 4 — even pace across all rounds.',
      ],
      videoQuery: 'mountain climbers high knees interval workout',
      restSec: 60,
    }),
  ].map((e) => [e.id, e]),
)

export function getExercise(id: string): ExerciseDef {
  const def = EXERCISES[id]
  if (!def) throw new Error(`Unknown exercise id: ${id}`)
  return def
}

export const ALL_EXERCISE_IDS = Object.keys(EXERCISES)
