import type { ExerciseDef } from '../types'
import { ATHLETIC_EXERCISES } from './athleticExercises'

// ============================================================
// Full exercise guides. `cue` lines and several `why`/`mistakes`
// entries come straight from the NAOD V3 PDF notes; steps are
// authored to be followable by feel, mid-session, on a phone.
// ============================================================

const E = (def: ExerciseDef) => def

export const EXERCISES: Record<string, ExerciseDef> = Object.fromEntries(
  [
    // ================= MONDAY. TWO-FOOT POWER + FIRST STEP =================
    E({
      id: 'falling-start-sprint',
      name: 'Falling Start Sprint (5–10 yd)',
      kind: 'sprint',
      equipment: 'Field / court',
      steps: [
        'Stand tall with feet together and arms relaxed, body in one straight line.',
        'Lean forward from the ankles until you have to catch yourself, then fire that leg down and sprint 5–10 yards low, driving the ground back.',
        'Stay chest over knees with hard arm punches, don’t pop up early. Walk back and fully recover before every rep.',
      ],
      targets: {
        muscles: ['Glutes', 'Hamstrings', 'Calves', 'Hip flexors'],
        qualities: ['First step', 'Acceleration', 'Horizontal power'],
      },
      why: 'This IS your first step. Falling starts teach your body to fire fast and low from stillness, the exact skill of blowing by someone from a dead stop. Your plan puts it first on Monday, on fresh legs, because speed practiced tired is speed practiced wrong.',
      mistakes: [
        'Popping straight up on the first step instead of projecting forward low and hard.',
        'Leaning from the waist instead of the ankles, bend at the hips and you lose the line of force.',
        'Cutting the rest short. This is nervous-system work, not conditioning.',
      ],
      cue: 'Lean till you HAVE to catch yourself. Fire fast and low. Drive the ground back, don’t pop up.',
      videoQuery: 'falling start sprint acceleration drill technique',
      restSec: 180,
    }),
    E({
      id: 'box-jump',
      name: 'Box Jump (two-foot, max height)',
      kind: 'jump',
      equipment: 'Box or bench',
      steps: [
        'Stand a short step back from the box, feet hip-width, arms ready to swing.',
        'Dip fast with a big arm swing, explode up off both feet, and land soft on the middle of the box, both feet flat. Stand tall on top.',
        'Every rep is a max effort from a full reset, and always STEP down, never jump down. Stop the set when your height drops.',
      ],
      targets: {
        muscles: ['Glutes', 'Quads', 'Calves'],
        qualities: ['Two-foot vertical', 'Explosive power', 'Rate of force'],
      },
      why: 'Two-foot jumping is max force from a dead stop, your natural strength. Box jumps let you train max-intent takeoffs with almost no landing cost, so your legs stay fresh enough to do it twice a week all year. This feeds your standing dunk power directly.',
      mistakes: [
        'Chasing a high box with a deep knee tuck instead of actually jumping higher. Box height is not jump height.',
        'Jumping DOWN off the box, that is where people get hurt for zero benefit.',
        'Rushing reps while tired. Stop the set the moment your height drops.',
      ],
      cue: 'Max intent every rep. Step down. Stop when height drops.',
      videoQuery: 'box jump proper technique max height',
      restSec: 180,
    }),
    E({
      id: 'goblet-squat',
      name: 'Goblet Squat',
      kind: 'lift',
      equipment: 'Dumbbell',
      steps: [
        'Hold one dumbbell vertically against your chest, elbows tucked under it. Feet shoulder-width, toes slightly out, abs braced.',
        'Sit straight down between your knees to just below parallel, chest proud, then drive the floor away FAST to stand.',
        'Control the lowering, explode up, and exhale hard through the sticking point. Heels stay down, leave 2–3 reps in the tank.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Core'],
        qualities: ['Leg strength', 'Jump force base', 'Squat pattern'],
      },
      why: 'The squat pattern is a core mover in your plan, it never rotates out, you just keep adding load. On Monday it is deliberately moderate and FAST: it backs up the sprint and jump work without frying your legs before Wednesday’s heavy day.',
      mistakes: [
        'Grinding heavy slow reps on Monday. That is Wednesday’s job. Monday you leave 2–3 in the tank and move the weight with speed.',
        'Heels lifting, elevate them slightly or work ankle mobility (Thursday exists for this).',
        'Letting the chest collapse forward into a good-morning.',
      ],
      cue: 'Moderate and explosive, NOT a grind. Leave 2–3 reps in the tank.',
      videoQuery: 'goblet squat proper form',
      restSec: 150,
    }),
    E({
      id: 'db-front-squat',
      name: 'DB Front Squat',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Clean two dumbbells to your shoulders, one end resting on each, elbows high. Feet shoulder-width, big breath, brace.',
        'Squat straight down, staying as upright as the front load demands, to just below parallel, then drive up hard through mid-foot.',
        'Keep the elbows up the whole rep so the weight can’t pull you forward. Re-breathe and re-brace before every rep.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Upper back', 'Core'],
        qualities: ['Leg strength', 'Upright squat pattern', 'Jump force base'],
      },
      why: 'Front-loading forces the upright torso that carries over to jumping and sprinting posture. Same core-mover squat pattern, new angle for the block, variety for the joints, same engine.',
      mistakes: [
        'Elbows dropping → torso folds → lower back takes over.',
        'Shallow reps as weight goes up. Depth first, load second.',
        'Holding your breath through multiple reps, re-breathe and re-brace each rep.',
      ],
      videoQuery: 'dumbbell front squat form',
      restSec: 150,
    }),
    E({
      id: 'heels-elevated-goblet',
      name: 'Heels-Elevated Goblet Squat',
      kind: 'lift',
      equipment: 'Dumbbell + plates under heels',
      steps: [
        'Set your heels on a 1–2 inch plate or board, forefoot on the floor, and hold a dumbbell at your chest like a goblet squat.',
        'Squat DEEP, riding the knees forward on purpose, feel the quads load at the bottom, then stand explosively.',
        'Stay upright and tight, control down and fast up. No bouncing out of the bottom and no knees caving in.',
      ],
      targets: {
        muscles: ['Quads (emphasized)', 'Glutes', 'Core'],
        qualities: ['Knee-dominant strength', 'Deep-range leg drive'],
      },
      why: 'Elevating the heels biases the quads and the deep knee bend, the exact range your legs pass through loading a two-foot jump. Block 3’s angle change keeps the squat pattern progressing without grinding the same groove.',
      mistakes: [
        'Using the heel lift to hide ankle stiffness but still cutting depth, go DEEPER, that is the point.',
        'Knees caving inward at the bottom.',
        'Bouncing out of the bottom instead of staying tight.',
      ],
      videoQuery: 'heels elevated goblet squat benefits form',
      restSec: 150,
    }),
    E({
      id: 'romanian-deadlift',
      name: 'Romanian Deadlift',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Stand tall holding the bar at your hips, hands just outside your thighs, knees slightly bent and fixed at that angle.',
        'Push your hips back so the bar slides down your thighs until the hamstrings pull hard below the knees, then drive the hips forward to stand.',
        'Keep the bar glued to your legs and your back flat the whole time. Squeeze the glutes at the top, don’t lean back.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Lower back', 'Grip'],
        qualities: ['Hip hinge power', 'Sprint speed', 'Posterior chain'],
      },
      why: 'Your sprint speed and jump both run on the posterior chain, and the RDL is its core builder, a never-rotate lift in your plan. Strong hamstrings are also the insurance policy against the sprint-day hamstring tear.',
      mistakes: [
        'Bending the knees more as you lower, that turns it into a squat and unloads the hamstrings.',
        'Rounding the lower back to chase depth. Depth is wherever YOUR hamstrings end.',
        'Bar drifting away from the legs, it multiplies stress on your spine.',
      ],
      cue: 'Hips back, bar on the legs, hamstrings loaded like bowstrings.',
      videoId: 'uhghy9pFIPY',
      videoQuery: 'romanian deadlift form barbell',
      restSec: 150,
    }),
    E({
      id: 'bulgarian-split-squat',
      name: 'Bulgarian Split Squat',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      perSide: true,
      steps: [
        'Stand a big step in front of the bench, rear foot laces-down on it, a dumbbell in each hand. Weight lives on the front leg.',
        'Drop the back knee straight down toward the floor, front shin fairly vertical, touch lightly, then drive up through the front heel.',
        'The back leg is just a kickstand, never push off it. Own the balance, finish all reps on one leg, then switch.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Adductors'],
        qualities: ['Single-leg strength', 'One-foot jump base', 'Knee stability'],
      },
      why: 'You sprint and jump off one leg at a time. Single-leg strength is what turns your two-foot power into a one-foot takeoff, and it irons out left-right gaps before they become injuries.',
      mistakes: [
        'Standing too close to the bench, cramps the front knee and tips you forward.',
        'Pushing through the back foot. It holds balance, nothing more.',
        'Wobbling side to side, slow down, own the balance; it is half the exercise.',
      ],
      videoId: '2C-uNgKwPLE',
      videoQuery: 'bulgarian split squat proper form dumbbells',
      restSec: 120,
    }),
    E({
      id: 'walking-lunge',
      name: 'Walking Lunge',
      kind: 'lift',
      equipment: 'Dumbbells',
      perSide: true,
      steps: [
        'Stand tall with a dumbbell in each hand at your sides.',
        'Take a long step forward, drop the back knee toward the floor, then push HARD off the front heel straight into the next lunge.',
        'Torso tall with a slight lean, front knee over the toes. Smooth continuous steps, no slamming the back knee down.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Hamstrings'],
        qualities: ['Single-leg strength', 'Stride power', 'Balance under fatigue'],
      },
      why: 'Lunges load the exact split-stance shape of sprinting. Every stride you run is a single-leg push, this is that push with weight in your hands, building the thick legs your plan calls for.',
      mistakes: [
        'Short choppy steps that keep everything on the quads and stress the knee.',
        'Slamming the back knee into the ground.',
        'Folding at the waist as fatigue builds.',
      ],
      videoQuery: 'walking lunge dumbbell form',
      restSec: 120,
    }),
    E({
      id: 'step-up',
      name: 'Step-Up',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      perSide: true,
      steps: [
        'Stand facing the bench with a dumbbell in each hand. Put one whole foot on it, heel included.',
        'Drive through that heel to lift your body up until you stand fully tall on top, then lower down slowly on the same leg.',
        'Don’t kick off the bottom leg, the top leg does all the work. Finish the set on one side, then switch.',
      ],
      targets: {
        muscles: ['Glutes', 'Quads'],
        qualities: ['Single-leg drive', 'First-step power', 'Hip extension'],
      },
      why: 'A step-up is a first step with load, one leg driving your whole bodyweight up and forward. Block 3 rotates it in to hit the same single-leg quality from a fresh angle.',
      mistakes: [
        'Kicking off the bottom leg, steal from the floor and the top leg learns nothing.',
        'Only half the foot on the bench.',
        'Dropping down with gravity instead of lowering under control.',
      ],
      videoQuery: 'dumbbell step up glute form',
      restSec: 120,
    }),
    E({
      id: 'single-leg-calf-raise',
      name: 'Single-Leg Calf Raise',
      kind: 'lift',
      equipment: '1 dumbbell',
      perSide: true,
      steps: [
        'Stand one foot on a step, ball of the foot on the edge, heel hanging. Dumbbell on the working side, other hand on a wall.',
        'Lower the heel slowly below the step to a deep stretch, pause one second, then drive up as high as you can onto the big toe.',
        'No bouncing and no bending the knee to cheat. Full stretch to full squeeze, every rep.',
      ],
      targets: {
        muscles: ['Calves (gastroc + soleus)', 'Foot/ankle stabilizers'],
        qualities: ['Ankle stiffness', 'Jump takeoff', 'Sprint ground contact'],
      },
      why: 'Every jump and every sprint stride ends with the calf and ankle snapping force into the floor. Stiff, strong calves return energy instantly, that is inches on your vertical hiding in an accessory most people skip.',
      mistakes: [
        'Bouncing out of the stretch instead of pausing.',
        'Half reps, no deep stretch, no full rise.',
        'Bending the knee to cheat the weight up.',
      ],
      videoQuery: 'single leg calf raise full range',
      restSec: 90,
    }),
    E({
      id: 'hanging-leg-raise',
      name: 'Hanging Leg Raise',
      kind: 'core',
      equipment: 'Pull-up bar',
      steps: [
        'Hang from the bar, hands shoulder-width, body still.',
        'Tuck your tailbone under first, then raise your legs (bent knees to start) to hip height or above, and lower over 2–3 slow seconds.',
        'Kill all swing between reps. If momentum sneaks in, the abs stop working.',
      ],
      targets: {
        muscles: ['Lower abs', 'Hip flexors', 'Grip'],
        qualities: ['Visible abs', 'Core control', 'Knee drive'],
      },
      why: 'Visible abs are a stated goal, and the lower abs are built by raising the legs against gravity, not by crunches. Bonus: hip flexor strength drives the knee punch in your sprint and jump.',
      mistakes: [
        'Swinging into momentum reps.',
        'Lifting with the legs only, the pelvis must curl, or the abs never fire.',
        'Cutting the lowering phase short: that half is where the muscle is made.',
      ],
      videoQuery: 'hanging leg raise strict form',
      restSec: 90,
    }),

    // ================= TUESDAY. PUSH + SHOULDER HEALTH =================
    E({
      id: 'incline-db-press',
      name: 'Incline DB Press',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      steps: [
        'Set the bench to a 30–45° incline, kick the dumbbells up as you lie back, and pin your shoulder blades back and down into the bench.',
        'Lower the weights with control to your outer chest, elbows about 45° from your body, then press up and slightly in over your upper chest.',
        'Exhale hard as you press and keep the blades pinned all set. Shoulders rolling forward is how pressing starts to hurt.',
      ],
      targets: {
        muscles: ['Upper chest', 'Front delts', 'Triceps'],
        qualities: ['Upper-chest size', 'Pressing strength'],
      },
      why: 'Upper chest is a stated goal of your plan, and it grows from incline volume, which is exactly why this is FIRST every Tuesday, when you are strongest. This is also a core mover: progress it every block.',
      mistakes: [
        'Flattening the incline benefit by flaring elbows straight out.',
        'Bouncing out of the bottom instead of controlling the lowering.',
        'Losing shoulder-blade position, shoulders rolling forward is how pressing starts to hurt.',
      ],
      cue: 'Incline first every week. Control the lowering, press hard.',
      videoId: '8iPEnn-ltC8',
      videoQuery: 'incline dumbbell press upper chest form',
      restSec: 150,
    }),
    E({
      id: 'flat-db-press',
      name: 'Flat DB Press',
      kind: 'lift',
      equipment: 'Dumbbells + bench',
      steps: [
        'Lie flat with feet planted, slight arch, shoulder blades pinned back and down. Dumbbells start over your chest, palms forward.',
        'Lower under control to a full chest stretch, elbows about 45° from your sides, then press up and slightly together to lockout.',
        'Exhale as you press and squeeze the chest at the top. Wrists stacked over elbows, no bouncing out of the bottom.',
      ],
      targets: {
        muscles: ['Chest', 'Front delts', 'Triceps'],
        qualities: ['Pressing strength', 'Chest mass'],
      },
      why: 'The flat press builds the overall chest mass under your incline work. Dumbbells over a bar means each side works alone and your shoulders move freely, more muscle, less joint stress, perfect for a home gym.',
      mistakes: [
        'Elbows flared to 90°, max shoulder stress for no extra chest.',
        'Half-rep lockouts with no top squeeze.',
        'Feet dancing around, plant them and push the floor away.',
      ],
      videoQuery: 'flat dumbbell bench press form',
      restSec: 150,
    }),
    E({
      id: 'floor-press',
      name: 'Close-Grip Floor Press',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Lie on the floor under the bar, knees bent, feet flat. Grip just inside shoulder-width, elbows tucked close to your sides.',
        'Lower under control until your upper arms rest gently on the floor, pause a beat, then press hard from the dead stop to lockout.',
        'No bouncing off the floor and no bridging the hips. Exhale through the press, wrists straight over elbows.',
      ],
      targets: {
        muscles: ['Triceps', 'Chest', 'Front delts'],
        qualities: ['Lockout strength', 'Pressing power from a dead stop'],
      },
      why: 'The floor shortens the range and forces a dead-stop press, pure triceps and pure starting strength, with the shoulders protected. Block 3 rotates it in so your press keeps climbing without beating up the same angle all year.',
      mistakes: [
        'Bouncing the arms off the floor instead of pausing.',
        'Flaring elbows, keep them tucked, this is a triceps lift.',
        'Bridging your hips off the floor.',
      ],
      videoQuery: 'barbell floor press technique',
      restSec: 150,
    }),
    E({
      id: 'standing-ohp',
      name: 'Standing Barbell OHP',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Bar at your collarbones, hands just outside shoulders, elbows slightly in front of the bar. Squeeze glutes, brace abs HARD.',
        'Press in a straight line, chin back to let the bar pass, then push your head through so the bar locks out stacked over your spine.',
        'No lean-back and no leg drive, if you must dip to press it, it’s too heavy. Lower under control and re-brace each rep.',
      ],
      targets: {
        muscles: ['Shoulders', 'Triceps', 'Upper chest', 'Core'],
        qualities: ['Overhead strength', 'Wide-shoulder mass', 'Total-body stiffness'],
      },
      why: 'Wide, capped shoulders are on your goal list, and the standing press is their heaviest builder, plus it is a core mover you progress all year. Standing (not seated) makes your trunk transfer force, the same job it does in a jump.',
      mistakes: [
        'Leaning way back and turning it into an incline press, squeeze the glutes to stop this.',
        'Pressing around your face in a curve instead of moving your head.',
        'No leg drive allowed, if you need to dip and push, the weight is too heavy.',
      ],
      videoId: 'GlyABLsPk-Q',
      videoQuery: 'standing barbell overhead press form',
      restSec: 150,
    }),
    E({
      id: 'lateral-raise',
      name: 'Lateral Raise',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Stand tall, dumbbells at your sides, slight bend in the elbows, leaning forward a hair.',
        'Raise the weights out to shoulder height, leading with the ELBOWS, pinkies slightly high, then lower over 2–3 slow seconds.',
        'The slow lowering is half the set. Stay strict, if you have to swing, the weight is too heavy.',
      ],
      targets: {
        muscles: ['Side delts'],
        qualities: ['Shoulder width', 'The V-taper look'],
      },
      why: 'Shoulder WIDTH is mostly the side delt, and the side delt only really grows from raises, pressing barely touches it. High reps, light weight, twice a week: this is what makes shoulders read wide from across the court.',
      mistakes: [
        'Swinging heavy dumbbells with the traps doing everything.',
        'Raising with straight vertical arms, soft elbows, lead with them.',
        'Dropping the weights on the way down.',
      ],
      videoQuery: 'lateral raise proper form side delts',
      restSec: 90,
    }),
    E({
      id: 'close-grip-press',
      name: 'Close-Grip Bench / Floor Press',
      kind: 'lift',
      equipment: 'Barbell + bench',
      steps: [
        'Grip the bar just inside shoulder-width, not hands-touching narrow. Unrack with wrists stacked, elbows tucked near your sides.',
        'Lower under control to your lower chest, forearms staying vertical, then press up to a hard triceps lockout.',
        'Keep the elbows tucked, flaring turns it back into a chest press. Exhale on the press, never bounce off the chest.',
      ],
      targets: {
        muscles: ['Triceps', 'Chest', 'Front delts'],
        qualities: ['Arm size (the 16″ goal)', 'Pressing lockout'],
      },
      why: 'Two-thirds of arm size is triceps. The close grip lets you overload them with real weight instead of only isolation moves, feeding the 16-inch arm target while backing up every press you do.',
      mistakes: [
        'Grip so narrow the wrists hurt, inside shoulder-width is close enough.',
        'Elbows flaring, which turns it back into a chest press.',
        'Bouncing off the chest.',
      ],
      videoQuery: 'close grip bench press triceps form',
      restSec: 120,
    }),
    E({
      id: 'overhead-tricep-extension',
      name: 'Overhead Tricep Extension',
      kind: 'lift',
      equipment: '1 dumbbell or EZ bar',
      steps: [
        'Stand or sit tall holding one dumbbell overhead, both hands cupped under the top plate, elbows pointing forward by your head.',
        'Lower the weight slowly behind your head to a deep triceps stretch, then extend to straight arms without moving the upper arms.',
        'The bottom stretch is the growth, never cut it short. Ribs down and abs on so the lower back doesn’t arch.',
      ],
      targets: {
        muscles: ['Triceps (long head)'],
        qualities: ['Arm size', 'Elbow health under load'],
      },
      why: 'The long head of the triceps, the big one that makes arms look thick from the side, only gets fully stretched overhead. This is the isolation piece the close-grip pressing doesn’t cover.',
      mistakes: [
        'Elbows drifting out wide as you fatigue.',
        'Short pump reps in the top half, the stretch at the bottom is the growth.',
        'Arching the lower back to fake range.',
      ],
      videoQuery: 'overhead dumbbell tricep extension form',
      restSec: 90,
    }),
    E({
      id: 'prone-y-raise',
      name: 'Prone Y Raise',
      kind: 'lift',
      equipment: 'Light dumbbells + incline bench',
      steps: [
        'Lie face down on an incline bench, arms hanging straight down with light dumbbells, thumbs turned UP toward the ceiling.',
        'Raise both arms up-and-out into a Y, squeezing between the shoulder blades, pause a second, then lower slow and controlled.',
        'Stay LIGHT, 5s and 10s do the job. If your shoulders shrug toward your ears, go lighter and slower.',
      ],
      targets: {
        muscles: ['Lower traps', 'Rear delts', 'Rotator cuff'],
        qualities: ['Shoulder health', 'Overhead stability'],
      },
      why: 'You press hard twice a week and throw dunks on Saturday, this is the insurance. Strong lower traps keep the shoulder blade rotating properly overhead, which is what keeps pressing pain-free all year.',
      mistakes: [
        'Going heavy and shrugging with the upper traps.',
        'Thumbs down, that position pinches the shoulder.',
        'Rushing. Slow and controlled is the entire point.',
      ],
      cue: 'Slow and controlled, feel the rear delts and lower traps.',
      videoQuery: 'prone Y raise incline bench lower trap',
      restSec: 60,
    }),

    // ================= WEDNESDAY. LOWER STRENGTH + HYPERTROPHY =================
    E({
      id: 'front-squat',
      name: 'DB / Barbell Front Squat',
      kind: 'lift',
      equipment: 'Dumbbells or barbell',
      steps: [
        'Rack the bar on your front delts, fingertips under it, elbows driven HIGH (dumbbells: one on each shoulder). Big breath, brace hard.',
        'Squat straight down, torso as vertical as possible, to below parallel with heels down, then drive up through mid-foot.',
        'Elbows stay high all rep or the weight tips you forward. Exhale over the top, re-brace, and never grind to failure.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Upper back', 'Core'],
        qualities: ['Heavy leg strength', 'Vertical force', 'Thick legs'],
      },
      why: 'Wednesday is the heavy version of the squat pattern, slower and heavier than Monday, building the thick legs and raw force your jumps convert into height. Placed two days before Saturday so your legs arrive fresh for sprints.',
      mistakes: [
        'Elbows dropping and the bar rolling forward.',
        'Cutting depth as the load climbs.',
        'Grinding to failure, heavy, not reckless; a rep or two always left in the tank.',
      ],
      videoId: '0ect9ETE6t0',
      videoQuery: 'front squat technique barbell dumbbell',
      restSec: 180,
    }),
    E({
      id: 'hip-thrust',
      name: 'Barbell Hip Thrust',
      kind: 'lift',
      equipment: 'Barbell + bench',
      steps: [
        'Upper back on the bench edge, bar padded across your hips, feet flat hip-width so your shins are vertical at the top.',
        'Drive through the heels and squeeze the glutes until your body is a flat table, hold one full second, then lower under control.',
        'Chin tucked, ribs down: squeeze the glutes flat, never arch the lower back to finish the rep.',
      ],
      targets: {
        muscles: ['Glutes', 'Hamstrings'],
        qualities: ['Hip extension power', 'Vertical jump', 'Sprint drive'],
      },
      why: 'Huge for vertical and glute size, the PDF says it straight. Jumping and sprinting are violent hip extension, and nothing loads hip extension like a heavy thrust. This is a core mover: keep adding plates all year.',
      mistakes: [
        'Overarching the back at the top instead of squeezing the glutes flat.',
        'Feet too far out (hamstring cramp) or too close (all quads).',
        'Bouncing fast half reps, own the one-second squeeze at the top.',
      ],
      cue: 'Shoulders on the bench, bar padded across the hips. Squeeze, don’t arch.',
      videoId: 'LM8XHLYJoYs',
      videoQuery: 'barbell hip thrust setup form bench',
      restSec: 150,
    }),
    E({
      id: 'single-leg-rdl',
      name: 'Single-Leg RDL',
      kind: 'lift',
      equipment: 'Dumbbell',
      perSide: true,
      steps: [
        'Stand on one leg with a soft knee, dumbbell in the OPPOSITE hand.',
        'Hinge at the hip, free leg drifting straight back, until the hamstring pulls hard near mid-shin, then drive the hips forward to stand.',
        'Hips stay square to the floor, back flat, range ends where the hamstring ends. Slow is strong, all reps one side then switch.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Ankle/hip stabilizers'],
        qualities: ['Single-leg hinge', 'Plant-leg strength', 'Balance'],
      },
      why: 'Your one-foot jump plants on a single loaded hamstring, this is that moment, slowed down and strengthened. It also bulletproofs the hamstring for max-velocity sprint day.',
      mistakes: [
        'Hips rotating open toward the free leg.',
        'Rounding the back to touch the floor, range ends where the hamstring ends.',
        'Rushing the balance. Slow is strong here.',
      ],
      videoId: 'gz9l8UA_KXs',
      videoQuery: 'single leg romanian deadlift dumbbell form',
      restSec: 120,
    }),
    E({
      id: 'good-morning',
      name: 'Good Morning',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Bar on your upper back like a squat, hands squeezing tight. Feet hip-width, soft knees fixed in place.',
        'Push your hips straight BACK, folding until your torso nears 45° or the hamstrings stop you, then drive the hips forward to stand tall.',
        'Back stays table-flat and the weight stays light, this lift rewards patience. No extra knee bend creeping in.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Spinal erectors'],
        qualities: ['Hip hinge strength', 'Posterior chain armor'],
      },
      why: 'Block 2’s hamstring rotation. Same hinge engine as the RDL but loaded on your back, which makes the erectors work overtime, carryover to every sprint, jump, and pickup-game rebound landing.',
      mistakes: [
        'Bending the knees into a squat as it gets heavy.',
        'Any rounding of the lower back, this lift punishes ego, keep it light and perfect.',
        'Going too deep; stop where the hamstrings stop you.',
      ],
      videoQuery: 'barbell good morning exercise form',
      restSec: 150,
    }),
    E({
      id: 'slider-leg-curl',
      name: 'Slider Leg Curl',
      kind: 'lift',
      equipment: 'Floor + towel/sliders',
      steps: [
        'Lie on your back, heels on towels or sliders, knees bent, hips bridged UP.',
        'Slide your heels away until the legs are nearly straight, then drag them back with the hamstrings, hips staying tall the whole time.',
        'Slow out, strong in, and never let the hips sag. Too hard? Slide out only as far as you can control.',
      ],
      targets: {
        muscles: ['Hamstrings (knee-flexion role)', 'Glutes'],
        qualities: ['Hamstring resilience', 'Sprint-speed protection'],
      },
      why: 'Hamstrings do two jobs, hip hinge and knee flexion, and sprint injuries live in the second one. Block 3 adds this to cover the job your RDLs don’t, right when your sprint speeds are at their highest of the year.',
      mistakes: [
        'Hips sagging to the floor mid-rep, the bridge is non-negotiable.',
        'Letting the slide out just drop instead of resisting it.',
        'Yanking with the lower back.',
      ],
      videoQuery: 'sliding leg curl towel hamstring exercise',
      restSec: 120,
    }),
    E({
      id: 'seated-calf-raise',
      name: 'Seated / Bent-Knee Calf Raise',
      kind: 'lift',
      equipment: 'Dumbbell + bench',
      perSide: true,
      steps: [
        'Sit on the bench, ball of one foot on a plate or step, a dumbbell standing on that knee.',
        'Let the heel sink to a deep stretch, pause one second, then press up onto the ball of the foot as high as it goes and squeeze.',
        'Slow down, pause, drive up, no bouncing anywhere. Finish the side, then switch.',
      ],
      targets: {
        muscles: ['Soleus (deep calf)'],
        qualities: ['Ankle stiffness', 'Ground-contact snap'],
      },
      why: 'With the knee bent, the deep soleus does the work, the muscle firing during the bent-knee moments of sprinting and jump loading. Block 2 rotates it in so both calf muscles get their turn.',
      mistakes: [
        'Bouncing reps off the stretch reflex.',
        'Too little weight to matter, the soleus is dense and strong; load it.',
        'Partial range at the top.',
      ],
      videoQuery: 'seated calf raise dumbbell soleus',
      restSec: 90,
    }),
    E({
      id: 'double-leg-calf-raise',
      name: 'Double-Leg Heavy Calf Raise',
      kind: 'lift',
      equipment: 'Dumbbells + step',
      steps: [
        'Stand with both forefeet on a step, heels hanging, a heavy dumbbell in each hand.',
        'Sink both heels to a deep one-second stretch, then drive up tall onto the big toes, like jumping without leaving the ground.',
        'Squeeze the top, lower over 2–3 seconds. If the range shrinks to a pulse, the load is too heavy.',
      ],
      targets: {
        muscles: ['Calves (gastroc emphasis)'],
        qualities: ['Heavy ankle strength', 'Takeoff stiffness'],
      },
      why: 'Block 3 trades single-leg reps for pure LOAD. Heavier calves = a stiffer ankle at takeoff, the last link that turns leg force into rim height instead of mushy ground contact.',
      mistakes: [
        'Loading so heavy the range shrinks to a pulse.',
        'Skipping the bottom pause.',
        'Rolling to the outside edge of the foot, finish over the big toe.',
      ],
      videoQuery: 'heavy standing calf raise dumbbells form',
      restSec: 90,
    }),
    E({
      id: 'weighted-situp',
      name: 'Weighted Sit-Up',
      kind: 'core',
      equipment: '1 plate or dumbbell',
      steps: [
        'Lie on your back, knees bent, feet flat or anchored, hugging a plate to your chest.',
        'Exhale and curl up one vertebra at a time to a tall sit, then lower back down slowly over 2–3 seconds, resisting the whole way.',
        'No neck yanking and no fast drops. Treat it like a lift: add weight over the weeks, abs grow with load.',
      ],
      targets: {
        muscles: ['Rectus abdominis (the six-pack)', 'Hip flexors'],
        qualities: ['Visible abs', 'Trunk flexion strength'],
      },
      why: 'Visible abs need two things: a leaner waist (nutrition’s job) and thicker ab muscle (this). Progressive load is what makes abs pop through, treat it like a lift, not a burnout.',
      mistakes: [
        'Pulling on your neck.',
        'Dropping down fast and losing the eccentric half.',
        'Reps so fast the hip flexors take everything.',
      ],
      videoQuery: 'weighted sit up plate form',
      restSec: 90,
    }),
    E({
      id: 'plank-side-plank',
      name: 'Plank + Side Plank',
      kind: 'core',
      equipment: 'Floor',
      steps: [
        'Front plank: forearms down, body one straight line. Side plank: elbow under shoulder, feet stacked, hips lifted tall.',
        'Squeeze glutes and abs HARD and push the floor away so nothing sags. Hold front, then each side, that trio is one set.',
        'Breathe shallow and steady behind the brace, never hold your breath. A hard 30 seconds beats a saggy 90.',
      ],
      targets: {
        muscles: ['Deep core', 'Obliques', 'Shoulder stabilizers'],
        qualities: ['Anti-rotation', 'Trunk stiffness for sprints', 'Waist control'],
      },
      why: 'Sprinting and jumping leak power through a soft trunk. Planks teach the core to lock the ribcage to the pelvis so every pound of leg force arrives at the floor, and the obliques frame a tighter waist.',
      mistakes: [
        'Hips sagging or hiking, one straight line, filmed or mirrored if unsure.',
        'Holding your breath; breathe shallow and steady behind the brace.',
        'Zoning out. Squeeze harder, hold shorter.',
      ],
      videoQuery: 'plank side plank proper form',
      restSec: 60,
    }),

    // ================= THURSDAY. MOBILITY + ACTIVE RECOVERY =================
    E({
      id: 'hip-9090-switch',
      name: '90/90 Hip Switch',
      kind: 'mobility',
      equipment: 'Floor',
      perSide: true,
      steps: [
        'Sit with your front leg bent 90° in front of you and your back leg bent 90° behind, chest tall, both sit bones down.',
        'Rotate both knees together over to the other side so the legs swap roles, pausing tall in each position.',
        'Slow, breathing switches, no forcing or bouncing. Lean your chest over the front shin for extra hip stretch.',
      ],
      targets: {
        muscles: ['Hip rotators', 'Glutes', 'Hip capsule'],
        qualities: ['Hip range for jumps', 'Change-of-direction health'],
      },
      why: 'Your hips take every plant, cut, and landing. Rotational hip range is what lets you load a jump deep and land absorbing force with muscle instead of joint, this keeps that range from shrinking under all the lifting.',
      mistakes: [
        'Slouching through the switches.',
        'Using hands to lift through every rep instead of the hips doing the work.',
        'Bouncing at end range.',
      ],
      videoQuery: '90 90 hip switch mobility drill',
      restSec: 30,
    }),
    E({
      id: 'deep-squat-hold',
      name: 'Deep Squat Hold + Pry',
      kind: 'mobility',
      equipment: 'Bodyweight',
      steps: [
        'Sink into your deepest squat, heels down, feet a bit wider than usual, elbows inside the knees, palms together.',
        'Sit tall in the hole and gently pry the knees outward, shifting side to side to open each ankle and hip.',
        'Breathe slow, each exhale sinks you deeper. Hold something in front if balance fights you.',
      ],
      targets: {
        muscles: ['Hips', 'Ankles', 'Adductors', 'Lower back (decompression)'],
        qualities: ['Squat depth', 'Jump-loading range'],
      },
      why: 'The deep squat is the human resting position your lifting depends on. Owning it keeps Wednesday’s heavy squats deep and safe, and ankle-and-hip range directly raises your jump, per your own plan.',
      mistakes: [
        'Heels floating, elevate them slightly rather than tipping forward.',
        'Rounding into a slump instead of sitting tall in the hole.',
        'Holding your breath; the exhale is what unlocks depth.',
      ],
      videoQuery: 'deep squat hold pry mobility',
      restSec: 30,
    }),
    E({
      id: 'ankle-wall-mobilization',
      name: 'Ankle Wall Mobilization',
      kind: 'mobility',
      equipment: 'Wall',
      perSide: true,
      steps: [
        'Face a wall with your toes about a hand-width away, heel glued down.',
        'Drive the knee straight over the toes to touch the wall (or as close as the ankle allows), pause, then return.',
        'The heel staying down is the only rule, if it peels up the rep counted for nothing. Too easy? Move the foot back an inch.',
      ],
      targets: {
        muscles: ['Ankle joint', 'Calves', 'Achilles'],
        qualities: ['Dorsiflexion', 'Deeper jump load', 'Plant-leg safety'],
      },
      why: 'Ankle range is hidden vertical. A stiff ankle cuts your jump load short and dumps stress into the knee on every plant, your plan calls this out directly: ankle and hip range raise the jump and protect the plant leg.',
      mistakes: [
        'Heel peeling up, that rep counted for nothing.',
        'Knee diving inward; track it over the second toe.',
        'Rushing through without the pause at end range.',
      ],
      videoQuery: 'ankle dorsiflexion wall mobilization knee to wall',
      restSec: 30,
    }),
    E({
      id: 'couch-stretch',
      name: 'Couch Stretch',
      kind: 'mobility',
      equipment: 'Wall / couch',
      perSide: true,
      steps: [
        'Kneel with your back foot up a wall or couch, back knee tucked into the corner, front foot flat in a lunge.',
        'Squeeze the back glute and tuck your pelvis so the stretch lands on the front of the hip, then raise your torso taller to deepen it.',
        'Long calm holds with steady breathing, intense but never sharp. Don’t arch the lower back to fake depth.',
      ],
      targets: {
        muscles: ['Hip flexors', 'Quads'],
        qualities: ['Hip extension range', 'Stride length', 'Sprint mechanics'],
      },
      why: 'Sitting and lifting shorten the hip flexors, and short hip flexors cap your sprint stride and steal hip extension from every jump. This opens the front of the hip so your glutes can finish what they start.',
      mistakes: [
        'Arching the lower back instead of tucking the pelvis, the stretch must live in the hip, not the spine.',
        'Skipping the glute squeeze that makes it work.',
        'Forcing depth on day one.',
      ],
      videoQuery: 'couch stretch hip flexor correct form',
      restSec: 30,
    }),
    E({
      id: 't-spine-opener',
      name: 'T-Spine Opener',
      kind: 'mobility',
      equipment: 'Floor',
      perSide: true,
      steps: [
        'Lie on your side, knees pulled up to hip height, arms stacked straight in front of you.',
        'Keeping the knees glued together, sweep the top arm up and over to the other side, chest opening to the ceiling, then return.',
        'Follow the hand with your eyes and exhale into the twist. No whipping the arm with momentum.',
      ],
      targets: {
        muscles: ['Thoracic spine', 'Chest', 'Shoulders'],
        qualities: ['Overhead range', 'Pressing posture', 'Rotation'],
      },
      why: 'Overhead pressing and heavy rows need a mid-back that extends and rotates. A stiff t-spine makes the shoulder and lower back pay the difference, this keeps Tuesday’s OHP clean and pain-free.',
      mistakes: [
        'Top knee lifting off, that turns spine rotation into hip rotation.',
        'Whipping the arm over with momentum.',
        'Shallow breathing; the exhale opens the twist.',
      ],
      videoQuery: 'open book t-spine rotation stretch',
      restSec: 30,
    }),
    E({
      id: 'dead-hang',
      name: 'Dead Hang',
      kind: 'mobility',
      equipment: 'Pull-up bar',
      steps: [
        'Grip the bar overhand, shoulder-width, and hang with straight arms, body quiet, no swinging.',
        'Let the shoulders shrug up by your ears and the spine lengthen, you’re decompressing, not pulling.',
        'Breathe slow and relax into the hold, a death grip cuts it short. Build toward the full time, grip gets trained for free.',
      ],
      targets: {
        muscles: ['Lats', 'Grip', 'Shoulders', 'Spine (decompression)'],
        qualities: ['Overhead range', 'Grip endurance', 'Spinal recovery'],
      },
      why: 'Your plan says it plainly: the dead hang decompresses your spine after a week of loading, and it quietly builds the grip that pull-ups, carries, and rim-hangs all draw on.',
      mistakes: [
        'Actively pulling the shoulders down the whole time, let them lengthen for the decompression benefit.',
        'Death-gripping so hard you cut the hold short; relax into it.',
        'Swinging.',
      ],
      videoQuery: 'dead hang benefits proper technique',
      restSec: 45,
    }),
    E({
      id: 'easy-walk',
      name: 'Easy Walk',
      kind: 'cardio',
      equipment: 'Outside',
      steps: [
        'Head out the door with your arms relaxed.',
        'Walk 20–30 minutes at a conversational pace, you could talk the whole way. Sunlight is a bonus for sleep tonight.',
        'Breathe through your nose if you can and keep it genuinely easy. This is recovery, not a workout.',
      ],
      targets: {
        muscles: ['Whole body (low intensity)'],
        qualities: ['Recovery', 'Blood flow', 'Daily steps'],
      },
      why: 'Easy movement clears the sludge from Wednesday’s heavy legs without adding any fatigue, so Friday and Saturday get your best. Steps are the cheapest recovery tool you own.',
      mistakes: [
        'Speed-walking it into cardio. Keep it genuinely easy.',
        'Skipping it because it feels too small to matter. It matters.',
      ],
      videoQuery: 'zone 1 recovery walk benefits',
      restSec: 0,
    }),

    // ================= FRIDAY. PULL + GRIP + SHOULDER HEALTH =================
    E({
      id: 'pull-up',
      name: 'Pull-Ups (wide grip)',
      kind: 'lift',
      equipment: 'Pull-up bar',
      steps: [
        'Grip the bar wider than shoulders, palms away, hang at straight arms, and pull the shoulder blades down and back before the arms bend.',
        'Drive the elbows down toward your hips until your chin clears the bar, then lower all the way back to a dead hang.',
        'No kipping and no half reps, every rep starts from straight arms. Stop when form breaks and log the honest number.',
      ],
      targets: {
        muscles: ['Lats', 'Upper back', 'Biceps', 'Grip'],
        qualities: ['Lat WIDTH', 'The V-taper', 'Pulling strength'],
      },
      why: 'Wide lats are a stated goal and this is where lat width gets built, the PDF’s words. It is a core mover: same exercise all year, and the climbing rep number becomes one of your clearest progress charts.',
      mistakes: [
        'Half reps that skip the dead-hang bottom, those build ego, not lats.',
        'Kipping/swinging through reps.',
        'Leading with a chin-poke instead of driving the elbows down.',
      ],
      videoId: 'rmdn5X_KLkY',
      videoQuery: 'wide grip pull up form lats',
      restSec: 150,
    }),
    E({
      id: 'barbell-row',
      name: 'Barbell Row',
      kind: 'lift',
      equipment: 'Barbell',
      steps: [
        'Hinge to about 45° or lower, bar hanging at arm’s length, back flat, knees soft, brace on.',
        'Pull the bar to your lower ribs, elbows driving back and blades squeezing together, then lower under control to a full stretch.',
        'The torso stays still, if you heave upright to move it, strip weight. Don’t let the chest drop as fatigue builds.',
      ],
      targets: {
        muscles: ['Lats', 'Mid-back', 'Rear delts', 'Biceps', 'Lower back (isometric)'],
        qualities: ['Back thickness', 'Pulling strength'],
      },
      why: 'Pull-ups build width; rows build the thickness behind it. A big flat pull also balances all your pressing so the shoulders stay healthy and the frame reads powerful from the side.',
      mistakes: [
        'Standing up 30° every rep to cheat the weight up.',
        'Pulling to the chest with flared elbows, target the lower ribs.',
        'Rounding the lower back as fatigue sets in.',
      ],
      videoId: 'FWJR5Ve8bnQ',
      videoQuery: 'barbell bent over row proper form',
      restSec: 150,
    }),
    E({
      id: 'db-pullover',
      name: 'DB Pullover',
      kind: 'lift',
      equipment: 'Dumbbell + bench',
      steps: [
        'Lie on the bench, feet planted, one dumbbell held in both hands over your chest, elbows slightly bent and locked at that angle.',
        'Lower the weight in an arc back over your head to a deep lat and chest stretch, then pull it back over your chest in the same arc.',
        'Ribs stay DOWN, slow arc back, strong arc up. The stretch is the growth signal, don’t go so heavy it gets cut short.',
      ],
      targets: {
        muscles: ['Lats (long stretch)', 'Chest', 'Serratus', 'Triceps (long head)'],
        qualities: ['Lat width', 'Ribcage expansion look', 'Overhead range'],
      },
      why: 'The pullover loads the lats at their longest, the stretch position that pull-ups and rows never reach. Week A’s tool for wider lats and a fuller upper body, straight off your goal list.',
      mistakes: [
        'Bending and extending the elbows, that turns it into a triceps extension.',
        'Flaring the ribs and arching the back to fake range.',
        'Going so heavy the stretch gets cut short.',
      ],
      videoQuery: 'dumbbell pullover lats form bench',
      restSec: 120,
    }),
    E({
      id: 'one-arm-db-row',
      name: 'One-Arm DB Row',
      kind: 'lift',
      equipment: 'Dumbbell + bench',
      perSide: true,
      steps: [
        'Left knee and hand on the bench, right foot planted wide, back flat like a table, dumbbell hanging in the right hand.',
        'Pull the elbow up and BACK toward your hip until the weight touches your side, then lower to a full stretch, blade sliding forward.',
        'No yanking with rotation, the torso stays square to the floor. Squeeze the lat at the top, then switch sides.',
      ],
      targets: {
        muscles: ['Lats', 'Mid-back', 'Biceps', 'Grip'],
        qualities: ['Unilateral pull strength', 'Lat width + thickness'],
      },
      why: 'One side at a time means full focus, a longer range than the barbell allows, and no lower-back limit, so the lats get direct heavy work. Week B’s rotation partner to the pullover.',
      mistakes: [
        'Yanking with rotation, the torso stays square to the floor.',
        'Pulling the elbow out wide, turning it into a rear-delt row.',
        'Short top-half pumps with no bottom stretch.',
      ],
      videoQuery: 'one arm dumbbell row form',
      restSec: 120,
    }),
    E({
      id: 'chest-supported-row',
      name: 'Chest-Supported Row',
      kind: 'lift',
      equipment: 'Dumbbells + incline bench',
      steps: [
        'Set the bench to about 30–45° and lie chest-down on it, dumbbells hanging below at a full stretch.',
        'Row both elbows back toward your hips, squeezing the blades together with a pause, then lower slow to the full hang.',
        'Chest stays on the pad the whole set, the bench deletes cheating. Never let the range shrink as it gets hard.',
      ],
      targets: {
        muscles: ['Mid-back', 'Lats', 'Rear delts', 'Biceps'],
        qualities: ['Strict pulling volume', 'Back detail', 'Spine-friendly rowing'],
      },
      why: 'Block 3’s row: the bench deletes momentum and spares the lower back late in the training year, so the upper back gets every rep. Strictness is the progression here, not just load.',
      mistakes: [
        'Lifting the chest off the pad to heave.',
        'Range shrinking as the set gets hard.',
        'Shrugging into the neck instead of pulling to the hips.',
      ],
      videoQuery: 'chest supported dumbbell row incline bench',
      restSec: 120,
    }),
    E({
      id: 'rear-delt-raise',
      name: 'Rear Delt Raise (slow tempo)',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Hinge to a near-flat torso, light dumbbells hanging, soft elbows.',
        'Raise the weights out to shoulder line, leading with the elbows, thumbs slightly down, then lower on a strict 3-second count.',
        'The slow lowering IS the exercise. Stay light and feel the back of the shoulder work, not the traps.',
      ],
      targets: {
        muscles: ['Rear delts', 'Mid traps'],
        qualities: ['3-D shoulder look', 'Shoulder health', 'Posture'],
      },
      why: 'The 3-second lowering doubles as your shoulder-health work, the PDF builds it in on purpose. Rear delts balance all your pressing, finish the wide-shoulder look from behind, and keep the joint centered.',
      mistakes: [
        'Going heavy and swinging, the rear delt is small; let it work alone.',
        'Rushing the 3-second eccentric. That IS the set.',
        'Standing too upright, which turns it into a lateral raise.',
      ],
      cue: '3-second lowering, every rep. Doubles as shoulder health.',
      videoQuery: 'bent over rear delt raise slow eccentric',
      restSec: 90,
    }),
    E({
      id: 'ez-bar-curl',
      name: 'EZ Bar Curl',
      kind: 'lift',
      equipment: 'EZ bar',
      steps: [
        'Grip the EZ bar on the angled grips, arms hanging, elbows pinned to your sides.',
        'Curl the bar up in an arc, squeeze the biceps at the top, then lower on a 2–3 count all the way to straight arms.',
        'No hip bump, no lean-back, no elbows drifting forward. Strip weight before you strip form.',
      ],
      targets: {
        muscles: ['Biceps', 'Forearms'],
        qualities: ['Arm size (16″ goal)', 'Elbow-friendly curling'],
      },
      why: 'The EZ bar’s angle spares your wrists while letting you load the biceps heaviest, the base builder for the 16-inch arm target. Curls also show up Saturday because arms recover fast and twice-a-week arms grow.',
      mistakes: [
        'Elbows drifting forward, turning it into a front raise.',
        'Half-rep bottom, full extension is where the growth range lives.',
        'Swinging with the hips on the last reps.',
      ],
      videoQuery: 'ez bar curl proper form biceps',
      restSec: 90,
    }),
    E({
      id: 'incline-db-curl',
      name: 'Incline DB Curl',
      kind: 'lift',
      equipment: 'Dumbbells + incline bench',
      steps: [
        'Set the bench to about 45–60° and lie back, arms hanging straight down behind your body line, palms forward.',
        'Curl both dumbbells up without the elbows creeping forward, squeeze at the top, then lower slowly to that deep hanging stretch.',
        'The bottom stretch is the point, never shorten it. Go lighter than your EZ curl weight, that’s correct, not weak.',
      ],
      targets: {
        muscles: ['Biceps (long head, stretched)'],
        qualities: ['Arm size', 'Peak development'],
      },
      why: 'The incline puts the biceps under load at full stretch, the position research keeps showing grows muscle fastest. Block 2 swaps it in so the arms get a new stimulus without new equipment.',
      mistakes: [
        'Shoulders rolling forward off the bench to shorten the stretch.',
        'Turning it into a hammer curl when it burns, keep palms up.',
        'Bouncing out of the bottom.',
      ],
      videoQuery: 'incline dumbbell curl stretch form',
      restSec: 90,
    }),
    E({
      id: 'hammer-curl',
      name: 'Hammer Curl',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Stand tall, dumbbells at your sides, palms facing each other, and keep that neutral grip the whole set.',
        'Curl up with elbows pinned, like swinging a hammer, squeeze at the top, then lower under control to straight arms.',
        'No rocking the torso and no racing the lowering. This is your strongest curl grip, load it accordingly.',
      ],
      targets: {
        muscles: ['Brachialis', 'Biceps', 'Forearms (brachioradialis)'],
        qualities: ['Arm THICKNESS', 'Grip strength'],
      },
      why: 'The brachialis sits under the biceps, grow it and the whole arm gets wider from every angle. The neutral grip also builds the forearms that your pull-ups, carries, and rim grabs run on.',
      mistakes: [
        'Rocking the torso to swing the weight up.',
        'Elbows flaring away from the body.',
        'Racing through the lowering.',
      ],
      videoQuery: 'hammer curl proper form',
      restSec: 90,
    }),
    E({
      id: 'farmer-carry',
      name: 'Farmer Carry',
      kind: 'carry',
      equipment: 'Loadable dumbbells',
      steps: [
        'Deadlift a heavy dumbbell up in each hand with a flat back, then stand TALL: ribs down, shoulders back, crush grip.',
        'Walk with short, quick, controlled steps for the prescribed time, no leaning, no shuffling collapse.',
        'Posture is the exercise, breathe steady behind a braced core. Set the weights down with a flat back.',
      ],
      targets: {
        muscles: ['Grip/forearms', 'Traps', 'Core', 'Whole body'],
        qualities: ['Grip strength for dunking', 'Trunk stability', 'Work capacity'],
      },
      why: 'Straight from the PDF: carries build the grip strength for dunking and general athleticism. Hanging on the rim, ripping rebounds, heavy RDLs, all grip-limited. Carries fix that while hammering the core.',
      mistakes: [
        'Weights too light to threaten your grip, it should be a fight by the end.',
        'Leaning back or shrugging up into the ears.',
        'Long lazy strides that swing the bells.',
      ],
      videoQuery: 'farmer carry walk proper form',
      restSec: 120,
    }),
    E({
      id: 'towel-hang',
      name: 'Towel Hang',
      kind: 'carry',
      equipment: 'Towel + pull-up bar',
      steps: [
        'Drape a towel over the pull-up bar and grab a handful with each hand.',
        'Hang with straight arms, feet off the floor, body quiet, and CRUSH the towel for max honest time.',
        'Breathe steady and fight for the hold instead of regripping, log the seconds. One towel per hand if it gets easy.',
      ],
      targets: {
        muscles: ['Grip (crush + support)', 'Forearms', 'Lats'],
        qualities: ['Rim-hang grip', 'Forearm size', 'Ball security'],
      },
      why: 'The towel’s thickness turns a hang into a max-grip event, the closest thing in your gym to hanging on a rim. Grip strength is the unglamorous piece of dunking your plan refuses to skip.',
      mistakes: [
        'Regripping constantly instead of fighting for the hold.',
        'Swinging to pass the time, quiet body, working hands.',
        'Quitting at discomfort rather than actual failure. Log real maxes.',
      ],
      videoQuery: 'towel hang grip training',
      restSec: 120,
    }),

    // ================= SATURDAY. MAX SPEED + ONE-FOOT REACTIVE =================
    E({
      id: 'dynamic-warmup',
      name: 'Dynamic Warm-Up',
      kind: 'warmup',
      equipment: 'Bodyweight',
      steps: [
        'Start with 2–3 minutes of easy jogging or skipping to raise your temperature.',
        'Move through leg swings, walking lunges with a twist, high knees, butt kicks, and A-skips, about 20 yards each.',
        'Finish with 2–3 build-up runs from 60% up to 90%. End feeling fast, loose, and slightly buzzed, never tired.',
      ],
      targets: {
        muscles: ['Whole body'],
        qualities: ['Sprint readiness', 'Injury prevention'],
      },
      why: 'Max-velocity sprinting on cold hamstrings is how pulls happen. Eight minutes here is the price of admission for the fastest running of your week, never skip it, never rush it.',
      mistakes: [
        'Static stretching instead of moving, save long holds for after.',
        'Turning the warm-up into a workout.',
        'Skipping the build-up runs and going 0-to-max on rep one.',
      ],
      videoQuery: 'dynamic warm up sprinting routine',
      restSec: 0,
    }),
    E({
      id: 'max-velocity-sprint',
      name: 'Max-Velocity Sprint (30–40 yd)',
      kind: 'sprint',
      equipment: 'Field / street',
      steps: [
        'Mark 30–40 yards and build up smoothly over the first 10–15, posture rising as you go.',
        'Hit TOP SPEED through the middle, tall with high knees, striking under your hips, then ease off gradually, never slam the brakes.',
        'Stay loose in the face and hands, speed comes from relaxed max effort. Full walk-back rest, stop the moment you feel slower.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Hip flexors', 'Calves'],
        qualities: ['Top-end speed', 'Elastic power', 'The back half of your sprint'],
      },
      why: 'Top speed lives here, your plan’s words. Max-velocity work builds the part of your sprint AFTER you’re moving, and it’s the single most potent stimulus in athletics. It must be done fresh, which is exactly why it leads Saturday.',
      mistakes: [
        'Straining and gritting, speed comes from relaxation at max effort.',
        'Short rest turning speed work into conditioning.',
        'Sprinting through fatigue: stop the moment you feel slower.',
      ],
      cue: 'TRUE max effort. Full recovery. Never tired. Stop when speed drops.',
      videoQuery: 'max velocity sprint mechanics top speed',
      restSec: 240,
    }),
    E({
      id: 'flying-sprint',
      name: 'Flying Sprint (10 yd run-in, 20 yd max)',
      kind: 'sprint',
      equipment: 'Field / street',
      steps: [
        'Mark a 10-yard build-in zone and a 20-yard fly zone.',
        'Accelerate gradually to about 80% by the line, then EXPLODE to your absolute fastest running through the fly zone and coast down long.',
        'Stay tall and relaxed, jaw and hands loose. Full rest between reps, three great flys beat six mediocre ones.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Calves'],
        qualities: ['Absolute top speed', 'Stride frequency', 'Elastic return'],
      },
      why: 'The run-in removes the slow start so every fly yard happens at max velocity, more top-speed exposure per rep than any other drill. This is where your fastest running gets faster.',
      mistakes: [
        'Sprinting the build-in and arriving at the fly zone already fading.',
        'Pressing/forcing in the fly, think “fast and loose”, not “hard”.',
        'Doing extra reps while slowing. Three great flys beat six mediocre ones.',
      ],
      cue: 'Gradual run-in, then explode, your fastest running.',
      videoQuery: 'flying sprints top speed drill',
      restSec: 240,
    }),
    E({
      id: 'pogo-hop',
      name: 'Pogo Hops (stiff ankle)',
      kind: 'jump',
      equipment: 'Floor',
      steps: [
        'Stand tall, hands relaxed, legs nearly straight, knees soft but NOT bending for power.',
        'Bounce off the balls of your feet like a pogo stick, ankles doing everything, ground contact as short as possible.',
        'Height comes from ankle snap, not squatting. Crisp rhythm, and if your heels start slapping down, rest.',
      ],
      targets: {
        muscles: ['Calves', 'Achilles tendon', 'Feet'],
        qualities: ['Tendon stiffness', 'Elastic return', 'One-foot jump spring'],
      },
      why: 'Your one-foot jump runs on the same elastic spring as sprinting, and pogos build exactly that: tendon stiffness. The PDF names them the tool for it. Stiffer tendons = the ground gives your jump back for free.',
      mistakes: [
        'Bending the knees into little squat jumps, that’s a different exercise.',
        'Long mushy ground contacts. Short and springy or stop.',
        'Landing on flat feet / heels.',
      ],
      videoQuery: 'pogo hops plyometric ankle stiffness',
      restSec: 120,
    }),
    E({
      id: 'approach-jump',
      name: 'Penultimate-Step Approach Jump',
      kind: 'jump',
      equipment: 'Court / hoop',
      steps: [
        'Take a 3–5 step build-up approach at about 70–80% speed.',
        'Second-to-last step LONG and LOW to drop your hips, then a short quick last step, plant, and fire up off that leg, knee and arms punching.',
        'The long-low step is everything, staying upright kills the jump. Land soft on two feet and fully reset each rep.',
      ],
      targets: {
        muscles: ['Plant-leg hamstrings/glutes', 'Calves', 'Hip flexors'],
        qualities: ['One-foot vertical', 'Speed-to-height conversion', 'Approach rhythm'],
      },
      why: 'Your plan calls the penultimate step THE single most important piece of the one-foot jump. Most converting jumpers stay too upright and lose all their height, the long-low second-to-last step is the fix, and it needs reps as much as strength.',
      mistakes: [
        'Staying upright through the plant, no hip drop, no height. The #1 error.',
        'Slowing down into the jump instead of converting speed through it.',
        'A long, slow last step that kills the spring. Penultimate long, last step SHORT.',
      ],
      cue: 'Lower the hips on the second-to-last step. Fire off one foot, knee UP.',
      videoId: 'cvhNlIEZvS4',
      videoQuery: 'penultimate step single leg jump technique',
      restSec: 180,
    }),
    E({
      id: 'dunk-attempt',
      name: 'One-Foot Max Vert / Dunk Attempts',
      kind: 'jump',
      equipment: 'Hoop',
      steps: [
        'Full approach at game speed, same rhythm you drilled: second-to-last step long and low, last step short and quick.',
        'Plant fast, drive the knee up hard, and reach for your target: rim grab, dunk, or backboard high-point. Land soft on two feet.',
        'Fresh jumps only, stop the moment height drops. Track your best touch height, it’s a weekly progress number.',
      ],
      targets: {
        muscles: ['Full lower body', 'Core'],
        qualities: ['One-foot max vertical', 'Dunk conversion', 'Confidence'],
      },
      why: 'The goal IS consistent dunks, so the plan has you attempt them, fresh, every week. Expect the one-foot jump to feel weaker than two-foot at first: normal, temporary, and for many converted jumpers it eventually wins because you keep all your run-up speed.',
      mistakes: [
        'Grinding attempts while tired, stop the drill the moment height drops.',
        'Changing your approach every rep. Same rhythm, better execution.',
        'Judging the one-foot jump in month one. The elasticity takes weeks, don’t quit early.',
      ],
      cue: 'Stop the moment height drops. Fresh jumps only.',
      videoId: 'SMhtEjgNzMI',
      videoQuery: 'one foot dunk approach training',
      restSec: 180,
    }),

    // ================= CARDIO BACKUP OPTIONS =================
    E({
      id: 'easy-jog',
      name: 'Easy Jog',
      kind: 'cardio',
      equipment: 'Outside',
      steps: [
        'Head out at a conversational pace, you can talk the whole time. That’s the test.',
        'Jog 25–30 minutes with soft landings and quick light steps.',
        'Nose-breathing pace is about right. Legs trashed? Walk instead, zone 2 is a tool, not a test.',
      ],
      targets: {
        muscles: ['Heart', 'Legs (low load)'],
        qualities: ['Aerobic base', 'Recovery between hard days', 'Conditioning floor'],
      },
      why: 'Zone-2 work builds the engine that lets you play full games without fading, without interfering with lifting or jumping. Your no-ball-week replacement when energy is just okay.',
      mistakes: [
        'Creeping into a medium-hard run that adds fatigue but builds nothing specific.',
        'Stacking it on top of a full ball week. It replaces ball, not adds.',
      ],
      videoQuery: 'zone 2 running benefits pace',
      restSec: 0,
    }),
    E({
      id: 'brisk-walk',
      name: 'Brisk Walk (outdoor)',
      kind: 'cardio',
      equipment: 'Outside',
      steps: [
        'Head outside and set a purposeful pace, noticeably faster than a stroll.',
        'Walk 30–45 minutes with your arms swinging. Clear your head while you’re at it.',
        'Breathing elevated but easy conversation still possible. Move with intent, not a phone-scrolling amble.',
      ],
      targets: {
        muscles: ['Legs', 'Heart (light)'],
        qualities: ['Recovery-friendly conditioning', 'Daily steps'],
      },
      why: 'The most recovery-friendly option on tired weeks, real conditioning volume with zero interference to your lifting or jumps. Get outside, bank the steps.',
      mistakes: ['Counting a phone-scrolling amble as brisk. Move with intent.'],
      videoQuery: 'brisk walking workout benefits',
      restSec: 0,
    }),
    E({
      id: 'incline-walk',
      name: 'Incline Walk',
      kind: 'cardio',
      equipment: 'Treadmill (if gym access)',
      steps: [
        'Set the treadmill to a 10–15% incline at 3.0–3.5 mph.',
        'Walk 25–30 minutes steady, pumping your arms.',
        'NO holding the rails, that deletes the work. If it gets easy, raise the incline, not the speed.',
      ],
      targets: {
        muscles: ['Glutes', 'Calves', 'Heart'],
        qualities: ['Zone-2 conditioning', 'Posterior chain endurance'],
      },
      why: 'All the heart-rate benefit of jogging with none of the impact, glutes and calves get quiet extra volume that feeds your jump. Best zone-2 pick when the weather or your joints say no to running.',
      mistakes: ['Holding the rails.', 'Cranking speed instead of incline.'],
      videoQuery: 'incline treadmill walk benefits',
      restSec: 0,
    }),
    E({
      id: 'hill-sprint',
      name: 'Hill Sprints',
      kind: 'cardio',
      equipment: 'Steep hill (30–40 yd)',
      steps: [
        'Find a steep hill with 30–40 yards of runnable slope.',
        'Sprint UP all-out with big knee drive and big arms, leaning into the slope, then walk down slowly, that walk is your full rest.',
        'Do 6–10 sprints and stop when your speed visibly drops. Never jog the downhill, recovery is part of the protocol.',
      ],
      targets: {
        muscles: ['Glutes', 'Hamstrings', 'Calves', 'Heart'],
        qualities: ['Conditioning + power', 'Acceleration strength', 'Fat burn'],
      },
      why: 'The hill forces perfect acceleration mechanics (you literally cannot overstride uphill) while being easier on the hamstrings than flat sprints. Conditioning that also feeds your first step, the highest-value hard-cardio option you have.',
      mistakes: [
        'Jogging the downhill instead of walking, recovery is part of the protocol.',
        'Doing these the day before Monday or Saturday and pre-fatiguing your speed work.',
      ],
      videoQuery: 'hill sprints workout benefits',
      restSec: 0,
    }),
    E({
      id: 'parking-lot-sprint',
      name: 'Parking Lot Sprints',
      kind: 'cardio',
      equipment: 'Any open space',
      steps: [
        'Find any open stretch of space and mark a start point.',
        'Sprint 10–15 seconds truly ALL OUT, then walk for 45–60 seconds of rest. Repeat 6–10 rounds.',
        'Max effort is the whole point, the moment your sprints stop being max, you’re done for the day.',
      ],
      targets: {
        muscles: ['Full lower body', 'Heart'],
        qualities: ['Repeat-sprint conditioning', 'Game-shape'],
      },
      why: 'Basketball is repeated short max efforts with incomplete rest, this is that, distilled. When you can’t play ball, this keeps the exact energy system that games run on.',
      mistakes: [
        'Pacing yourself into 80% “sprints”. Shorter and truly max beats longer and fake.',
        'Skipping the walk-rest and turning it into a jog.',
      ],
      videoQuery: 'sprint interval training 10 seconds',
      restSec: 0,
    }),
    E({
      id: 'stair-run',
      name: 'Stair Runs',
      kind: 'cardio',
      equipment: 'Stadium or building stairs',
      steps: [
        'Find stadium or building stairs and start at the bottom, on the balls of your feet.',
        'Run up hard, every step or every other step, arms driving, then walk down as your rest. 8–12 rounds.',
        'Stop while quality is still high. No flat-footed stomping, and never race the descent, the walk is the recovery.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Calves', 'Heart'],
        qualities: ['Leg-drive conditioning', 'Knee-punch mechanics'],
      },
      why: 'Stairs force the high-knee, ball-of-foot drive of good acceleration and light up the calves that pogo work also targets. A hard-cardio option that quietly rehearses sprint mechanics.',
      mistakes: ['Flat-footed stomping.', 'Racing the descent, walk it, it’s your rest.'],
      videoQuery: 'stair sprints workout',
      restSec: 0,
    }),
    E({
      id: 'circuit-a',
      name: 'Home Circuit A',
      kind: 'cardio',
      equipment: 'None, indoor',
      steps: [
        'Clear a little indoor space, no equipment needed.',
        'One round: 10 burpees chest-to-floor with a jump at the top, 20 brisk jumping jacks, 10 squat jumps landing soft.',
        'Rest 1 minute, repeat 4–5 rounds. Push the pace inside each round, but quality first, no saggy burpees.',
      ],
      targets: {
        muscles: ['Full body'],
        qualities: ['Conditioning', 'High output indoors'],
      },
      why: 'Bad weather, no space to run, still need to sweat, this is the plan’s indoor answer. High-output full-body rounds that keep your engine from idling on a no-ball week.',
      mistakes: [
        'Sloppy burpees with saggy hips, quality first, pace second.',
        'Landing squat jumps stiff-legged.',
      ],
      videoQuery: 'burpee squat jump circuit workout',
      restSec: 60,
    }),
    E({
      id: 'circuit-b',
      name: 'Home Circuit B',
      kind: 'cardio',
      equipment: 'None, indoor',
      steps: [
        'Clear a little indoor floor space.',
        'One round: 30 seconds mountain climbers with hips low, 30 seconds high knees with quick feet and tall chest, 30 seconds rest.',
        'Repeat 8–10 rounds at an even, repeatable pace. Don’t sprint rounds 1–2 and die by round 4.',
      ],
      targets: {
        muscles: ['Core', 'Hip flexors', 'Legs', 'Heart'],
        qualities: ['Endurance', 'Steady conditioning'],
      },
      why: 'The steadier indoor option, builds endurance without the pounding, and the high-knee pattern doubles as sprint-posture practice. Pick this over Circuit A when you want work, not war.',
      mistakes: [
        'Hips piking up on mountain climbers.',
        'Sprinting rounds 1–2 and dying by round 4, even pace across all rounds.',
      ],
      videoQuery: 'mountain climbers high knees interval workout',
      restSec: 60,
    }),
    // ================= GENERATOR CATALOG (bodyweight tier + gym machines) =================
    E({
      id: 'push-up',
      name: 'Push-Up',
      kind: 'lift',
      equipment: 'Floor',
      steps: [
        'Hands just outside shoulder-width, body one straight line from head to heels, glutes and abs squeezed.',
        'Lower your chest to just above the floor, elbows about 45° from your body, then press the floor away hard to straight arms.',
        'The straight line is non-negotiable, no sagging or half reps. Too easy? Slow the lowering to 3 seconds or raise your feet.',
      ],
      targets: {
        muscles: ['Chest', 'Front delts', 'Triceps', 'Core'],
        qualities: ['Pressing strength anywhere', 'Trunk stiffness'],
      },
      why: 'The push-up is the pressing pattern with zero equipment, chest, shoulders, and triceps loaded through a full range while the trunk holds a moving plank. Scaled by tempo, feet height, or hand position, it stays productive from beginner to advanced.',
      mistakes: [
        'Hips sagging or piking, the straight line is non-negotiable.',
        'Half reps that never bring the chest near the floor.',
        'Elbows flared to 90°, which grinds the shoulders.',
      ],
      videoQuery: 'push up proper form full range',
      restSec: 90,
    }),
    E({
      id: 'pike-push-up',
      name: 'Pike Push-Up',
      kind: 'lift',
      equipment: 'Floor',
      steps: [
        'From a push-up position, walk your feet in and push your hips high into an inverted V, head between your arms.',
        'Bend the elbows to lower the top of your head toward the floor between your hands, then press back up to straight arms.',
        'Hips stay high the whole time or it turns back into a push-up. Feet on a bench raises it toward a handstand push-up.',
      ],
      targets: {
        muscles: ['Shoulders', 'Triceps', 'Upper chest'],
        qualities: ['Overhead pressing with no equipment'],
      },
      why: 'Tipping the torso vertical turns a push-up into an overhead press, the shoulders take the load a standing press would give them, with nothing but the floor. The closest bodyweight stand-in for barbell or dumbbell overhead work.',
      mistakes: [
        'Letting the hips drop, which turns it back into a decline push-up.',
        'Bending at the waist more as fatigue builds instead of ending the set.',
        'Craning the neck, the head slides between the arms, not in front of them.',
      ],
      videoQuery: 'pike push up shoulders form',
      restSec: 90,
    }),
    E({
      id: 'inverted-row',
      name: 'Inverted Row',
      kind: 'lift',
      equipment: 'Low bar / sturdy table',
      steps: [
        'Set a bar (or grip a sturdy table edge) around hip height and slide underneath, heels down, body one straight line.',
        'Pull your chest to the bar, driving the elbows back and squeezing the shoulder blades, then lower with control to straight arms.',
        'Squeeze the glutes so the hips never sag. Feet elevated makes it harder, more knee bend makes it easier.',
      ],
      targets: {
        muscles: ['Lats', 'Mid-back', 'Rear delts', 'Biceps'],
        qualities: ['Horizontal pulling anywhere', 'Posture'],
      },
      why: 'The rowing pattern with zero load required, the same back-building pull as a barbell row, scaled by body angle instead of plates. It balances all pressing and keeps shoulders healthy when no weights are available.',
      mistakes: [
        'Hips sagging into a banana shape, squeeze the glutes.',
        'Yanking the chin to the bar instead of pulling the chest.',
        'Cutting the bottom stretch short.',
      ],
      videoQuery: 'inverted row form bodyweight',
      restSec: 90,
    }),
    E({
      id: 'chin-up',
      name: 'Chin-Up',
      kind: 'lift',
      equipment: 'Pull-up bar',
      steps: [
        'Grip the bar shoulder-width, palms facing YOU, and hang at straight arms, shoulder blades set down and back.',
        'Pull your elbows down to your sides until your chin clears the bar, then lower all the way to a dead hang.',
        'No kipping and no half reps, every rep starts from straight arms. Squeeze the biceps and lats for a beat at the top.',
      ],
      targets: {
        muscles: ['Biceps', 'Lats', 'Upper back', 'Grip'],
        qualities: ['Pulling strength', 'Arm size with bodyweight'],
      },
      why: 'The underhand grip shifts a pull-up toward the biceps while the lats still do the heavy lifting, the biggest arm builder that needs nothing but a bar. It pairs with any pressing to keep the shoulders balanced.',
      mistakes: [
        'Kipping or swinging through reps.',
        'Half reps that skip the dead-hang bottom.',
        'Chin poking over by neck extension instead of actual pulling height.',
      ],
      videoQuery: 'chin up proper form biceps',
      restSec: 120,
    }),
    E({
      id: 'split-squat',
      name: 'Split Squat',
      kind: 'lift',
      equipment: 'Bodyweight',
      perSide: true,
      steps: [
        'Take a long stride stance, one foot forward, one back, both pointing ahead. Most of your weight on the FRONT leg.',
        'Drop the back knee straight down toward the floor, front shin near vertical, touch lightly, then drive up through the front heel.',
        'The back foot is a kickstand, not a pusher. All reps one side then switch, and hold dumbbells once it gets easy.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes', 'Adductors'],
        qualities: ['Single-leg strength anywhere', 'Balance'],
      },
      why: 'The single-leg squat pattern with no equipment, each leg learns to carry the body alone, which is how legs actually work in sport and life. It finds and fixes left-right gaps that two-leg squats hide.',
      mistakes: [
        'Stance too short, cramps the front knee and tips you forward.',
        'Pushing off the back foot instead of using it as a kickstand.',
        'Slamming the back knee into the floor.',
      ],
      videoQuery: 'split squat bodyweight form',
      restSec: 90,
    }),
    E({
      id: 'reverse-lunge',
      name: 'Reverse Lunge',
      kind: 'lift',
      equipment: 'Bodyweight',
      perSide: true,
      steps: [
        'Stand tall, feet hip-width, hands ready for balance (add dumbbells to progress).',
        'Step one foot BACKWARD into a long stride, drop the back knee toward the floor, then drive through the front heel to stand.',
        'Torso tall, front shin vertical, push from the front heel, not the back toes. Slow beats wobbly.',
      ],
      targets: {
        muscles: ['Glutes', 'Quads', 'Hamstrings'],
        qualities: ['Knee-friendly single-leg work', 'Hip drive'],
      },
      why: 'Stepping backward keeps the front shin vertical, so the knee takes less stress than a forward lunge while the glutes take more, the friendliest entry to single-leg training, and still heavy-loadable later.',
      mistakes: [
        'Short steps that pitch the torso forward.',
        'Wobbling, slow down; the balance is part of the work.',
        'Pushing off the back toes instead of the front heel.',
      ],
      videoQuery: 'reverse lunge form',
      restSec: 90,
    }),
    E({
      id: 'glute-bridge',
      name: 'Glute Bridge',
      kind: 'lift',
      equipment: 'Floor',
      steps: [
        'Lie on your back, knees bent, feet flat hip-width with heels close to your butt, pelvis slightly tucked.',
        'Drive through the heels and squeeze the glutes to lift your hips into a straight line, hold one second, then lower under control.',
        'Squeeze, don’t arch the lower back. Progress with slow tempo, one leg, or a load across the hips.',
      ],
      targets: {
        muscles: ['Glutes', 'Hamstrings'],
        qualities: ['Hip extension anywhere', 'Posterior chain'],
      },
      why: 'Pure hip extension with nothing but the floor, the same glute-driven pattern as a hip thrust, minus the setup. Strong glutes carry every sprint, jump, and hinge you will ever do.',
      mistakes: [
        'Arching the lower back at the top instead of squeezing the glutes flat.',
        'Feet too far out, the hamstrings cramp and the glutes disappear.',
        'Bouncing reps without the top squeeze.',
      ],
      videoQuery: 'glute bridge proper form',
      restSec: 90,
    }),
    E({
      id: 'hollow-hold',
      name: 'Hollow Hold',
      kind: 'core',
      equipment: 'Floor',
      steps: [
        'Lie on your back and press your lower back into the floor, it stays glued there the whole time.',
        'Lift your shoulders and legs a few inches so your body forms a shallow dish, arms reaching past your hips.',
        'Breathe shallow and steady behind the brace. The set ends the moment your lower back peels off the floor.',
      ],
      targets: {
        muscles: ['Deep abs', 'Hip flexors'],
        qualities: ['Trunk stiffness', 'Gymnast-grade core control'],
      },
      why: 'The hollow position is the body-line every sprint, jump, and press leaks force without, ribs locked to pelvis under tension. It builds the deep core that planks only start.',
      mistakes: [
        'Lower back arching off the floor, the only rule, and the first thing to go.',
        'Holding the breath instead of breathing behind the brace.',
        'Neck strain from pulling the chin to the chest.',
      ],
      videoQuery: 'hollow body hold form',
      restSec: 60,
    }),
    E({
      id: 'dead-bug',
      name: 'Dead Bug',
      kind: 'core',
      equipment: 'Floor',
      steps: [
        'Lie on your back, arms straight up, knees bent 90° over your hips, lower back pressed into the floor.',
        'Slowly lower ONE arm overhead and the OPPOSITE leg toward the floor, stop just above it, return, and switch sides.',
        'Exhale as the limbs travel and keep the back glued down, if it arches, shorten the range. The slowness IS the exercise.',
      ],
      targets: {
        muscles: ['Deep abs', 'Obliques'],
        qualities: ['Anti-extension control', 'Coordination'],
      },
      why: 'The dead bug teaches the trunk to stay rigid while the limbs move, exactly what running, pressing, and carrying demand of it. It builds control that crunches never touch, with zero equipment.',
      mistakes: [
        'Rushing, the slowness IS the exercise.',
        'Lower back popping off the floor as the leg lowers.',
        'Moving same-side arm and leg together.',
      ],
      videoQuery: 'dead bug exercise form',
      restSec: 60,
    }),
    E({
      id: 'db-shoulder-press',
      name: 'DB Shoulder Press',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Standing or seated tall, bring the dumbbells to your shoulders, palms forward, ribs down, abs braced.',
        'Press both bells straight up until your biceps are by your ears, touch gently overhead, then lower with control to the shoulders.',
        'No lower-back arch, that turns it into an incline press. Wrists stacked over elbows the whole rep.',
      ],
      targets: {
        muscles: ['Shoulders', 'Triceps', 'Upper chest'],
        qualities: ['Overhead strength', 'Shoulder mass'],
      },
      why: 'The dumbbell press lets each shoulder move on its own natural path, more muscle recruited, less joint stress than a fixed bar, and it needs no rack. The overhead press is the fastest route to shoulders that look and perform.',
      mistakes: [
        'Arching the lower back to press, that turns it into an incline press.',
        'Pressing the bells forward instead of straight up.',
        'Half lockouts.',
      ],
      videoQuery: 'dumbbell shoulder press form',
      restSec: 120,
    }),
    E({
      id: 'lat-pulldown',
      name: 'Lat Pulldown',
      kind: 'lift',
      equipment: 'Cable machine',
      steps: [
        'Grip the bar wider than shoulders, thighs snug under the pads, chest tall with a few degrees of lean-back.',
        'Pull the bar to your upper chest, driving the elbows down and back, then let it rise ALL the way to stretched arms.',
        'The torso stays quiet, no rocking to move the stack. Squeeze the lats for a beat at the bottom of each pull.',
      ],
      targets: {
        muscles: ['Lats', 'Upper back', 'Biceps'],
        qualities: ['Lat width when pull-ups aren’t there yet'],
      },
      why: 'The same width-building pull as a pull-up with an adjustable weight stack, perfect for building toward the first strict pull-up or adding volume past your max reps. Elbows down, lats wide.',
      mistakes: [
        'Pulling behind the neck.',
        'Rocking the torso to move the stack.',
        'Stopping the stretch halfway up.',
      ],
      videoQuery: 'lat pulldown proper form',
      restSec: 120,
    }),
    E({
      id: 'seated-cable-row',
      name: 'Seated Cable Row',
      kind: 'lift',
      equipment: 'Cable machine',
      steps: [
        'Sit tall, feet braced, knees soft, holding the handle with both hands.',
        'Let the weight pull you into a full stretch, then pull the handle to your lower ribs, elbows driving straight back. Return slow.',
        'Squeeze the blades together at the back, chest proud. The torso moves only a few degrees, no rocking chair.',
      ],
      targets: {
        muscles: ['Mid-back', 'Lats', 'Rear delts', 'Biceps'],
        qualities: ['Back thickness', 'Strict rowing volume'],
      },
      why: 'Constant cable tension through the entire range, stretch to squeeze, makes this the cleanest thickness-builder in the gym. It rows heavy without asking anything of the lower back.',
      mistakes: [
        'Turning it into a rocking chair, torso stays near vertical.',
        'Shrugging the shoulders up toward the ears.',
        'Short pumps with no front stretch.',
      ],
      videoQuery: 'seated cable row form',
      restSec: 120,
    }),
    E({
      id: 'leg-press',
      name: 'Leg Press',
      kind: 'lift',
      equipment: 'Leg press machine',
      steps: [
        'Sit in the machine, feet shoulder-width on the middle of the platform, then release the handles.',
        'Lower the sled until your knees near your chest, stopping before your lower back rolls off the pad, then press through mid-foot.',
        'Stop just short of locked knees and never slam lockout, keep tension the whole set. Don’t let the knees cave.',
      ],
      targets: {
        muscles: ['Quads', 'Glutes'],
        qualities: ['Heavy leg volume with the spine supported'],
      },
      why: 'The press loads the legs hard while the machine carries your spine, big quad and glute volume on days a barbell squat would cost more than it gives. Depth honesty makes or breaks it.',
      mistakes: [
        'Butt lifting off the pad at the bottom, that rounds the spine under load.',
        'Knees caving inward.',
        'Locking the knees hard at the top.',
      ],
      videoQuery: 'leg press machine proper form',
      restSec: 150,
    }),
    E({
      id: 'machine-leg-curl',
      name: 'Machine Leg Curl',
      kind: 'lift',
      equipment: 'Leg curl machine',
      steps: [
        'Set the pad just above your heels and line your knees up with the machine’s pivot, hips glued down.',
        'Curl your heels toward your glutes in one smooth pull, squeeze at the top, then lower on a slow 3-count to a full stretch.',
        'No hips popping up and no dropping the weight. The slow lowering is where the hamstrings grow.',
      ],
      targets: {
        muscles: ['Hamstrings'],
        qualities: ['Knee-flexion strength', 'Hamstring resilience'],
      },
      why: 'Hamstrings do two jobs, and hinges only train one. The curl isolates knee flexion, the half where sprint injuries happen, so the machine version slots straight into the protection role sliders play at home.',
      mistakes: [
        'Hips popping up to cheat the weight.',
        'Fast drops with no eccentric.',
        'Range so short the stretch never happens.',
      ],
      videoQuery: 'lying leg curl machine form',
      restSec: 120,
    }),
    E({
      id: 'bike-erg',
      name: 'Stationary Bike',
      kind: 'cardio',
      equipment: 'Bike',
      steps: [
        'Set saddle height so your knee stays slightly bent at the bottom of the stroke.',
        'Zone 2: ride 25–30 minutes at a pace where you could talk in full sentences. Harder day: 30 seconds hard, 90 easy, 8–10 rounds.',
        'Spin smooth circles at 80–95 rpm with a quiet upper body, don’t grind a huge gear.',
      ],
      targets: {
        muscles: ['Quads', 'Heart'],
        qualities: ['Zero-impact conditioning'],
      },
      why: 'All the engine-building of running with none of the pounding, the bike lets you add conditioning volume on tired legs without stealing from lifting or speed days.',
      mistakes: [
        'Grinding a huge gear at low rpm, spin 80–95.',
        'Turning every ride into a race; easy days easy.',
      ],
      videoQuery: 'zone 2 stationary bike training',
      restSec: 0,
    }),
    E({
      id: 'rowing-erg',
      name: 'Rowing Machine',
      kind: 'cardio',
      equipment: 'Rower',
      steps: [
        'Strap in and order every stroke: legs push, then hips swing back, then arms pull to the ribs.',
        'Return in reverse (arms away, hips forward, knees bend) and keep driving with the LEGS, the arms only finish the stroke.',
        'Flat back at the catch, no arm-first pulling. Zone 2 is 20–25 conversational minutes, hard days are 500 m repeats with equal rest.',
      ],
      targets: {
        muscles: ['Legs', 'Back', 'Heart'],
        qualities: ['Full-body conditioning', 'Posterior chain endurance'],
      },
      why: 'The rower conditions the whole body, legs, back, and lungs in every stroke, with zero impact. The closest thing to a second workout hiding inside a cardio machine.',
      mistakes: [
        'Pulling with the arms first, legs start every stroke.',
        'Hunching the back at the catch.',
        'Flying up the slide and slamming the catch.',
      ],
      videoQuery: 'rowing machine technique legs drive',
      restSec: 0,
    }),
    E({
      id: 'db-rdl',
      name: 'DB Romanian Deadlift',
      kind: 'lift',
      equipment: 'Dumbbells',
      steps: [
        'Stand tall with a dumbbell in each hand resting on your thighs, knees soft and fixed at that angle.',
        'Push your hips back so the bells slide down your legs to mid-shin, where the hamstrings pull hard, then drive the hips forward to stand.',
        'Back flat and bells close the whole way, squeeze the glutes at the top. Hinge back, never squat down.',
      ],
      targets: {
        muscles: ['Hamstrings', 'Glutes', 'Lower back', 'Grip'],
        qualities: ['Hip hinge without a barbell'],
      },
      why: 'The same hinge that builds the entire posterior chain, in dumbbell form, no bar, no rack, same rules: hips back, flat back, bells on the legs. The pattern every athlete keeps for life.',
      mistakes: [
        'Squatting the weight down instead of hinging back.',
        'Rounding the back to chase the floor.',
        'Bells drifting away from the legs.',
      ],
      videoQuery: 'dumbbell romanian deadlift form',
      restSec: 150,
    }),
    // ---- Athletic Performance Library (organized by athletic quality) ----
    ...ATHLETIC_EXERCISES,
  ].map((e) => [e.id, e]),
)

export function getExercise(id: string): ExerciseDef {
  const def = EXERCISES[id]
  if (!def) throw new Error(`Unknown exercise id: ${id}`)
  return def
}

export const ALL_EXERCISE_IDS = Object.keys(EXERCISES)
